### ISSUE TITLE
Performance of website open in mobile & Desktop its low speed 

### ISSUE THREAD

**Issue by webdeveloperswj** [thenewboston-developers/Website#1002]
**Bug Description**
Performance of website open in mobile & Desktop its low speed 

**Steps to Reproduce**
1. Copy URL "https://www.thenewboston.com/" 
2. go to "https://developers.google.com/speed/pagespeed/insights/"
3. paste URL "https://www.thenewboston.com/" in Enter a web page URL 

**Expected behavior**
The speed of website open it must be score 90-100

**Actual behavior**
In mobile website open speed is 30
and Desktop 40

**Screenshots/Recordings**
https://prnt.sc/vo6tg9 ->mobile
https://prnt.sc/vo6ttz ->Desktop

**OS and Browser**
 - OS:  Windows 10
 - Browser Chrome

**Comment by mersimoski** [comment]
Well, even youtube a Google products sucks at their testers, thats because page insights tests on overall network quality which in the world more percentage have slow internet. If you want to provide the best UX for the website then try to get 100% on GTMetrix or Pingdom Tools.

**Comment by Hristijan95** [comment]
We should consider SSR for the website, it will increase performance, but we'll also have more abilities for SEO.
But this will be something in a longer-term, right now it's not a priority.

**Comment by manishram** [comment]
> We should consider SSR for the website, it will increase performance, but we'll also have more abilities for SEO.

We can use the **PageSpeed Module with Nginx**. We will get a bunch of configurations for Server-side Rendering.
https://developers.google.com/speed/pagespeed/module

**Comment by MahadAdil** [comment]
Hi there, 
How about using Cloud Flare Pro? It enhances security and a lot of optimization tools for websites. I've used in one of my websites and it works great.

**Comment by denistsoi** [comment]
Attached Screenshots from lightroom report below: 
<img width="678" alt="Screenshot 2021-01-14 at 11 06 50 PM" src="https://user-images.githubusercontent.com/3061779/104608765-3e5caa00-56bd-11eb-81ca-3af71e9e85b6.png">

<img width="675" alt="Screenshot 2021-01-14 at 11 07 00 PM" src="https://user-images.githubusercontent.com/3061779/104608751-3b61b980-56bd-11eb-8d2a-2ec70875c395.png">
