### ISSUE TITLE
Update the team pages

### ISSUE THREAD

**Issue by Hristijan95** [thenewboston-developers/Website#1013]
There is a new design and functionality updates for the teams page (https://thenewboston.com/teams).

Figma design for "All Teams": https://www.figma.com/file/SIc8HUnq7mDy7T1cWrKaG8/Teams-V2?node-id=0%3A1
Figma design for "Individual Teams": https://www.figma.com/file/SIc8HUnq7mDy7T1cWrKaG8/Teams-V2?node-id=8%3A241

All team tabs should be linkable, meaning we should be able to navigate to a specific place inside the team, for example Design > Members.
Team members in each team should be sorted like this:
- Team Leads first (sorted alphabetically)
- All other members after (sorted alphabetically)

The content of All > Resources right now is located [here](https://thenewboston.com/project-proposals/overview), in the internal section. The internal section of the website should be removed completely and move that content in All > Resources.
We also need one more section in All > Resources - the content of the following document: 
[TNB Payments.pdf](https://github.com/thenewboston-developers/Website/files/5586465/TNB.Payments.pdf)

The content for all Individual Teams > Overview can be found in this document:
[Roles & Responsibilities.pdf](https://github.com/thenewboston-developers/Website/files/5586495/Roles.Responsibilities.pdf)
For the teams where the Roles & Responsibilities are not mentioned in the document, just put the team name for now. 

Please make sure to reuse existing components as much as possible & follow the [Style](https://thenewboston.com/style-guide/css) & [Code](https://thenewboston.com/style-guide/react) rules.

**Comment by AbhayAysola** [comment]
Can I work on this?

**Comment by thesanjeevsharma** [comment]
@AbhayAysola All yours!

**Comment by subhamg** [comment]
@thesanjeevsharma 
Please let me work on this issue. I'm familiar with figma and good at frontend aspects of website.

**Comment by AbhayAysola** [comment]
@subhamg Sure! I made some progress, but it's proving a little difficult for me. You can check out my fork at [https://github.com/AbhayAysola/Website](https://github.com/AbhayAysola/Website) and use the code I wrote if you want, or you could do it from scratch.

**Comment by Hristijan95** [comment]
@AbhayAysola you are not working on it anymore? If that's the case, let us know, so we can reassign the issue.

**Comment by AbhayAysola** [comment]
@Hristijan95 I'm working on it right now, but I wouldn't mind if someone more experienced works on it. I can complete the task, but since this is one of my first large scale React project, I'm not sure if the code quality would be up to par. I'll leave it up to you and @subhamg to decide. I don't think I communicated properly in my last comment 😓

**Comment by subhamg** [comment]
> @Hristijan95 I'm working on it right now, but I wouldn't mind if someone more experienced works on it. I can complete the task, but since this is one of my first large scale React projects, I'm not sure if the code quality would be up to par. I'll leave it up to you and @subhamg to decide. I don't think I communicated properly in my last comment 😓

I can take this task @Hristijan95

**Comment by Hristijan95** [comment]
Sure, @subhamg, collaborate with @AbhayAysola on it.

**Comment by AbhayAysola** [comment]
So @subhamg have you checked out my [fork](https://github.com/AbhayAysola/Website)? We just need to add content now, for the resources page.

**Comment by subhamg** [comment]
> So @subhamg have you checked out my [fork](https://github.com/AbhayAysola/Website)? We just need to add content now, for the resources page.

Yes, I did and I'm working on it.

**Comment by thesanjeevsharma** [comment]
@subhamg Hey! How's is it coming along?

**Comment by subhamg** [comment]
> @subhamg Hey! How's is it coming along?

@thesanjeevsharma I'm on it.

**Comment by Hristijan95** [comment]
@subhamg , can you give us some rough estimate on when you plan on finishing this?

**Comment by subhamg** [comment]
a
