### ISSUE TITLE
Teams Page for Research has a couple errors

### ISSUE THREAD

**Issue by colfax23** [thenewboston-developers/Website#1017]
Hey all, I was looking at the teams page for the research team and there seem to be a couple issues:

https://thenewboston.com/teams

1. Mircea is displayed as on the team, but is not (to my knowledge).  If I am mistaken please have him reach out to me!

2. Joe Sykes just joined the team, I created an Issue, and it looks like the PR got merged here https://github.com/thenewboston-developers/Website/issues/921 but he does not appear on the website.
He is here in the teams.json - do you know what is going on?
https://github.com/thenewboston-developers/Website/blob/development/src/data/teams.json#L777

Can you please look into these?  Thanks!

**Comment by thesanjeevsharma** [comment]
@colfax23 That's weird! I can see him on my dev server but not the website. I'll look into it.

**Comment by colfax23** [comment]
Thanks @thesanjeevsharma !

**Comment by Hristijan95** [comment]
#1013 could fix this since the task is changing a lot of the teams page

**Comment by thesanjeevsharma** [comment]
@colfax23 Your issue is resolved now! Closing this.
