### ISSUE TITLE
[Suggestion] Automate testing/linting using github actions

### ISSUE THREAD

**Issue by jamessspanggg** [thenewboston-developers/Website#1032]
Currently, the repository has certain code styles to obey, such as code styles for javascript, typescript by `eslint`.

Code reviewers would have to manually look through PR code styles and request changes if the PR changes does not fully obey the code styles.

Suggestion: use github actions to automate the linting or any testings that may be constructed in the future.

Advantages:
- Saves effort from code reviewers on code styles
- Serves as a reminder for contributors obey the code styles, since the github status checks will fail in the PR if not obeyed

Am happy to work on this if this is needed.

**Comment by jamessspanggg** [comment]
@lapstjup @thesanjeevsharma @Hristijan95 since this mainly impacts the code reviewers, what do you guys think of this? 

Github actions are free for open source projects, with limits such as:
- 1000 API requests per hour
- 20 concurrent jobs at a time
Taken from [here](https://docs.github.com/en/free-pro-team@latest/actions/reference/usage-limits-billing-and-administration)

**Comment by thesanjeevsharma** [comment]
@jamessspanggg Yes! I've thinking about it but didn't get time to implement it. Really nice suggestion. Love it.
