### ISSUE TITLE
[Suggestion] Linter for css/scss files

### ISSUE THREAD

**Issue by jamessspanggg** [thenewboston-developers/Website#1036]
Currently, the website only has linter (eslint) only for js, ts, and tsx files.

CSS and SCSS files however, do not have a linter. I believe we can consider [stylelint](https://stylelint.io/) as the linter for CSS and SCSS files, as that would save the code reviewers' efforts to look through CSS styles. We can try our best to configure the linter to the style guide listed [here](https://www.thenewboston.com/style-guide/css)

We can incorporate the linter to the github action workflow done in https://github.com/thenewboston-developers/Website/pull/1033 as well.

If this is appropriate, do assign me for this task.

**Comment by Hristijan95** [comment]
I agree, it's something that will help a lot. @thesanjeevsharma @lapstjup what do you think?

**Comment by jamessspanggg** [comment]
I'll work on this then!
