### ISSUE TITLE
[Suggestion] Use semantic HTML

### ISSUE THREAD

**Issue by sno2** [thenewboston-developers/Website#1037]
Why are we not using semantic HTML?  If you look at one of the [website docs pages](https://thenewboston.com/account-manager/get-started), you can see that we are using div upon div upon divs.

For example, for the navigation sidebar on the left of the different sections of the documentation,

![Navigation Sidebar](https://user-images.githubusercontent.com/43641633/100386354-b62a2480-2fea-11eb-973e-4557aa427e44.png)

we are using javascript to toggle the visibility of each section with classes.  However, you can't even press on the arrow to hide and show each section.  This would be a perfect place to use the summary and details tags as it is already accessible and we can just target the automatically added `open` attribute.  Also, the navigation section should be a `nav` element with a bunch of `detail`s and `summary`s within.  I guess we could also opt for the `aside > details > (summary  + (nav > a))` way.  This idea should also be implemented for the top navigation bar.

This is one example in which we should be adding semantic html to make our website easier to develop and use.  I guess the question we should be asking ourselves right now is if we are going to use semantic html or not.

**Comment by hydra91** [comment]
@wakawakathedev please review

**Comment by wakawakathedev** [comment]
this is a nice to have - not top priority in the backlog
