### ISSUE TITLE
[Leaderboard] High ranking number exceeds container in mobile view

### ISSUE THREAD

**Issue by jamessspanggg** [thenewboston-developers/Website#1041]
**Bug Description**
While in leaderboard page with mobile, high ranking numbers seem to exceed their container.

**Steps to Reproduce**
1. Using mobile phone, visit leaderboard page
2. Click on All top contributors
3. Scroll down to the bottom for the higher ranking numbers
4. View that the number exceeds the container

**Expected behavior**
The ranking number should not exceed the bubble container.

**Actual behavior**
The ranking number exceeds the bubble container.

**Screenshots/Recordings**
![IMG_3224](https://user-images.githubusercontent.com/32864116/100426938-9ff49500-30cc-11eb-9707-890c9913ea3c.PNG)

**OS and Browser**
 - OS: iPhone XR, Safari

**Additional context**
Perhaps reduce the font size of the rankings in mobile view?

**Account Number**
Acc no: c54c04774efaae20746fd3f29cdd619fea512e119bc1082b863572b2e8844104

**Comment by AbhayAysola** [comment]
Can I fix this?

**Comment by jamessspanggg** [comment]
Go ahead @AbhayAysola

**Comment by nparoski** [comment]
Hey I also had my take on this issue, here is my PR #1054

**Comment by uipalette** [comment]
Yeah, we can reduce the font size or make a rectangle with a border-radius instead of a circle for larger numbers. Is it ready from design ?
