### ISSUE TITLE
The leaderboard page redirects to the home page

### ISSUE THREAD

**Issue by YashovardhanSingh** [thenewboston-developers/Website#1042]
**Bug Description**
When we go to the [leaderboard page](https://thenewboston.com/leaderboard) it redirects us to the [Home page](https://thenewboston.com/) but it should be redirected to https://thenewboston.com/leaderboard/All (first section of the leaderboard).

**Steps to Reproduce**

1. Go to https://thenewboston.com/leaderboard
1. See the error

**Expected behavior**
We should be redirected to all-leaderboard

**Actual behavior**
We are redirected to the home page

**OS and Browser**

- OS: Windows 10
- Browser: Chrome

**Account Number**
38a99b8f1916eab0471ca1df26e7fe5e71d845e6ea5b233cd3d93a75097ea2d6

**Comment by Hristijan95** [comment]
When fixing it, use the same logic used for the openings: `<Redirect exact from="/openings" to="/openings/All" />`

**Comment by nparoski** [comment]
Alright i will take on this issue i will link PR as soon as I open it.

**Comment by YashovardhanSingh** [comment]
https://github.com/thenewboston-developers/Website/pull/1043
