### ISSUE TITLE
New Job Opening

### ISSUE THREAD

**Issue by kristykjlee** [thenewboston-developers/Website#1046]
Add the following job opening to the website.

***

#### Job Title
Graphic Designer

#### Job Description
As a graphic designer, you will create high-fidelity graphics for our social media team and marketing team.

#### Responsibilities
- Create HiFi graphics for social media posts & marketing content
- Give design reviews to community members making infographics
- Review end results with design team
- Send completed graphics to social media & marketing team for them to post
- Be a part of creating our visual language

#### Technology Requirements
- Skilled in Figma
- Skilled in Illustrator

#### Reports To
- First Name: [Kristy Lee, David Yap]
- Slack Name: [#design]

#### Pay
- 2,800 coins/day

#### Application channels
- Slack - Message [Kristy KJ Lee & David Yap]
- LinkedIn
- Twitter
- Reddit

**Comment by jamessspanggg** [comment]
I'll take this
