### ISSUE TITLE
New Job Opening

### ISSUE THREAD

**Issue by kristykjlee** [thenewboston-developers/Website#1047]
Add the following job opening to the website.

***

#### Job Title
Content Writer

#### Job Description
Work with our marketing team to create written content for email campaigns and blogs to make awareness about our product. 

#### Responsibilities
- Create written material for our email campaigns 
- Produce well-researched content for blogs
- Give feedback on writings

#### Technical Requirements
- An understanding of search engine optimization best practices
- Understanding grammar rules and how to construct clear sentences
- Being mindful of things like flow, readability, and sentence variety

#### Reports To
- First Name: [Pulkit & Siddhesh]
- Slack Name: [Pulkit Bajaj & Siddhesh Kulthe - Head Of Marketing]

#### Pay
- 2,800 coins/day

#### Application channels
- Slack - Message [Pulkit Bajaj & Siddhesh Kulthe - Head Of Marketing]
- LinkedIn
- Twitter
- Reddit

**Comment by kristykjlee** [comment]
@Hristijan95 Hi! The description on the website is not what is written in the issue. Can you please update this? 
![Screen Shot 2020-12-02 at 12 07 07 AM](https://user-images.githubusercontent.com/68207101/100845605-59879900-3432-11eb-8458-a0408ffbe4d7.png)

**Comment by Hristijan95** [comment]
@kristykjlee, sorry, I don't know how I managed to mess it up. It's fixed now, once Bucky deploys it, the changes will be up on the website

**Comment by kristykjlee** [comment]
> @kristykjlee, sorry, I don't know how I managed to mess it up. It's fixed now, once Bucky deploys it, the changes will be up on the website

@Hristijan95 it's all good! Thanks for fixing 🙂
