### ISSUE TITLE
Guide page Responsiveness

### ISSUE THREAD

**Issue by kristykjlee** [thenewboston-developers/Website#105]
- For Guide & APIs pages, we will now have a max width of 720px specifically for the written information.
- Leave diagrams to be the same width they already are. (Bc some diagrams are best viewed past 720px width.)
- Breakpoint of 768px, can still fit 720px information. 
- Marketing Site itself will always have left and right padding of 12px.
- Once 768px breakpoint is reached, the side menu will truncate into a dropdown menu under the top nav. 
- If API page titles get too long on mobile, please use ellipses. (...)

Guide
https://www.figma.com/file/ChyT88EmP2Rmzx35I9erCL/Marketing-Site?node-id=55%3A0

**Comment by BozidarSiljanoski** [comment]
I'll work on this
