### ISSUE TITLE
Download button weird behaviour

### ISSUE THREAD

**Issue by Hristijan95** [thenewboston-developers/Website#1055]
**Bug Description**
Download button strange behavior 

**Steps to Reproduce**
1. Go to https://thenewboston.com/download
2. Refresh the page
3. After the refresh you'll notice that the text in the button is in 2 rows instead of 1
4. Click the button and the text will go in 1 line, but it will have wrong alignment.

**Expected behavior**
The button UI should be consistent all the time

**Actual behavior**
The button text is in one row initially and it looks good. After page reloads the button text is in 2 rows and when you click on it it goes back into one row, but it's not aligned well.

**Screenshots/Recordings**
After page refresh:
![Screenshot 2020-11-28 at 20 04 13](https://user-images.githubusercontent.com/5727677/100524053-27b5ce80-31b5-11eb-9b63-f7643e77d3c9.png)

After clicking on it:
![Screenshot 2020-11-28 at 17 29 35](https://user-images.githubusercontent.com/5727677/100524059-33a19080-31b5-11eb-8bd1-7c5a417dc62d.png)

**OS and Browser**
 - OS: MacOS Big Sur
 - Safari

**Comment by jamessspanggg** [comment]
Note: Cannot replicate in Chrome but able to in Safari.

It's a very weird bug, I tried changing the text from `Download for Mac` -> `Download for MAC` and the bug no longer occurs. Seems like it occurs specifically for the text `Download for Mac` where it auto wraps the text

**Comment by Duke123-tech** [comment]
I could see in the 'inspector' that string for button is in two rows, yet button wouldn't double up  in my browser. It's 
related with click event on the page, to my knowledge, because of some detail related with Css. By.

**Comment by jay7134** [comment]
Interested to contribute

**Comment by SirDaev** [comment]
Using a template literal it only outputs a single string. I cannot duplicate this issue but I believe this will prevent it.
