### ISSUE TITLE
Responsive Top Nav

### ISSUE THREAD

**Issue by kristykjlee** [thenewboston-developers/Website#106]
- Breakpoint of 768px will truncate the top nav options into a hamburger menu.  
- Clicking/tapping onto the hamburger menu will then trigger a dropdown of the top nav functionality. 

Landing Page Example
https://www.figma.com/file/ChyT88EmP2Rmzx35I9erCL/Marketing-Site?node-id=6%3A0

Hamburger Icon
[Hamburger.zip](https://github.com/thenewboston-developers/Website/files/4978674/Hamburger.zip)

**Comment by BozidarSiljanoski** [comment]
I'll work on this
