### ISSUE TITLE
Prepare the top navigation for user profile

### ISSUE THREAD

**Issue by Hristijan95** [thenewboston-developers/Website#1061]
As part of #315 , the idea of this task is to prepare the top navigation for the profile page.

We need to edit the top navigation as shown in the figma design here: https://www.figma.com/file/ChyT88EmP2Rmzx35I9erCL/Marketing-Site?node-id=1353%3A1915

- [ ] Add the Sign In and Create Account buttons in the menu
- [ ] Add the Profile icon with a dropdown menu with 2 options (Your Profile / Sign Out)
- [ ] Apply the same changes to the mobile menu (make sure you follow the figma design)
- [ ] Update the navigation items on the mobile menu to have 24px spacing between them
- [ ] Change the Get Started & Community options into a dropdown as per the figma design. Right now they are all displayed

Note: You'll notice there's already a "Login with GitHub" button in `src/components/TopNav/index.tsx`. Uncomment that button & make it part of your solution by editing it to match the requirements.

**Comment by amarjeet987** [comment]
I'll take it.

**Comment by amarjeet987** [comment]
PR: https://github.com/thenewboston-developers/Website/pull/1100

**Comment by jamessspanggg** [comment]
Closing this as it is done
