### ISSUE TITLE
Create the "Profile Info" section of the profile page

### ISSUE THREAD

**Issue by Hristijan95** [thenewboston-developers/Website#1062]
This issue is part of #315 , the idea is to create the left (profile info) section of the page. You can check the Figma design here: https://www.figma.com/file/ChyT88EmP2Rmzx35I9erCL/Marketing-Site?node-id=1353%3A1915

Just to note, the avatar has a white stroke (2px) around it, so it doesn't blend in with the background color.
On the 1366px screens, the user info block & the task completed block that's been designed is the max width of those containers, for smaller screens, the blocks will respond according to the tablet/mobile

There's an existing empty component in `src/containers/Profile/index.tsx` . This is the component where the "Profile Info" section and the "Tasks Completes" section should go. Use this section to place your component that you should create inside the `src/containers/Profile` directory.

**Comment by uipalette** [comment]
Hey, I am just starting. So created a fork and started the project but no sign-in feature yet in the develop branch. Is anybody working on it from which I can extend the branch?

**Comment by Hristijan95** [comment]
@uipalette, why do you need a sign-in feature? This specific task is just to create the left (profile info) section of the /user/profile page. The idea is to only draw the UI. We'll connect everything later with the other features & the real user data.

![Screenshot 2020-11-30 at 14 19 30](https://user-images.githubusercontent.com/5727677/100614880-184e9680-3317-11eb-922e-27354e0b6390.png)

**Comment by Paul-Taiwo** [comment]
@uipalette Are you working on this? Or should I proceed?

**Comment by jamessspanggg** [comment]
anyone working on this at the moment?

**Comment by geezerP** [comment]
@Paul-Taiwo && @jamessspanggg  anyone working on the task?

**Comment by jamessspanggg** [comment]
> @Paul-Taiwo && @jamessspanggg anyone working on the task?

Yes I am working on it.

**Comment by geezerP** [comment]
> > @Paul-Taiwo && @jamessspanggg anyone working on the task?
> 
> Yes I am working on it.

@jamessspanggg Alright noted
