### ISSUE TITLE
Create the "Tasks Completed" section of the profile page

### ISSUE THREAD

**Issue by Hristijan95** [thenewboston-developers/Website#1063]
This issue is part of #315 , the idea is to create the right (tasks completed) section of the page. You can check the Figma design here: https://www.figma.com/file/ChyT88EmP2Rmzx35I9erCL/Marketing-Site?node-id=1353%3A1915

On the 1366px screens, the user info block & the task completed block thats been designed is the max width of those containers, for smaller screens, the blocks will respond according to the tablet/mobile.

There's an existing empty component in src/containers/Profile/index.tsx . This is the component where the "Profile Info" section and the "Tasks Completes" section should go. Use this section to place your component that you should create inside the src/containers/Profile directory.

**Comment by jamessspanggg** [comment]
I'll have a go on this.
