### ISSUE TITLE
Add additional logos to Assets page

### ISSUE THREAD

**Issue by kristykjlee** [thenewboston-developers/Website#1073]
Include an option to download a white version of the logos.
https://www.figma.com/file/ChyT88EmP2Rmzx35I9erCL/Marketing-Site?node-id=2251%3A2677

[Logo & Wordmark.zip](https://github.com/thenewboston-developers/Website/files/5640458/Logo.Wordmark.zip)

**Comment by leelatanniru** [comment]
I would like to work on this. I will do a PR before 7th december. Thank you.

**Comment by Duke123-tech** [comment]
<span xpath="1">question</span>

**Comment by Duke123-tech** [comment]
//a[@class='IssueLabel--big d-inline-block v-align-top lh-condensed js-label-link']//span[contains(text(),'question')]

**Comment by leelatanniru** [comment]
I finished working on it in my local. Facing an issue related to prettier format, will fix it and create a PR tomorrow. I don't have write access to upload the zip file to https://github.com/thenewboston-developers/Marketing/ @buckyroberts / @kristykjlee could you please do it. Thank you.

**Comment by manishram** [comment]
> I don't have write access to upload the zip file to https://github.com/thenewboston-developers/Marketing

Already uploaded: https://github.com/thenewboston-developers/Website/files/5640458/Logo.Wordmark.zip

**Comment by kristykjlee** [comment]
> I finished working on it in my local. Facing an issue related to prettier format, will fix it and create a PR tomorrow. I don't have write access to upload the zip file to https://github.com/thenewboston-developers/Marketing/ @buckyroberts / @kristykjlee could you please do it. Thank you.

@thesanjeevsharma @Hristijan95 @jamessspanggg  Hey guys, I dont know how to code, so I dont know how to upload the zipfile into the website, would any of you guys be able to take this on?

**Comment by jamessspanggg** [comment]
> @thesanjeevsharma @Hristijan95 @jamessspanggg Hey guys, I dont know how to code, so I dont know how to upload the zipfile into the website, would any of you guys be able to take this on?

Sure. But I do not have the write access as well. @leelatanniru can you make a pull request to the marketing repository with the new file? Then tag bucky to merge it

**Comment by leelatanniru** [comment]
> > @thesanjeevsharma @Hristijan95 @jamessspanggg Hey guys, I dont know how to code, so I dont know how to upload the zipfile into the website, would any of you guys be able to take this on?
> 
> Sure. But I do not have the write access as well. @leelatanniru can you make a pull request to the marketing repository with the new file? Then tag bucky to merge it

Sure

**Comment by leelatanniru** [comment]
Sorry for the delay in doing the commit, i will do it this weekend. Thank you.

**Comment by leelatanniru** [comment]
Thanks @manishram  I am doing the commit today for this.
