### ISSUE TITLE
Job Description

### ISSUE THREAD

**Issue by kristykjlee** [thenewboston-developers/Website#1084]
Add the following job opening to the website.

***

#### Job Title
SEO Manager

#### Job Description
We are looking for an SEO Manager to coordinate SEO efforts, including onsite and offsite optimization and keyword expansion research. You’ll also oversee paid search campaigns to ensure their success. We are looking for an analytical and perceptive professional who is a skilled communicator and able to collaborate with various teams. Current knowledge of SEO practices and techniques is essential to this role. Your goal will be to ensure that content is search-engine friendly and optimized to increase our company’s profitability

#### Responsibilities
1. Develop and execute successful SEO strategies
2. Conduct keyword research to guide content teams
3. Review technical SEO issues and recommend fixes
4. Optimize website content, landing pages and paid search copy
5. Collect data and report on traffic, rankings and other SEO aspects
6. Work with social media to optimize campaigns

#### Technology Requirements
1. Knowledge of standard and current SEO practices
2. Experience with SEO reporting
3. Familiarity with relevant tools (e.g. Conductor, Screaming Frog, MOZ) and web analytics tools (e.g. Google Analytics, WebTrends)

#### Reports To
- First Name: [Siddhesh]
- Slack Name: [Siddhesh Kulthe]

#### Pay
- 2,800 coins/day

#### Application channels
- Slack - Message [Siddhesh Kulthe]
- LinkedIn
- Twitter
- Reddit

**Comment by alexkimeu0** [comment]
I would like to take this one.

**Comment by jamessspanggg** [comment]
@alexkimeu0 go ahead

**Comment by Duke123-tech** [comment]
'A nuclear power-plant safety inspector' in Sprnigfield is looked for now.

**Comment by alexkimeu0** [comment]
Hello @kristykjlee, to what category does this opening fall ? Also, does the person to report to have a Github account?

**Comment by kristykjlee** [comment]
> Hello @kristykjlee, to what category does this opening fall ? Also, does the person to report to have a Github account?

@alexkimeu0 Hey! SEO Manager will fall under the Marketing team.
