### ISSUE TITLE
New Contributor

### ISSUE THREAD

**Issue by IanArb** [thenewboston-developers/Website#1085]
Team: Kotlin SDK

{
  "title": Software Developer,
  "isLead": false,
  "payPerDay": 2800,
  "createdDate": "2020-07-08T02:14:59.307535Z",
  "contributor": {
    "contributorId": [CONTRIBUTOR ID],
    "displayName": Nish,
    "githubUsername": nishp77,
    "profileImage": https://ca.slack-edge.com/T07PJD1FZ-U01DQ2732R5-gc833f5ec6b4-512,
    "slackUsername": Nish
  }
}

**Comment by Reeler** [comment]
What is his contributor id?

**Comment by IanArb** [comment]
Hey @Reeler this is just a placeholder that you guys need to fill in.
