### ISSUE TITLE
Landing Page responsiveness

### ISSUE THREAD

**Issue by kristykjlee** [thenewboston-developers/Website#109]
- Pngs of the app remain the same size (are not squishy), whether user is on desktop or mobile. 
- When pngs of app wrap to the bottom of the title & paragraph, please make sure it is 12px away from the left of the site. (So we see the most of the app png)
- Paragraphs & title on (instant transactions sections) are a max width of 480px.
- View Guide button comes after the 2nd paragraph (instant transaction section) 
- Update app pngs with newer pngs attached to this ticket.

Landing Page 
https://www.figma.com/file/ChyT88EmP2Rmzx35I9erCL/Marketing-Site?node-id=6%3A0

[Marketing Site PNG.zip](https://github.com/thenewboston-developers/Website/files/4978815/Marketing.Site.PNG.zip)
![Send Points Modal](https://user-images.githubusercontent.com/68207101/88491020-724be380-cf54-11ea-87b5-3aa81f59bbae.jpg)
![Full Data](https://user-images.githubusercontent.com/68207101/88491028-80016900-cf54-11ea-83c6-ef529895787f.jpg)

**Comment by BozidarSiljanoski** [comment]
I'll work on this
