### ISSUE TITLE
Alignment of doc Images

### ISSUE THREAD

**Issue by manishram** [thenewboston-developers/Website#1105]
**Bug Description**
There is an extra left margin for the heading as compared to the image content on a large screen. This behavior can be observed on all pages with images.

**Steps to Reproduce**
1. Go to https://thenewboston.com/account-manager/get-started on a large screen
2. You see image and heading are not aligned properly.

**Actual behavior**
![vfds](https://user-images.githubusercontent.com/22790904/101783682-8c134f00-3b20-11eb-9739-d5afb1b0cddf.JPG)

**Expected behavior**
![vfds2](https://user-images.githubusercontent.com/22790904/101783733-9e8d8880-3b20-11eb-9696-ad1f39d73215.JPG)

**OS and Browser**
 - OS: Windows 10
 - Browser: Chrome

**Account Number**
0f92e975101eb96cea80dce430d74efd3172fa229377818d467ded85dcf2ab6c

**Comment by manishram** [comment]
I saw the code and I found: https://github.com/thenewboston-developers/Website/blob/d4007ec229dc680e7bd8091db5645eb3b5fcb446/src/components/DocWrapper/DocContainer/DocContainer.scss#L5-L9 which seems like It was done intentionally what was the reason?

**Comment by buckyroberts** [comment]
Some diagrams/graphics are hard to read when they are squished down to a 720px width, for example this one at the bottom https://thenewboston.com/guide/confirmation-services . Our docs for the account manager and guide are using the same CSS, we can look into separating that if needed later on.
