### ISSUE TITLE
Update components/Layout/LeftMenu and component/Layout/LeftMenuGroup to follow styling guideline

### ISSUE THREAD

**Issue by angle943** [thenewboston-developers/Website#111]
Check out: https://thenewboston.com/style-guide/

**Comment by leelatanniru** [comment]
I would like to work on this

**Comment by angle943** [comment]
great thanks @leelatanniru . One thing to keep in mind with this is that currently, the `LeftMenu` and the `LeftMenuGroup` both rely on the same `scss` file. This needs to be separated into two separate files, and the styling for each should be scoped to each respective component. Please feel free to ask for help (either here or on chat) any time

**Comment by leelatanniru** [comment]
Sure @angle943 Thank you.

**Comment by angle943** [comment]
@leelatanniru this one will be closed due to a site-wide update: https://github.com/thenewboston-developers/Website/pull/126
