### ISSUE TITLE
Update the Project Proposals section

### ISSUE THREAD

**Issue by manishram** [thenewboston-developers/Website#1116]
The project proposals section: https://thenewboston.com/project-proposals/ needs to be updated.
Project Proposals Document: https://docs.google.com/document/d/1vk-yH5kNOB2DWnPu3BV3ARlTaB9TBApmcELUw57S2H4/edit

- [x] Add **Funding** sub-section to describe new funding system.
- [x] Import **Labels** component to the **Overview** sub-section and use them to mark GitHub Labels to appropriate places as per the given document.
- [x] Make important text **bold** as per the document.

**Comment by manishram** [comment]
Hey, @jamessspanggg new project proposals system needs to be announced. Before the announcement, we need to have complete information regarding it on the site. So, please review the above changes as soon as possible.

**Comment by jamessspanggg** [comment]
@manishram can you share the google docs with viewing permissions? I dont have the permissions to view it

**Comment by manishram** [comment]
Hey, @jamessspanggg I updated the link with view permission.
