### ISSUE TITLE
Sharing website link with hash param does not snap to correct position

### ISSUE THREAD

**Issue by jamessspanggg** [thenewboston-developers/Website#1127]
**Bug Description**
When visiting a link that has a hash param, i.e. https://www.thenewboston.com/deployment-guide/validator#firewall, the page does not automatically snap to the correct position of the anchor.

**Steps to Reproduce**
1. Go to https://www.thenewboston.com/deployment-guide/validator#firewall or other links with anchor
2. View that it does not snap correctly to the anchor position

**Expected behavior**
Snap to correct position of anchor

**Actual behavior**
Does not snap to correct position

**Screenshots/Recordings**
N.A.

**OS and Browser**
 - OS: Mac Safari/Chrome

**Additional context**
Does not occur in development, only at the official website

**Account Number**
c54c04774efaae20746fd3f29cdd619fea512e119bc1082b863572b2e8844104

**Comment by jamessspanggg** [comment]
The underlying issue might be related to #595

**Comment by SirDaev** [comment]
Could this be related to [this issue with React Router](https://github.com/ReactTraining/react-router/issues/394#issuecomment-220221604)? A potential fix for shared links might be to utilize `.scrollIntoView()` inside `useEffect()` in `<Layout />`.

**Comment by jamessspanggg** [comment]
> Could this be related to [this issue with React Router](https://github.com/ReactTraining/react-router/issues/394#issuecomment-220221604)? A potential fix for shared links might be to utilize `.scrollIntoView()` inside `useEffect()` in `<Layout />`.

Hmm, but when in development, the snapping works fine though so I don't think it's an issue with React Router? Not sure though :/
