### ISSUE TITLE
Update the Icon library to use `mdi-react` (hint, make it the same as the one in AccountManager Repo)

### ISSUE THREAD

**Issue by angle943** [thenewboston-developers/Website#113]
Currently, this repo uses `material-icons` font library to display icons. We want to update this to use SVGs (just like it is done in AccountManager)

1) Install `mdi-react` and create a new component just like the one found in our website repo: https://github.com/thenewboston-developers/Account-Manager/tree/master/src/renderer/components/Icon

2) update all occurrences of `material-icons` to use the newly added `Icon` component.

3) Erase/uninstall all traces of `material-icons`

Resources: you can find the name of the icons here: https://github.com/thenewboston-developers/Account-Manager/tree/master/src/renderer/components/Icon

**Comment by leelatanniru** [comment]
I would like to work on this.
