### ISSUE TITLE
New Contributor

### ISSUE THREAD

**Issue by benjithorpe** [thenewboston-developers/Website#1144]
Team: [Community]

{
  "title": [Slack Community Manager],
  "isLead": [false],
  "payPerDay": 2800,
  "createdDate": "2020-07-08T02:14:59.307535Z",
  "contributor": {
    "contributorId": [CONTRIBUTOR ID],
    "displayName": [Chris Meninwa - Slack Manager],
    "githubUsername": [GITHUB USERNAME],
    "profileImage": [ https://ca.slack-edge.com/T07PJD1FZ-U01EHEJQUMS-g820abfd57a6-512],
    "slackUsername": [Chris Meninwa - Slack Manager]
  }
}

**Comment by jamessspanggg** [comment]
@benjithorpe is it possible to provide the user's github username as well as the github profile image url?

**Comment by benjithorpe** [comment]
@jamessspanggg he is not currently on github.

**Comment by thesanjeevsharma** [comment]
@benjithorpe Can you ask Chris to create an account and comment here?

**Comment by benjithorpe** [comment]
Ok, I will

**Comment by oluwatomiwatemidayo** [comment]
What is this task about?

**Comment by jamessspanggg** [comment]
> What is this task about?

This task adds a new contributor to this page: https://www.thenewboston.com/teams/All. However, there is an existing PR #1145 that fixes this.

**Comment by oluwatomiwatemidayo** [comment]
> > What is this task about?
> 
> This task adds a new contributor to this page: https://www.thenewboston.com/teams/All. However, there is an existing PR #1145 that fixes this.

Okay, Thanks.

**Comment by jamessspanggg** [comment]
@benjithorpe any updates on this?

**Comment by benjithorpe** [comment]
@jamessspanggg I have already ask Chris to create an account and comment here.
I still dont know why he has not done that. I'll check with him again.

sorry for the late reply
