### ISSUE TITLE
Top contributors not showing in README

### ISSUE THREAD

**Issue by jamessspanggg** [thenewboston-developers/Website#1147]
The top contributors (from sourceror.io) is not showing in the README:

<img width="938" alt="Screen Shot 2020-12-24 at 7 17 49 PM" src="https://user-images.githubusercontent.com/32864116/103085460-b7b43000-461c-11eb-90a9-39537029d225.png">

**Comment by jamessspanggg** [comment]
Related: https://github.com/sourcerer-io/hall-of-fame/issues/53

**Comment by thesanjeevsharma** [comment]
@jamessspanggg Let's remove that part from README then!
