### ISSUE TITLE
Slack link on homepage no longer active

### ISSUE THREAD

**Issue by LunarDeveloper** [thenewboston-developers/Website#1152]
**Bug Description**
The slack link on the homepage now takes users to a "this link is no longer active" page.

**Steps to Reproduce**
1. Go to thenewboston.com
2. Click slack link

**Expected behavior**
Should take people to the slack channel

**Actual behavior**
Takes people to a link not active page

**Account Number**
b32e6086c378b840fcece09daacfaee8ba75e0e038152406e2d2db3c0f93204e

**Comment by singh-sarabjeet** [comment]
TNB Account - c5778aee3cfd83c2088ae81c178c3d34931399f20c1492c33044d8cd85e21898
