### ISSUE TITLE
Add "Hello world" in Kartvelian language

### ISSUE THREAD

**Issue by Mikheil-A** [thenewboston-developers/Website#1176]
Team: [TEAM NAME]

{
  "title": [JOB TITLE],
  "isLead": [true OR false],
  "payPerDay": 2800,
  "createdDate": "2020-07-08T02:14:59.307535Z",
  "contributor": {
    "contributorId": [CONTRIBUTOR ID],
    "displayName": [DISPLAY NAME],
    "githubUsername": [GITHUB USERNAME],
    "profileImage": [PROFILE IMAGE URL (Slack or GitHub URL)],
    "slackUsername": [SLACK USERNAME]
  }
}

**Comment by thesanjeevsharma** [comment]
@Mikheil-A #351 exists for adding 'Hello World' in your own language. No need for a separate issue.
