### ISSUE TITLE
After going to the .NET Core page team page, all repo links transform to the .NET Core one

### ISSUE THREAD

**Issue by Mirch** [thenewboston-developers/Website#1178]
**Bug Description**
All team pages have a link to their repository. However, after clicking on the .NET Core team page, any further team repo links are actually the link to .NET Core. This does not seem to happen with any other pages.

**Steps to Reproduce**
1. Go to https://thenewboston.com/teams/All/Members
2. Click on any team except .NET Core and notice that the repo links are correct.
3. Click on '.NET Core'
4. Notice that it links to the right repository - dotnetcore-sdk.
5. Now click on any other team page - the repo links are dotnetcore-sdk.

**Expected behavior**
The repo links should remain the same.

**Actual behavior**
The repo links change to dotnetcore-sdk.

**Screenshots/Recordings**
<img width="638" alt="Screenshot 2021-01-04 at 22 34 47" src="https://user-images.githubusercontent.com/15807790/103577218-0eebb780-4edd-11eb-9c22-4ffc3b0acb01.png">

**OS and Browser**
 - OS: macOS Catalina 10.15.7
 - Browser: Chrome

**Account Number**
dc3eb7a93238a4e691817d294c97fa372748807c473130901b71b819032a2faa

**Comment by jamessspanggg** [comment]
Already fixed by #1175, which isn't merged to the master branch yet. In development branch it has been fixed.
