### ISSUE TITLE
Mobile drop down icon not clickable

### ISSUE THREAD

**Issue by jamessspanggg** [thenewboston-developers/Website#1179]
**Bug Description**
Clicking TopNavMobileMenu's drop down icons do not toggle show/hide. Clicking only the title will toggle show/hide.

**Steps to Reproduce**
1. Go to website home page with mobile device
2. Click on top right hamburger icon
3. Click on the drop down icon 
4. View that nothing happens

**Expected behavior**
Clicking on drop down icon should show/hide items

**Actual behavior**
Nothing happened 

**Screenshots/Recordings**
https://user-images.githubusercontent.com/32864116/103612713-f8d30b00-4f5f-11eb-8c03-2ad520814900.MP4

**OS and Browser**
 - OS: iOS safari

**Additional context**

**Account Number**
c54c04774efaae20746fd3f29cdd619fea512e119bc1082b863572b2e8844104

[How to Create an Account](https://thenewboston.com/account-manager/create-an-account)

**Comment by AkinAguda** [comment]
Working on this issue
