### ISSUE TITLE
WebMap popup doesn't work consistently on mobile

### ISSUE THREAD

**Issue by franchyze923** [thenewboston-developers/Website#1183]
**Bug Description**
When viewing the webmap on a mobile device, upon clicking a node, the node pop up doesn't always display. Only at certain position, if it is clicked again then the popup is visible until closed or loses focus.

**Steps to Reproduce**
1. Go to website home page with mobile device
2. Click on top right hamburger icon
3. Click More
4. Click WebMap
5. Click on an bank/validator icon and observe that the pop up doesn't always display. 

**Expected behavior**
The popup should always display and be visible upon click. 

**Actual behavior**
Popup displays for a brief second and then goes away. Sometimes it works properly. 

**Screenshots/Recordings**
https://user-images.githubusercontent.com/9319623/103895685-ca1f7680-50be-11eb-9964-dc55cfe5e71b.MP4

**OS and Browser**
 - OS: iOS safari

**Additional context**

**Account Number**
da8500cb8e2ffd728f919cfae82b1c4e97ca2558f2545ab1b020a4172642dce3

[How to Create an Account](https://thenewboston.com/account-manager/create-an-account)

**Comment by etfaghaoubeid** [comment]
Hello @franchyze923 , i will fix this

**Comment by amarjeet987** [comment]
@etfaghaoubeid any update on this one?
