### ISSUE TITLE
Unable to Create Account

### ISSUE THREAD

**Issue by adewolejosh** [thenewboston-developers/Website#1184]
Hi there, I am new to open source and just got to know about this community. Here's my issue:
I tried creating an account on thenewboston website, it asked for (email, password and confirm password), after filling all correctly I got "AUTHENTICATION CREDENTIALS WERE NOT PROVIDED". I don't know if there's something I'm missing or if it's a bug.

**Comment by denistsoi** [comment]
```
Request URL: https://api.thenewboston.com/users
Request Method: POST
Status Code: 403 Forbidden
Remote Address: 34.209.106.188:443
Referrer Policy: strict-origin-when-cross-origin
```

**Comment by denistsoi** [comment]
@adewolejosh seems that it's ok now - unsure how this was resolved

**Comment by adewolejosh** [comment]
@denistsoi thanks for letting me know.
