### ISSUE TITLE
New Contributor - Tristan Spearing

### ISSUE THREAD

**Issue by iamsid47** [thenewboston-developers/Website#1186]
Team: Marketing
{
  "title": Marketing Analyst,
  "isLead": false,
  "payPerDay": 2800,
  "createdDate": "2020-07-08T02:14:59.307535Z",
  "contributor": {
    "contributorId": U01JJ677TL0,
    "displayName": Tristan Spearing,
    "githubUsername": [GITHUB USERNAME],
    "profileImage": https://ca.slack-edge.com/T07PJD1FZ-U01JJ677TL0-88e284149aec-512,
    "slackUsername": Tristan Spearing
  }
}

**Comment by Paul-Taiwo** [comment]
I'll take this

**Comment by iamsid47** [comment]
Hey @Paul-Taiwo I see that the reference you gave is not compatible to get merged.

**Comment by Paul-Taiwo** [comment]
Hi @iamsid47 Please I don't understand what you mean by reference. Can you explain?

**Comment by iamsid47** [comment]
![Screenshot_20210115-192155_GitHub.jpg](https://user-images.githubusercontent.com/55309498/104734939-f7c38a00-5766-11eb-9cdc-6c06da437af5.jpg)

I meant this👆

**Comment by iamsid47** [comment]
Oh.. my bad. I got this in the wrong place.
You can continue with the issue. I actually misplaced the message a bit.

**Comment by Paul-Taiwo** [comment]
Actually, I created a PR that fixes the issue #1189 but no one is reviewing it.

**Comment by iamsid47** [comment]
Hold on. Maybe someone will check it in a few hours.

**Comment by Paul-Taiwo** [comment]
Alright.
