### ISSUE TITLE
New Contributor - Tomiwa

### ISSUE THREAD

**Issue by iamsid47** [thenewboston-developers/Website#1187]
Team: Marketing
{
  "title": Marketing Analyst,
  "isLead": false,
  "payPerDay": 2800,
  "createdDate": "2020-07-08T02:14:59.307535Z",
  "contributor": {
    "contributorId": U01JHJS30SC,
    "displayName": Tomiwa,
    "githubUsername": [GITHUB USERNAME],
    "profileImage": https://ca.slack-edge.com/T07PJD1FZ-U01JHJS30SC-62f5af21aed7-512,
    "slackUsername": Tomiwa
  }
}

**Comment by Paul-Taiwo** [comment]
I'll take this
