### ISSUE TITLE
New Contributor - Aathil Ahamed

### ISSUE THREAD

**Issue by iamsid47** [thenewboston-developers/Website#1188]
Team: Front End Developers
{
  "title": WordPress Developer,
  "isLead": false,
  "payPerDay": 2800,
  "createdDate": "2020-07-08T02:14:59.307535Z",
  "contributor": {
    "contributorId": U01H0QWK2BG,
    "displayName": Aathil Ahamed,
    "githubUsername": [GITHUB USERNAME],
    "profileImage": https://ca.slack-edge.com/T07PJD1FZ-U01H0QWK2BG-7b8970a84b6c-512,
    "slackUsername": ATLIT
  }
}

**Comment by Paul-Taiwo** [comment]
I'll take this
