### ISSUE TITLE
New Contributor

### ISSUE THREAD

**Issue by iamsid47** [thenewboston-developers/Website#1197]
Team: Marketing

{
  "title": Blog Writer
  "isLead": false
  "payPerDay": 2800,
  "createdDate": "2020-07-08T02:14:59.307535Z",
  "contributor": {
    "contributorId": U01G1B4V42D
    "displayName": Chibuzor Eze-nwosu
    "githubUsername": null
    "profileImage": https://ca.slack-edge.com/T07PJD1FZ-U01G1B4V42D-94d5b325b7d5-512
    "slackUsername": Chibuzor
  }
}

**Comment by Paul-Taiwo** [comment]
I'll take this.

**Comment by Paul-Taiwo** [comment]
@iamsid47 Chibuzor's Github username is not provided.

**Comment by iamsid47** [comment]
She actually doesn't have a GitHub account
