### ISSUE TITLE
Update /guide/blocks table

### ISSUE THREAD

**Issue by angle943** [thenewboston-developers/Website#1240]
in https://thenewboston.com/guide/blocks ,

There is a table that shows this:

![Screen Shot 2021-01-31 at 6 26 47 PM](https://user-images.githubusercontent.com/5943963/106407927-05794080-63f2-11eb-9c94-5f0dfdd7dfb3.png)

1) Our current cryptocurrency only allows integers for the values of the coins, so the `X.00` part is inappropriate.

AC:
1) For `coins being sent to Brian` and `Total` row, remove the decimals
2) (not required, but my opinion) For `Bank Fees` and `Validator Fees` row, I don't think the suffix `coins` is needed. I think we can remove those

**Comment by led76marx** [comment]
I have included this in #1298 - PR is #1293
