### ISSUE TITLE
New Contributor - Requested to get back on team

### ISSUE THREAD

**Issue by kristykjlee** [thenewboston-developers/Website#1256]
Team: [Design]

{
  "title": [Graphic Designer],
  "isLead": [false],
  "payPerDay": 2800,
  "createdDate": "2020-07-08T02:14:59.307535Z",
  "contributor": {
    "contributorId": [CONTRIBUTOR ID],
    "displayName": [Tolawak Gelana],
    "githubUsername": [toledit]
    "profileImage": [PROFILE IMAGE URL (Slack or GitHub URL)],
    "slackUsername": [toledit]
  }
}

**Comment by aayushi14** [comment]
#1222 need to revert and update contributorId
