### ISSUE TITLE
New Contributor

### ISSUE THREAD

**Issue by IanArb** [thenewboston-developers/Website#1261]
Team: Kotlin SDK

{
  "title": Software Developer,
  "isLead": false,
  "payPerDay": 2800,
  "createdDate": "2020-07-08T02:14:59.307535Z",
  "contributor": {
    "contributorId": [CONTRIBUTOR ID],
    "displayName": tomijaga,
    "githubUsername": tomijaga,
    "profileImage": https://avatars.githubusercontent.com/u/50385769?s=400&u=53be327b7eaabd41f4e3c1e57d958508dec12357&v=4,
    "slackUsername": tomijaga
  }
}

**Comment by dhakal0kushal** [comment]
#1285
My Account Number
22d0f0047b572a6acb6615f7aae646b0b96ddc58bfd54ed2775f885baeba3d6a
