### ISSUE TITLE
Hiring

### ISSUE THREAD

**Issue by Chrisha1212** [thenewboston-developers/Website#1265]
Add the following job opening to the website.

***

#### Job Description
We are looking for a Data Entry Operator to update and maintain information on our Marketing Team database .

#### Responsibilities
- a. Maintaining accurate, up-to-date and useable information in our systems.
- b. Comply with data integrity and security policies
- c. Keep information confidential
- d. Research and obtain further information for incomplete documents
- e. Compile, verify accuracy and sort information according to priorities to prepare source data for computer entry
- f. Review data for deficiencies or errors, correct any incompatibilities if possible and check output

#### Technology Requirements
- a. Proven data entry work experience, as a Data Entry Operator or Office Clerk
- b. Experience with MS Office and data programs
- c. Excellent knowledge of correct spelling, grammar and punctuation
- e. Can work with Marketing Team

#### Reports To
- First Name: [Chrisha]
- Slack Name: [Ms.Chrishaph]

#### Pay
- 2,800 coins/day

#### Application channels
- Slack - Message [MsChrishaph]
- LinkedIn
- Twitter
- Reddit

**Comment by dhakal0kushal** [comment]
#1285
My Account Number
22d0f0047b572a6acb6615f7aae646b0b96ddc58bfd54ed2775f885baeba3d6a
