### ISSUE TITLE
Add Project's openings to the website

### ISSUE THREAD

**Issue by manishram** [thenewboston-developers/Website#1270]
We have openings for the projects here: 
https://github.com/thenewboston-developers/Project-Proposals/blob/master/Openings/openings.md

We need to move these opening to the openings of the website, here https://thenewboston.com/openings/All

**Comment by AbhayAysola** [comment]
Can I work on this if it isn't being worked on?

**Comment by manishram** [comment]
Yeah @AbhayAysola please go ahead.

**Comment by avinashupadhya99** [comment]
Can we think about making this automated? Everytime a project owner, adds an opening in a specific format in the Project Proposals and is approved, it should automatically show up in the website.

**Comment by angle943** [comment]
@avinashupadhya99 ideally yes, this should be automated in the future. Its just further up in the pipelines of TODOs, as we are currently prioritizing a couple big changes that are coming soon

**Comment by AbhayAysola** [comment]
Account Number: 8928526805de48e4bf2ed2a9b4b839e6b2603018ecdfbf4cffdb2065e01a3ed1
