### ISSUE TITLE
Add a new job opening

### ISSUE THREAD

**Issue by yaya-BL** [thenewboston-developers/Website#1274]
Add the following job opening to the website.

***

#### Job Title

Software architect/Senior Django developer

#### Job Description

Someone with a good experience in translating business and technical requirements into comprehensive software design and architecture

#### Project name

	Restaurants-Self-Order-App

#### Responsibilities

	- Designing and creating RESTful APIs
	- Designing and optimization of the database 
	- Responsible for architectural, design of the product
	- Familiar with diagrams and documentations is a plus
	- Code review

#### Technology Requirements

	- Mainly a person who has a good skills in product designing to meet the best performance, scalability, and maintainability
	- Even if you are not experienced with Django, but you meet the main responsibilities, still DM me
	- Clean code standards
	- 5+ years of experience 

#### Reports To
- First Name: [Yahya]
- Slack Name: [@yahya]

#### Pay
- 2,800 coins/day

#### Application channels
- Slack - Message [@Yahya]

**Comment by dhakal0kushal** [comment]
#1285
My Account Number
22d0f0047b572a6acb6615f7aae646b0b96ddc58bfd54ed2775f885baeba3d6a

**Comment by manishram** [comment]
@thesanjeevsharma please approve this jon opening.
@yaya-BL is the leader of Restaurant-self-order-App project.

Project members and leaders detail for future reference: 
https://github.com/thenewboston-developers/Project-Proposals/blob/master/CSVs/project-teams.csv

**Comment by thesanjeevsharma** [comment]
@manishram @yaya-BL 

I see a similar opening on the website: https://thenewboston.com/openings/Engineering/self-order-senior-backend-django-developer

Is this different?

**Comment by manishram** [comment]
@yaya-BL your job description seems to be very similar to what we already have in the openings section as sanjeev said.

**Comment by yaya-BL** [comment]
@thesanjeevsharma  @manishram 
that was pulled from opening file in the project-proposals repo, i will create a new issue to remove both of the openings,
i only need this new one to be published in the website

**Comment by yaya-BL** [comment]
@thesanjeevsharma thanks for working on this one
I noticed that "Reports to" section is having a hyperlink to some github profile - which is not mine
that @ was meant to be for Slack name but it seems that github grabbed a github username
Can we get it fixed somehow, thanks

**Comment by thesanjeevsharma** [comment]
Sure, I'll update it.
