### ISSUE TITLE
New Contributor

### ISSUE THREAD

**Issue by manishram** [thenewboston-developers/Website#1276]
team: Recruiting Team
title: Recruiting Specialist
isLead: TRUE
display_name: Demetrio Ornelas
github_username: DemetrioOrnelas
profile_image: https://avatars.githubusercontent.com/u/47065529?s=400&v=4
slack_username: Demetrio Ornelas 
account_number: cf209735e4295b03b24ec7863a62f49196df4389076e73a67d776134961ac338

**Comment by AmrOuf** [comment]
What is the contributor id ?
