### ISSUE TITLE
Add FAQ about how to keep your wallet safe

### ISSUE THREAD

**Issue by hussu010** [thenewboston-developers/Website#1278]
Title: How do I keep my wallet safe?
Ans: Your **Signing Key** is the thing that gives you the ability to spend your coins, so as long as you keep that safe and secure then your coins are safe and secure as well.

**Comment by angle943** [comment]
Let's make this more detailed. Add pictures on how to save your signing key, etc etc

**Comment by manishram** [comment]
We have decided to make some **DOs and DON'T for Account Manager on first-time installation**, maybe we can make a separate page on the Website as well where all those information will be added including **how to keep your wallet safe** and yes like Justin said we'll be using illustrative images along with texts.

**Comment by bart-jay** [comment]
has this task been assigned?
I am available though

**Comment by oshioki4** [comment]
Title: How do I keep my wallet safe?
Ans: Try not to make transaction with a public device

**Comment by bart-jay** [comment]
Title: How do I keep my wallet safe?
Ans: Try not to carry out transaction when connected to a public unprotected internet access provider or wifi to avoid MITM security attacks.

**Comment by bart-jay** [comment]
Title: How do I keep my wallet safe?
Ans: One should always ensure private signing in keys aren't saved anywhere online, even on the cloud platforms.
These signing in keys are best kept when kept offline and very safe.

**Comment by bart-jay** [comment]
Title: How do I keep my wallet safe?
Ans: Everyone should ensure the activation of the 2FA feature on the wallet for higher security privileges.

**Comment by bart-jay** [comment]
Title: How do I keep my wallet safe?
Ans: The security of your wallet is your sole responsibility as the use because all features to ensure maximum security privileges have been  inco-operated on the wallet.  Do not share your key with any one at all. Your wallet is a private property and no one requests of you such information. Keep  them very safe.

**Comment by clove10002** [comment]
Lets make a tutorial page on how to use/secure the wallet so we can educate new comers that will use tnb wallet
also maybe adding a walkthrough guide at the very beginning of the installation for the 1st installation
