### ISSUE TITLE
Breadcrumb menu improvement

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Website#128]
Breadcrumb menu needs `text-overflow: ellipsis;`

<img width="410" alt="Screen Shot 2020-08-06 at 8 21 38 PM" src="https://user-images.githubusercontent.com/8547538/89605503-8d570700-d822-11ea-8c1a-c79c914d0fb8.png">

**Comment by buckyroberts** [comment]
Updated this to hide the overflowed text, but couldn't get the ellipsis working with flex box.

<img width="441" alt="Screen Shot 2020-08-08 at 2 39 27 PM" src="https://user-images.githubusercontent.com/8547538/89720278-11c19b00-d985-11ea-99d1-df943f788bb0.png">

**Comment by guptstagram** [comment]
It can be done by putting strings into some tags.

**Comment by guptstagram** [comment]
Can I take it?

**Comment by leelatanniru** [comment]
@guptstagram are you working on this?

**Comment by guptstagram** [comment]
Yes, @leelatanniru I have pushed the code.
