### ISSUE TITLE
New Contributor

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Website#1281]
Team: Community

{
  "title": Technical Writer,
  "isLead": false,
  "payPerDay": 2800,
  "createdDate": "2020-07-08T02:14:59.307535Z",
  "contributor": {
    "contributorId": [CONTRIBUTOR ID],
    "displayName": Vyz,
    "githubUsername": led76marx,
    "profileImage": https://avatars.githubusercontent.com/u/20023713?v=4,
    "slackUsername": Vyz
  }
}

**Comment by dhakal0kushal** [comment]
#1285
My Account Number
22d0f0047b572a6acb6615f7aae646b0b96ddc58bfd54ed2775f885baeba3d6a
