### ISSUE TITLE
Add YouTube videos to website

### ISSUE THREAD

**Issue by SteveHedden** [thenewboston-developers/Website#1282]
Here are the designs for the playlists tab on the website: 
https://www.figma.com/file/tfm2m2vGTdaZT8u5iQZS3B/Youtube-Playlists?node-id=631%3A0

- [ ] The user should be able to navigate to the page by selecting Tutorials under the Get Started menu on the homepage.
- [ ] The user should be able to watch videos on the TNB website. We are going to embed the YouTube videos directly onto the website. 
- [ ] The videos should be separated into categories -- the categories are listed on the left-hand tab. 
- [ ] The user should be able to select the playlist they want to watch by scrolling through existing playlists.
- [ ] The videos should be default sorted by date published (newest to oldest) 
- [ ] In tablet & mobile designs, put the side menu as a dropdown below the top nav.
- [ ] In tablet & mobile designs, make sure playlists wrap.
- [ ] In tablet & mobile designs, make sure playlist stacks under main video. 

## Blockers
Video API - https://github.com/thenewboston-developers/Website-API/pull/46

**Comment by maskeynihal** [comment]
@angle943 @thesanjeevsharma Is this being worked on?

**Comment by thesanjeevsharma** [comment]
@maskeynihal Yeah, I am working on it!

**Comment by maskeynihal** [comment]
@thesanjeevsharma Great. Wanted to know if I can work on it if nobody was on it. 
No worries. Good luck !!

**Comment by ma2b0043** [comment]
@buckyroberts this was closed on feb 19.
