### ISSUE TITLE
Add link to blog on website

### ISSUE THREAD

**Issue by kristykjlee** [thenewboston-developers/Website#1283]
- [ ] Add links to the blog (https://thenewboston.blog/) on both the top and bottom nav bars on the website. One under the 
the More menu and one in the footer. 

https://www.figma.com/file/UbsJyxNB7ruowSqjpx43pP/Blogs?node-id=0%3A1

**Comment by jamessspanggg** [comment]
hi @kristykjlee do you have the name or link of the icon used for the Blog in the top nav?
