### ISSUE TITLE
Add governance documentation to website

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Website#1289]
Add governance docs to website up to page 9 (Budgets). The pages after that (Rates & Amounts, Engineering Tasks, and Wireframes) are just notes for engineering and design.

**Docs** - https://docs.google.com/document/d/1GcGg-uWijwD4A2boSPPFFh5Ras0UMk7syiyZB4l_bLk/edit?usp=sharing
**Image files** - [Governance Graphics.zip](https://github.com/thenewboston-developers/Website/files/5978707/Governance.Graphics.zip)

**Comment by gsonly** [comment]
Can I work on this one? 
If yes which file I need to add the docs?

**Comment by buckyroberts** [comment]
@gsonly yep!

**Comment by gsonly** [comment]
Which file I need to add the docs?

**Comment by gsonly** [comment]
Graphic for **usernames & votes** sections is missing
