### ISSUE TITLE
Remove team member from Teams Page

### ISSUE THREAD

**Issue by kristykjlee** [thenewboston-developers/Website#1297]
- [ ] Remove David Yap from Design Team 
- [ ] Remove Ijeoma from Marketing Team
- [ ] Remove Chibuzor from Marketing Team
- [ ] Remove Martyn from New User Operation team

**Comment by maskeynihal** [comment]
Could not find: Mar Nina from Marketing Team

**Comment by amarjeet987** [comment]
> Could not find: Mar Nina from Marketing Team

Mar Nina sounds similar to Mr9tynine from the teams page, but not sure. @kristykjlee can you verify?

**Comment by maskeynihal** [comment]
Waiting for @kristykjlee to verify.
