### ISSUE TITLE
Leaderboard completed tasks alignment issue

### ISSUE THREAD

**Issue by jamessspanggg** [thenewboston-developers/Website#1299]
**Bug Description**
With the addition of the open in a new window icon, the leaderboard page shows completed tasks that are not aligned properly.

**Steps to Reproduce**
1. Go to website
2. Click on leaderboard
3. Scroll down to view for tasks
4. See that the completed tasks are not aligned properly

**Expected behavior**
Each completed tasks should be aligned in the same line.

**Actual behavior**
The task name is shifted slightly lower than the others.

**Screenshots/Recordings**
<img width="555" alt="Screenshot 2021-02-16 at 8 46 22 PM" src="https://user-images.githubusercontent.com/32864116/108064789-200d1400-7098-11eb-8345-e94f3c77c4e4.png">

**OS and Browser**
 - OS: Mac, Chrome

**Additional context**
N.A.

**Account Number**
Your account number where the reward coins for this bug bounty will be sent (pending review and approval).

[How to Create an Account](https://thenewboston.com/account-manager/create-an-account)

**Comment by jamessspanggg** [comment]
Caused by https://github.com/thenewboston-developers/Website/pull/1286 

CC @angle943

**Comment by angle943** [comment]
maybe we should explicitely set the height of each row. I'll let whoever decides to tackle this figure that one out
