### ISSUE TITLE
[Suggestions] Updates on TableBorderGrid and TableVertical of Table component

### ISSUE THREAD

**Issue by led76marx** [thenewboston-developers/Website#1313]
1. I recommend adding a property for a table's header (== 1st row different colored or bold than the rest). Something like markdown's table + different background color and text color would do I think:

| Col1  | Col2, and so on|
|-------|------------------|
| cell1 | cell2                  |

2. Also. I think TableVertical allows second column to be too narrow in mobile view for narrow screens. Not sure if there can be some min width value there. I haven;t noticed the same in TableBorderGrid (I see a horizontal scrollbar).

**Comment by amarjeet987** [comment]
Can you put up screenshots/recordings of the issue you noticed? Easier that way.

**Comment by led76marx** [comment]
Sure. Here is Introduction Guide on my old-ish mobile
![1](https://user-images.githubusercontent.com/20023713/108484289-89378780-7250-11eb-8e26-ea08648d3d5b.jpg)

**Comment by angle943** [comment]
putting a `Not Ready` for now, but we will definately revisit this in the near future

**Comment by hydra91** [comment]
@wakawakathedev 
1- done
2- need to be fixed
