### ISSUE TITLE
spelling error

### ISSUE THREAD

**Issue by Musabii** [thenewboston-developers/Website#1318]
**Bug Description**
there is a spelling error in the accounts guide of the website.

**Steps to Reproduce**
1. Go to 'https://thenewboston.com/guide/accounts'
2. search for 'an d'

**Expected behavior**
it should be written as 'and''.

**Actual behavior**
it is written as 'an d'.

**Screenshots/Recordings**

**OS and Browser**
 - OS: Ubuntu 18.04
 - Browser: Chrome
 
**Account Number**
40e778329f4d75ced4ea412f7acd0634b2c44d355bf2d479a054c9b5a44b5432

**Comment by bojan-ilijevski** [comment]
I'll do it

**Comment by angle943** [comment]
closing due to us doing an editorial pass on this page: https://github.com/thenewboston-developers/Website/pull/1293
