### ISSUE TITLE
Front End Developer (thenewboston blog)

### ISSUE THREAD

**Issue by iamsid47** [thenewboston-developers/Website#1330]
Add the following job opening to the website.

***

#### Job Title
Front End Developer

#### Job Description
As a front-end developer, your key contributions will be setting up the layout for the blog, removing bugs, integrating services like Google Analytics, Facebook Pixel, managing the metadata of the website, etc.

#### Responsibilities
- Developing the front-end of the website
- Managing the blog and clearing bugs
- Posting blogs on a timely basis (Weekly)
- Changing the blog layout if needed
- The code should not be copy-pasted
- Quality of code shall be high so that reduction in size is possible which will perhaps lead to faster load times.

#### Technology Requirements
- Experience in Reactjs
- Proven Expertise in SASS
- Shall be well acquainted with jQuery
- Knowledge regarding back-end development is preferred
- Optional: Experience in Server-side Rendering

#### Reports To
- First Name: Siddhesh
- Slack Name: Siddhesh Kulthe

#### Pay
- 2,800 coins/day

#### Application channels
- Slack - Message Siddhesh Kulthe or leave a message in the #intros channel.

**Comment by dhakal0kushal** [comment]
#1331
