### ISSUE TITLE
UNIT TESTS - components/GoToTop

### ISSUE THREAD

**Issue by angle943** [thenewboston-developers/Website#1356]
## What

Create unit tests using [Jest](https://jestjs.io/en/) and [React Testing Library](https://testing-library.com/docs/react-testing-library/intro/).

Here are a couple examples of how unit tests should be created:

1. [Unit tests for our A component](https://github.com/thenewboston-developers/Website/blob/development/src/components/A/A.test.tsx)
2. [Unit tests for Icon component](https://github.com/thenewboston-developers/ui-js/blob/master/src/components/Icon/Icon.test.tsx)
3. [Unit tests for Button component](https://github.com/thenewboston-developers/ui-js/blob/master/src/components/Inputs/Button/Button.test.tsx)

## General Acceptance Criteria for writing Unit tests

1. Should create a `[nameOfComponent].test.tsx` within the same directory of the component.
2. Should have tests that tests every `prop` of the component.
3. If there are any conditional logic within the component, there should be unit tests that accounts for each conditional branches.
4. `npm run test` should be passing.

## Specific Acceptance Criteria

**Comment by jamessspanggg** [comment]
Since scrolling is involved for this component, I think this can only be tested in real browser i.e. Cypress.

Reference: https://github.com/testing-library/react-testing-library/issues/671

**Comment by angle943** [comment]
good callout @jamessspanggg . There might be some things we can unit test, but I'll take this on. For now i'll put a `not ready`
