### ISSUE TITLE
Add og meta tags to PageTitle component

### ISSUE THREAD

**Issue by jamessspanggg** [thenewboston-developers/Website#1447]
Would be good if there are `og` meta tags for our website. This will make the shared urls to thenewboston website look much better.

How it looks currently when sharing thenewboston website on facebook:

<img width="502" alt="Screen Shot 2021-03-02 at 10 11 20 PM" src="https://user-images.githubusercontent.com/32864116/109660787-39d44e00-7ba4-11eb-8694-0cf1d5baab74.png">

More info: https://css-tricks.com/essential-meta-tags-social-media/

**Comment by jamessspanggg** [comment]
@angle943 @thesanjeevsharma what do u guys think?

**Comment by thesanjeevsharma** [comment]
Yes, this is a good idea. 👍

**Comment by angle943** [comment]
yeah definately a good idea. I think the design team's busy with a whole slew of new features we have coming though. @jamessspanggg can you just put the TNB logo and some basic description?
