### ISSUE TITLE
New Contributor

### ISSUE THREAD

**Issue by angle943** [thenewboston-developers/Website#1457]
Team: Javascript SDK

{
  "title": "Head of Javascript SDK",
  "isLead": true,
  "payPerDay": 2800,
  "createdDate": "2021-03-03T02:14:59.307535Z",
  "contributor": {
    "contributorId": [CONTRIBUTOR ID],
    "displayName": Zino Adidi,
    "githubUsername": zinoadidi,
    "profileImage": https://avatars.githubusercontent.com/u/30411401?v=4,
    "slackUsername": Zino Adidi
  }
}

**Comment by aayushi14** [comment]
Should I update constants/teams and types/teams to add Javascript-SDK team?

**Comment by aayushi14** [comment]
Added.
