### ISSUE TITLE
Better UX for forms

### ISSUE THREAD

**Issue by jamessspanggg** [thenewboston-developers/Website#1464]
- Show loading icon when users are submitting the forms.
- Show disabled button if the inputs are invalid.

c54c04774efaae20746fd3f29cdd619fea512e119bc1082b863572b2e8844104

**Comment by jamessspanggg** [comment]
@angle943 @thesanjeevsharma  thoughts on this?

**Comment by angle943** [comment]
@jamessspanggg I just tried pressing enter, and i was able to submit the form. What browser are you using?

We should definately make the form submittable via `enter` for all users. Lets pinpoint why you are having this issue in your environment first

**Comment by jamessspanggg** [comment]
> @jamessspanggg I just tried pressing enter, and i was able to submit the form. What browser are you using?

Oh shoot i retried it and it works for me now. I experienced around a 2 second delay before being able to login, so I thought entering does not submit haha, my bad.

On this note, would it be better to show a loading icon while the form is submitting? Also, should be only enable the `SignIn` button when the inputs are all valid?
