### ISSUE TITLE
New Contributor

### ISSUE THREAD

**Issue by angle943** [thenewboston-developers/Website#1468]
Team: JavaScript SDK

{
  "title": Javascript Developer,
  "isLead": false,
  "payPerDay": 2800,
  "createdDate": "2021-03-05T02:14:59.307535Z",
  "contributor": {
    "contributorId": [CONTRIBUTOR ID],
    "displayName": Mieszko,
    "githubUsername": kycermann,
    "profileImage": https://avatars.githubusercontent.com/u/59399685?v=4,
    "slackUsername": Mieszko
  }
}

**Comment by angle943** [comment]
please pay @bojan-ilijevski for this issue

**Comment by thesanjeevsharma** [comment]
@odetolataiwo tagging you ^
