### ISSUE TITLE
Feat: Add ability to edit the Github link assosciated with an user profile

### ISSUE THREAD

**Issue by avinashupadhya99** [thenewboston-developers/Website#1473]
**Bug Description**
The GitHub link on an user's profile redirects to https://github.com. Users should be able to add this just like their Account number, Slack name and display name

**Steps to Reproduce**
1. Go to https://thenewboston.com/
2. Sign in with a verified account
3. On the users profile page, notice the GitHub link

**Expected behavior**
A field for adding GitHub profile in th edit modal.

**Actual behavior**
No field for GitHub profile. It is hard coded to https://github.com

**Screenshots/Recordings**

![tnb](https://user-images.githubusercontent.com/52544819/110220835-56e38680-7eee-11eb-8d46-81b49e6d85a2.png)
![tnb_edit](https://user-images.githubusercontent.com/52544819/110220833-5519c300-7eee-11eb-883d-3fd14839e05c.png)

**OS and Browser**
 - OS: Windows 10
 - Browser: Chrome

**Additional context**
N/A

**Account Number**
94cf53921e9c5ddf48dc5589b7cdf111f7acdc93dc3073b94880416d4676b9ae

**Comment by angle943** [comment]
closing for now. I will submit an issue for this soon
