### ISSUE TITLE
Console error: validateDOMNesting

### ISSUE THREAD

**Issue by jamessspanggg** [thenewboston-developers/Website#1479]
**Bug Description**
When going through some pages in the documentation, the following console errors appear: `validateDOMNesting(...): <div> cannot appear as a descendant of <p>`.

**Steps to Reproduce**
1. Run development server and visit localhost
2. Go to documentation
3. Click on Style Guide -> React
4. View console erorrs

**Expected behavior**
No console errors should occur.

**Actual behavior**
Console errors occurred.

**Screenshots/Recordings**
<img width="724" alt="Screen Shot 2021-03-07 at 11 20 40 AM" src="https://user-images.githubusercontent.com/32864116/110227911-ec573880-7f37-11eb-93c1-942a714bb838.png">

**OS and Browser**
 - OS: MacOS Big Sur
 - Browser: Chrome

**Additional context**

**Account Number**
c54c04774efaae20746fd3f29cdd619fea512e119bc1082b863572b2e8844104

[How to Create an Account](https://thenewboston.com/account-manager/create-an-account)

**Comment by elvisiraguha** [comment]
I'd like to take this
