### ISSUE TITLE
Administrative Assistant

### ISSUE THREAD

**Issue by kiezela** [thenewboston-developers/Website#1522]
Add the following job opening to the website.

***

#### Job Title
Administrative Assistant

#### Job Description
Provides administrative or community support through a variety of tasks related to organization and communication.

#### Responsibilities

- Provides administrative support to ensure efficient operation.

- Ensure things are accomplished.

- Carries out administrative duties such as organizing documents, answering questions and requests.

- Organize meetings in Google Calendar.

#### Skills and Qualifications

- Knowable with G Suite

- Analyzing Information

- Organization Skills

#### Reports To
- First Name: [Bucky]
- Slack Name: [Bucky]

#### Pay
- 2,800 coins/day

#### Application channels
- Slack - Message [Bucky]
- LinkedIn
- Twitter
- Reddit

**Comment by Prawesh-MAGNETIC** [comment]
I am in.
Please count on me.
Thank you!
