### ISSUE TITLE
Content Editors

### ISSUE THREAD

**Issue by kiezela** [thenewboston-developers/Website#1525]
Add the following job opening to the website.

***

#### Job Title
Content Editors

#### Job Description
A detail-oriented content editor who can deliver quality content and help devise traffic and profit generating content strategies for the community.

#### Responsibilities

- Responsible for all aspects of content, which includes development, design, production, presentation, evaluation, analysis, etc.

- Use data and feedback from users to help evaluate and enhance the value of a set of written materials and websites.

#### Skills and Qualifications

- Excellent command of the English language

- Writing, copy editing, and proofreading experience

- Good communication and interpersonal skills

- Highly organized and detail-oriented

- Proficient in desktop publishing software

- Proficient in Microsoft Office and Social Media platforms

#### Reports To
- First Name: [Kristy]
- Slack Name: [Kristy]

#### Pay
- 2,800 coins/day

#### Application channels
- Slack - Message [Kristy]
- LinkedIn
- Twitter
- Reddit

**Comment by Prawesh-MAGNETIC** [comment]
I am interested

**Comment by jamessspanggg** [comment]
Hi @Prawesh-MAGNETIC, are u interested in the job or solving this issue? If prior, you can contact @kristykjlee in our [slack](https://join.slack.com/t/thenewboston/shared_invite/zt-lldpqdle-l9lvBI7PbZD_uDJegmk3xA) or [discord](https://discord.gg/thenewboston) channel. If the latter, just make a PR and ping me to review it!

**Comment by Tatenda** [comment]
You can assign me to this

**Comment by Tatenda** [comment]
@jamessspanggg
