### ISSUE TITLE
Localization Manager

### ISSUE THREAD

**Issue by kiezela** [thenewboston-developers/Website#1526]
Add the following job opening to the website.

***

#### Job Title
Localization Manager

#### Job Description
Ensure translation and localization project tasks are managed to high standards and guarantee that a product is ready for a near simultaneous global launch.

#### Responsibilities

- Keep an eye for organization and precision. 

- Communicate the promotional message to a series of external teams. 

- Excellent communication skills needed. Comprehension of one or more languages is preferrable. 

#### Skills and Qualifications

- Knowledge in Foreign Languages for future purposes (Spanish, Chinese, Russian, and Japanese) 

#### Reports To
- First Name: [Justin]
- Slack Name: [Justin]

#### Pay
- 2,800 coins/day

#### Application channels
- Slack - Message [Justin]
- LinkedIn
- Twitter
- Reddit

**Comment by Tatenda** [comment]
You can assign me to this

**Comment by Tatenda** [comment]
@jamessspanggg

**Comment by angle943** [comment]
paid
