### ISSUE TITLE
Community Engagement Specialist

### ISSUE THREAD

**Issue by kiezela** [thenewboston-developers/Website#1527]
Add the following job opening to the website.

***

#### Job Title
Community Engagement Specialist

#### Job Description
Responsible for building awareness about the project such as coordinating and supporting targeted engagements and outreach that supports public participation and partnership-building efforts for the community. Facilitate projects to promote cohesion and participation at the grassroots level.

#### Responsibilities

- Provide leadership and strategic vision to activities promoting community engagement in municipal governance.

- Strengthen capacity of team members to engage with community, include them in participatory planning processes, and incorporate their priorities into planning documents.

- Facilitate citizen participation in collaborative decision making, management, and monitoring.

- Promote productive interactions between communities that facilitate upward flow of information on community needs and priorities.

- Contribute to work plans, donor reports, success stories, and other deliverables.

#### Skills and Qualifications

- Strong interpersonal and written communication skills.

- Proven ability to engage women, youth, and other marginalized populations in community development activities.

#### Reports To
- First Name: [Chrisha]
- Slack Name: [Chrisha]

#### Pay
- 2,800 coins/day

#### Application channels
- Slack - Message [Chrisha]
- LinkedIn
- Twitter
- Reddit

**Comment by Tatenda** [comment]
You can assign me to this

**Comment by Tatenda** [comment]
@jamessspanggg

**Comment by angle943** [comment]
paid
