### ISSUE TITLE
UX Designer & Researcher

### ISSUE THREAD

**Issue by kiezela** [thenewboston-developers/Website#1528]
Add the following job opening to the website.

***

#### Job Title
UX Designer & Researcher

#### Job Description
Responsible for researching, categorizing, and documenting user behavior by employing design methodologies, facilitating internal & external discussions, and visualizing concepts. Ensure design concepts are fully realized by working closely with software developer teams and collaborating with other designers to arrive at the best design solution.

#### Responsibilities

- Conduct competitor analysis, customer analysis and user research.

- Attend to product structure and strategy, as well as content development.

- Develop user flows, prototypes and wireframes.

- Coordination with other designers and developers.

- Conduct user testing and analysis.

- Continuously iterate on solutions to make the product increasingly effective and delightful for users.

#### Skills and Qualifications

- Collaboration and communication

- Critical thinking and problem-solving skills

- Familiarity with user research and analysis technique

- Wireframing and prototyping

- Understanding of information architecture

- User and usability testing

- Successful completion of UX/UI course work or training portfolio

- Proven experience at a professional level

#### Reports To
- First Name: [Kristy]
- Slack Name: [Kristy]

#### Pay
- 2,800 coins/day

#### Application channels
- Slack - Message [Kristy]
- LinkedIn
- Twitter
- Reddit

**Comment by Tatenda** [comment]
I'm working on this

**Comment by Tatenda** [comment]
@jamessspanggg

**Comment by angle943** [comment]
paid
