### ISSUE TITLE
Profile shows internal link but showing the new window icon

### ISSUE THREAD

**Issue by jamessspanggg** [thenewboston-developers/Website#1541]
<img width="332" alt="Screen Shot 2021-03-12 at 11 19 20 PM" src="https://user-images.githubusercontent.com/32864116/110962558-13749680-838c-11eb-8c5f-a99bb5371bd1.png">

The `front end developers` link at the profile page is internal and shouldn't have the new window icon

**Comment by PrinceRajRoy** [comment]
@jamessspanggg are the profile details except Name & AN, not suppose to be shown for non team members?

**Comment by jamessspanggg** [comment]
> @jamessspanggg are the profile details except Name & AN, not suppose to be shown for non team members?

Yeah it wouldn't show if it's non team members
