### ISSUE TITLE
Document the history of TNBC

### ISSUE THREAD

**Issue by hussu010** [thenewboston-developers/Website#1543]
This doc will contain everything from when TNBC was started, how it all began, whose idea, the first set of people involved and so on, which later can be featured on the website and social media as well.

**Comment by tomijaga** [comment]
This could be a good start for the document  
https://drive.google.com/file/d/1mO1x9Ja0o1_KSMU9xL7T9lRynEMLMlom/view

- Author : **Josh Adewale**
