### ISSUE TITLE
Separate skills required from technology requirements

### ISSUE THREAD

**Issue by Tatenda** [thenewboston-developers/Website#1551]
**Bug Description**
When adding a job opening, there is only provision to add technology requirements thus some jobs that do not have tech requirements but instead skills requirements end up having skills listed under tech requirements

**Steps to Reproduce**
1. Go to 'https://thenewboston.com/openings/All'
2. Click on 'any listed job openning'
3. Scroll down to 'Technology requirements'

**Expected behavior**
I expected to see Skills requirements separate from Technology requirements

**Actual behavior**
Tech and skills requirements mixed

**Additional context**
Some job postings do not have technology requirements

**Account Number**
272978bf3770b403ddd520e2b4cf64a700e1ca87e12e5505337dd67a9aeb8a9f

[How to Create an Account](https://thenewboston.com/account-manager/create-an-account)

**Comment by Lalisfeed** [comment]
this is related to #1960 and is fixed by #1964

technology requirements is now requirements, so skills can be considered into it

**Comment by wakawakathedev** [comment]
Closing this issue -
