### ISSUE TITLE
Add feature request in Issue template

### ISSUE THREAD

**Issue by avinashupadhya99** [thenewboston-developers/Website#1572]
**Bug Description**
Not really a bug, a feature request section in the issue templates would be great

[How to Create an Account](https://thenewboston.com/account-manager/create-an-account)

**Comment by angle943** [comment]
@avinashupadhya99 what is your account number?

**Comment by avinashupadhya99** [comment]
@angle943 , it's `94cf53921e9c5ddf48dc5589b7cdf111f7acdc93dc3073b94880416d4676b9ae`
