### ISSUE TITLE
Add back the Senior Python Developer job

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Website#1601]
This job - https://github.com/thenewboston-developers/Website/blob/development/src/data/openings.json#L3

We can remove the `2,800 coins/day` and also update the contact information where instead of redirecting them to a social media account we will link them a the new Google Form application link which is being worked on right now by @ma2b0043 and @Chrisha1212.

**Blocked by:**
- https://github.com/thenewboston-developers/Management/issues/112

**Comment by ma2b0043** [comment]
Will try to complete, this task:

- https://github.com/thenewboston-developers/Management/issues/112

as soon as possible.
