### ISSUE TITLE
Scrap leaderboards

### ISSUE THREAD

**Issue by angle943** [thenewboston-developers/Website#1602]
we are going to get rid of leaderboards page: https://thenewboston.com/leaderboard/All

remove all components related to it, all util functions related to it (if any), the routes, from header, footer, etc. Erase the associated data files too

**Comment by thesanjeevsharma** [comment]
![OWAwyXG](https://user-images.githubusercontent.com/29539278/112418039-be9f2b80-8d4e-11eb-9ba4-993ac7239eb1.gif)

**Comment by dhakal0kushal** [comment]
@mrbusysky @mrbusysky @mrbusysky where are you?

**Comment by angle943** [comment]
We will have an updated version of Leaderboards later :)
