### ISSUE TITLE
Update opening page of the website as per the new design

### ISSUE THREAD

**Issue by ma2b0043** [thenewboston-developers/Website#1617]
@angle943  need to update the following page:

https://thenewboston.com/openings/All

according to the following design prepared by kristy:
https://www.figma.com/file/ChyT88EmP2Rmzx35I9erCL/Marketing-Site?node-id=577%3A1182

When a user clicks "apply" he/she will be redirected to a google form, which has been made for thenewboston's recruitment. You can access "thenewboston recruitment" google form, from the following path, in thenewboston's drive:

Community Process > Recruitment Drive > thenewboston recruitment
https://drive.google.com/drive/folders/1Bni6GU_Vepd3A_57_X4ywm3mtoqa_Etf?usp=sharing

If you need any help, feel free to ask me anytime.

**Comment by jamessspanggg** [comment]
let me take this
