### ISSUE TITLE
Documentation Bug

### ISSUE THREAD

**Issue by Rajputusman** [thenewboston-developers/Website#1628]
**Bug Description**
Redirecting to Confirmation Services Page under Guide category. But there is no Confirmation Service Page under the Guide category.

**Steps to Reproduce**
1. Go to 'https://thenewboston.com/bank-api/validator-confirmation-services'
2. Hover over 'Confirmation Services'
3. See link https://thenewboston.com/guide/confirmation-services

**Expected behavior**
I think there is no need to redirect to the current page. So can wrap it in **Strong** tag.

**Actual behavior**
Going to Guide Overview page(in search of Confirmation Service).

**Screenshots/Recordings**
![image](https://user-images.githubusercontent.com/65516140/112775734-30c98600-9057-11eb-89ee-2362551fa3b0.png)

**OS and Browser**
 - OS: Windows 10
 - Browser: Chrome

**Comment by angle943** [comment]
This is a valid bug. Lets get rid of the whole sentence: '`More information about the confirmation process can be found in the Confirmation Services section of the guide.`
