### ISSUE TITLE
Max supply needs to be changed in FAQ

### ISSUE THREAD

**Issue by jamessspanggg** [thenewboston-developers/Website#1651]
https://www.thenewboston.com/faq#is-there-a-max-supply

<img width="275" alt="Screen Shot 2021-03-31 at 10 44 44 PM" src="https://user-images.githubusercontent.com/32864116/113163414-bc6b2e80-9272-11eb-8251-ccf123f7a4e3.png">

**Comment by tomijaga** [comment]
It's 2,032,628,357 now.
