### ISSUE TITLE
Projects hifi

### ISSUE THREAD

**Issue by kristykjlee** [thenewboston-developers/Website#1682]
@angle943 is going to break down tickets to hand off to FE team
https://www.figma.com/file/HEQpY7l2jvazLp1kqyyUiH/Projects-Page?node-id=0%3A1

Subtasks
- [ ] Integrate with API
- [ ] Create projects landing page 
- [ ] Create project details page structure
- [ ] Add project details scrolling behaviour

**Comment by angle943** [comment]
BE: https://github.com/thenewboston-developers/Website-API/pull/82

**Comment by jamessspanggg** [comment]
@angle943 with this, then are we scraping off the existing projects page?

<img width="1343" alt="Screen Shot 2021-04-22 at 9 13 49 PM" src="https://user-images.githubusercontent.com/32864116/115720426-a5ba8200-a3af-11eb-9bef-0aebaecf0003.png">
