### ISSUE TITLE
Add meeting notes template link to website

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Website#1691]
Add a "Meeting Notes Template" link to the resources page https://thenewboston.com/teams/All/Resources on the website.

Link - https://docs.google.com/document/d/15P7MPPGgC2O3ZhOWryOeuW1K5EO9TL8_TBWR4Z2-_eo/edit?usp=sharing

**Comment by angle943** [comment]
@thesanjeevsharma @jamessspanggg could one of you guys look into this?
