### ISSUE TITLE
Text alignment

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Website#1693]
Menu items are slightly misaligned.

<img width="353" alt="Screen Shot 2021-04-11 at 3 08 12 PM" src="https://user-images.githubusercontent.com/8547538/114322938-cba27580-9ad7-11eb-8d5b-7a4389eaec09.png">

**Comment by angle943** [comment]
@jamessspanggg @thesanjeevsharma can one of you guys look into this?

**Comment by jamessspanggg** [comment]
Will fix it tonight
