### ISSUE TITLE
Review the project process

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Website#1695]
Review the project process guides/documentation and provide any suggestions on how we can improve it. Anything that is potentially confusing, unclear, or that can be improved please provide feedback on.

Our goal is to make this process as easy as possible for users to understand the overall process, submit a project, and get started with development.

https://thenewboston.com/projects/overview

**Comment by led76marx** [comment]
@buckyroberts on it

**Comment by led76marx** [comment]
As of 4/13:
- [x] Review Project Overview
- [x] Review Rules & Guidelines
- [ ] Review Proposal Submission Process
- [ ] Review Milestones & Payouts
