### ISSUE TITLE
Weird color in disabled button

### ISSUE THREAD

**Issue by jamessspanggg** [thenewboston-developers/Website#1699]
The color of the disabled buttons seems to be different as compared to previous

<img width="402" alt="Screen Shot 2021-04-12 at 10 32 54 PM" src="https://user-images.githubusercontent.com/32864116/114412172-6fc31400-9bdf-11eb-972c-222d3e368ea7.png">

<img width="536" alt="Screen Shot 2021-04-12 at 10 32 02 PM" src="https://user-images.githubusercontent.com/32864116/114412164-6d60ba00-9bdf-11eb-97b6-bd052d3fa066.png">

**Comment by angle943** [comment]
lets make this consistent with how it is in the accountManager
