### ISSUE TITLE
AppWide UI Update - Update Headers

### ISSUE THREAD

**Issue by angle943** [thenewboston-developers/Website#1702]
here is our new style guide: https://www.figma.com/file/6AGSvP6DJIIvy5Ayyp1a6U/Design-System?node-id=12%3A4

as you can see from that figma link, we will have standards when it comes to headers (h1,h2,h3,h4) and what they are calling `Display`.

Find an elegant way to tackle this issue app-wide. Make sure you test each page that will be effected to ensure that it will not be broken

**Comment by thesanjeevsharma** [comment]
@angle943 Figma link is not working!

**Comment by angle943** [comment]
@thesanjeevsharma i'll bring it up with kristy. thanks for bringing that to attention!

**Comment by jamessspanggg** [comment]
hi @kristykjlee do we also have a color system as well? I realised while working with the projects, some colors do not exist within the codebase.
