### ISSUE TITLE
Add Project Reviewer Job

### ISSUE THREAD

**Issue by ma2b0043** [thenewboston-developers/Website#1705]
Add the following job opening to the website.

***

#### Job Title
Project Reviewer

#### Job Description
We are looking for Project Reviewer, who will help and support Project Leads to complete their projects.

#### Qualification
- Ability to actively communicate with each team and community of thenewboston
- Detail-oriented  in scoping projects & getting good estimates
- Familiarity with blockchain & thenewboston in general

#### Responsibilities
- Actively recruit projects
- Work with the project lead and negotiate on price (milestone by milestone), milestones, objectives and make sure they are crystal clear
- - Check Project Lead's GitHub history and background to ensure they are able to tackle the project
- - Let project leads know that they will be getting paid per milestone
- - Ensure proposed milestones requires some amount of work to be done
- Submit completed projects proposals to government for review
- Review milestones as they come in / QA
- Ensure progress of the project remains on track
- Update the community on the progress of the project

---

@buckyroberts  @angle943 does this^^ job description needs any update? or is it good to go?

**Comment by angle943** [comment]
approved. I don't think we currently support indented bullet points, so if we don't, then you can work on this without the indents

**Comment by jamessspanggg** [comment]
@ma2b0043 can i check if this should be categorized under `Community` team?

**Comment by ma2b0043** [comment]
@jamessspanggg I think it will be under `engineering` because the `community` has nothing to do with this issue right now.

**Comment by ma2b0043** [comment]
@angle943 if you see this PR: https://github.com/thenewboston-developers/Website/pull/1706#pullrequestreview-634560620
we have "Responsibilities" and "Technology Requirements" instead of "Qualification" and "Responsibilities". Should we post it as it is or should we change these headings(but if we do that we'll have to change all of the headings, even previous ones according to @jamessspanggg)?

**Comment by ma2b0043** [comment]
We can close this now, as the post has been removed.
