### ISSUE TITLE
Include React Helmet

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Website#1721]
Include React Helmet to allow us to set meta descriptions on each page to improve SEO.

https://github.com/nfl/react-helmet

**Comment by jamessspanggg** [comment]
@buckyroberts we do have react helmet, check this component: https://github.com/thenewboston-developers/Website/blob/development/src/components/PageTitle/index.tsx

**Comment by buckyroberts** [comment]
Noice
