### ISSUE TITLE
Add "Terms of Service" and "Privacy Policy" on the website

### ISSUE THREAD

**Issue by ma2b0043** [thenewboston-developers/Website#1723]
You need to add the "Terms of Service" and "Privacy Policy" to the website, as per these design: https://www.figma.com/file/5bwlfJUNu6HdbWQwagKdEt/Terms-of-Use-and-Privacy-Policy?node-id=0%3A1

These will be added in the footer of the website. You can get the original doc from this issue > [146](https://github.com/thenewboston-developers/Management/issues/146). 

If you have any question, you can message me on discord or ask the question in the comments of this issue.

**Comment by jamessspanggg** [comment]
Superseded by #1913
