### ISSUE TITLE
Update wording on Team Member Payments documentation

### ISSUE THREAD

**Issue by kristykjlee** [thenewboston-developers/Website#1757]
In the Team Member Payments documentation, please update '~30 minutes' to '0.5 hours'
![Screen Shot 2021-04-24 at 2 58 14 PM](https://user-images.githubusercontent.com/68207101/115974723-7f155c00-a513-11eb-8a0a-e7c21d48eb2d.png)

**Comment by buckyroberts** [comment]
Fixed in a separate PR
