### ISSUE TITLE
Update FAQs Page

### ISSUE THREAD

**Issue by ma2b0043** [thenewboston-developers/Website#1779]
Hi, you need to update the FAQ's page; https://thenewboston.com/faq based on the following design.

Here is the Figma link:
https://www.figma.com/file/C22D4Et2I0AIE0n8QwBDMm/FAQ?node-id=152%3A3508
Here is the FAQ content link:
https://docs.google.com/document/d/12DzwJnge7LaVabgtnkIjM9fpuVp1fNS4KdVsndiU4uc/edit?usp=sharing

If you have any query in this design, kindly let me know asap. Thank you!

Note: You can add this task in whichever sprint you want to.

**Comment by jamessspanggg** [comment]
> Here is the Figma link:
https://www.figma.com/file/C22D4Et2I0AIE0n8QwBDMm/FAQ?node-id=152%3A3508

need permission to open link

**Comment by ma2b0043** [comment]
@ThaDeveloper when you are done with this issue: https://github.com/thenewboston-developers/Website-API/issues/115 kindly let me know and let the frontend guys know as well by commenting on this issue as well. Thank you

**Comment by ThaDeveloper** [comment]
@ma2b0043 This is now on [dev](https://api-dev.thenewboston.com/)
