### ISSUE TITLE
Need to Optimize the Website

### ISSUE THREAD

**Issue by ma2b0043** [thenewboston-developers/Website#1786]
Hi, hope you are doing fine. You need to optimize thenewboston's website based on the following things:

Step 1:
Goto this page: https://developers.google.com/speed/pagespeed/insights/ and then paste in: https://thenewboston.com/

Step 2:
You'll see 2 sections on the navbar, one showing the analytics for Mobile and one for PC. You can go to each section and see the "Opportunity" and "Diagnostics" section(attaching ss to make things more clear):

![Screenshot from 2021-05-10 05-34-43](https://user-images.githubusercontent.com/60430226/117592344-9aa67680-b151-11eb-993b-83c0795b2f9a.png)
![Screenshot from 2021-05-10 05-35-06](https://user-images.githubusercontent.com/60430226/117592348-a09c5780-b151-11eb-8e41-6a03ff544735.png)
![Screenshot from 2021-05-10 05-35-28](https://user-images.githubusercontent.com/60430226/117592354-a4c87500-b151-11eb-9782-9717eaa4b1ce.png)
![Screenshot from 2021-05-10 05-35-50](https://user-images.githubusercontent.com/60430226/117592362-aa25bf80-b151-11eb-99c9-7adc3269615f.png)

Step 3:
If there are some tasks requiring BE update, let me know on discord and I can reach out to Justin Ndwiga or Truyen about it.

If you need any help whatsoever, let me know about that too, on discord. Thank you!

**Comment by jamessspanggg** [comment]
@truyenhv we might need to serve the g-zipped files and might need your help in configuring in the server side.

**Comment by truyenhv** [comment]
yeah. I added this one already on cloudfront CDN but seem like it didn't work great.
<img width="1571" alt="image" src="https://user-images.githubusercontent.com/32347748/117634997-a9207c80-b1a9-11eb-91a5-7b0e4966c8d9.png">

I think we could try to use nginx to serve for frontend contents. It allow us to custom config if needed

**Comment by wakawakathedev** [comment]
This seems like an epic - (i.e. how do we measure website performance etc)
