### ISSUE TITLE
Andrey Bortnikov's name card getting spammed on team's page

### ISSUE THREAD

**Issue by manishram** [thenewboston-developers/Website#1793]
**Bug Description**
Andrey Bortnikov's name card getting spammed on team's page

**Steps to Reproduce**
1. Go to https://thenewboston.com/teams/All/Members
2. You see everything looks good.
3. Now click on **Resource** tab to the right of **Members** tab in **All** team section
4. You will see **Andrey Bortnikov** name in the resource section.
5. Now come back to **Members** tab and you will see  **Andrey Bortnikov** name is on top of member's list and goes on increasing when following the above steps few more times.

**Screenshots/Recordings**

![bug](https://user-images.githubusercontent.com/22790904/118361280-4d3e6500-b5a8-11eb-846c-c70bbc3de886.gif)

**Account Number**
0f92e975101eb96cea80dce430d74efd3172fa229377818d467ded85dcf2ab6c

**Comment by jamessspanggg** [comment]
thanks for spotting @manishram, fixing it
