### ISSUE TITLE
Website members > resources tab bug

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Website#1795]
When you visit https://thenewboston.com/teams/All/Members and then click on the "Resources" tab it displays the incorrect components (random user cards) instead of just the resources links.

<img width="1324" alt="Screen Shot 2021-05-15 at 2 39 10 PM" src="https://user-images.githubusercontent.com/8547538/118378879-7d2b3f80-b58b-11eb-8b95-7356ab9751c5.png">

**Comment by jamessspanggg** [comment]
@buckyroberts this is fixed in the latest commit, can you deploy to the website?
