### ISSUE TITLE
Incorrect sprint dates

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Website#1811]
The date range for the sprint is incorrect. Note the actual date in the top right corner.

<img width="936" alt="Screen Shot 2021-05-20 at 3 53 39 PM" src="https://user-images.githubusercontent.com/8547538/119058655-a54be180-b983-11eb-8526-6881815d9270.png">

**Comment by jamessspanggg** [comment]
hi @buckyroberts during every sprint, we will need to modify the general milestone located here: https://github.com/thenewboston-developers/Management/milestone/1

The specific things that need to be changed for that milestone:
- milestone due)date (we are obtaining the sprint date by using [due_date - 7, due_date])
- title (must be in the format of "Sprint [No]"

**Comment by jamessspanggg** [comment]
@ma2b0043 may i know who is responsible to update the general milestone?

**Comment by ma2b0043** [comment]
> @ma2b0043 may i know who is responsible to update the general milestone?

We'll each team lead is responsible for this, we'll update these in our sprint meeting from now on, I think that will work for this issue.
