### ISSUE TITLE
Add the Newsletter Page on the website

### ISSUE THREAD

**Issue by ma2b0043** [thenewboston-developers/Website#1817]
Hi, hope you are doing good. You need to add the newsletter page onto the website, as per this design:
https://www.figma.com/file/zHkdKxSOz1LzAfT0Intoyq/Newsletters?node-id=92%3A1509

The details of this project can be found here: [197](https://github.com/thenewboston-developers/Design/issues/197). If you have any questions kindly let me know, asap. Thank you!

**Comment by angle943** [comment]
This one is blocked for now. We might move over to wordpress for this
