### ISSUE TITLE
Unlisted and unmodified page on blog website

### ISSUE THREAD

**Issue by stellar1s** [thenewboston-developers/Website#1831]
**Bug Description**
There is an unmodified page on the blog from the template that while is unlisted but is not removed. Additionally, the home page has an empty dropdown (the community dropdown).

**Steps to Reproduce**
1. Go to https://thenewboston.blog/about/
2. Done

**Expected behavior**
Normal 404 page or the page gets updated with correct information and is listed as a valid page.

**Actual behavior**
Shows an unmodified page from the template the blog uses.

**Screenshots/Recordings**
There is none needed.

**OS and Browser**
 - OS: iOS 14.4.2
 - Browser: Safari

**Additional context**
None required.

**Account Number**
02c00467c5f149cb7cbd9cce382c709a3939f1f9f7e6acdc6687b34453943db0

**Comment by angle943** [comment]
We are not currently maintaining the blog website
