### ISSUE TITLE
Homepage social icons lag issue

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Website#1840]
On the new homepage there is a slight delay between hovering and the color fading animation.

<img width="590" alt="Screen Shot 2021-06-09 at 9 35 40 PM" src="https://user-images.githubusercontent.com/8547538/121466689-b11c3980-c96c-11eb-8284-06065e95d2a1.png">

**Comment by navin41** [comment]
transition delayed using opacity

**Comment by roovy54** [comment]
Hi! I will work on this issue

**Comment by roovy54** [comment]
Created a new PR [#1860](https://github.com/thenewboston-developers/Website/pull/1860)

**Comment by angle943** [comment]
PAID
