### ISSUE TITLE
Download button animation is jumpy

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Website#1841]
On mobile when the menu is opened, the download button jumps from the top to the bottom. Included images below the video incase the frame rate on the video makes it difficult to see what's going on.

https://user-images.githubusercontent.com/8547538/121468238-4fa99a00-c96f-11eb-8670-fbdb7652f10d.mp4

<img width="615" alt="Screen Shot 2021-06-09 at 10 07 49 PM" src="https://user-images.githubusercontent.com/8547538/121468372-88497380-c96f-11eb-8e2d-c51e8f3936c9.png">

<img width="615" alt="Screen Shot 2021-06-09 at 10 07 55 PM" src="https://user-images.githubusercontent.com/8547538/121468368-87184680-c96f-11eb-8f9a-557276a0a331.png">

**Comment by AndreasMaita** [comment]
@buckyroberts What is the desired behavior? Should the button just appear, or should it continue to scroll down but without the little stop?
