### ISSUE TITLE
z-index logo link issue

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Website#1842]
On the FAQ page, on certain screen widths there is a card that appears over the logo that is hidden. So when I go to click the logo it doesn't take me to the homepage since I am clicking the invisible card.

<img width="592" alt="Screen Shot 2021-06-09 at 10 13 37 PM" src="https://user-images.githubusercontent.com/8547538/121468771-335a2d00-c970-11eb-897f-49acd7f98d59.png">

<img width="543" alt="Screen Shot 2021-06-09 at 10 13 55 PM" src="https://user-images.githubusercontent.com/8547538/121468773-33f2c380-c970-11eb-9683-315b6a6a499e.png">

**Comment by jamessspanggg** [comment]
@buckyroberts are you sure that its the FAQ page? the `GetStartedCard` is in the home page, which make sense since clicking on a link to the home page when you are already at the home page wont do anything...

**Comment by rootleet** [comment]
Assign this to me please
