### ISSUE TITLE
Replace all instances of "Account Manager" with "Wallet"

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Website#1843]
Since we are rebranding the "Account Manager" to "Wallet" we can replace all instances on the website. For example:

<img width="1427" alt="Screen Shot 2021-06-09 at 10 12 56 PM" src="https://user-images.githubusercontent.com/8547538/121468879-5edd1780-c970-11eb-990e-144eee5d3235.png">

**Comment by avinashupadhya99** [comment]
Hi, I will be working on this if it is alright. Thanks :)

**Comment by hussu010** [comment]
Requesting the bounty to be increased since it's a lot of work for 250 TNBC.

**Comment by angle943** [comment]
PAID
