### ISSUE TITLE
FAQ Question Link toggle issue

### ISSUE THREAD

**Issue by hemanth-kotagiri** [thenewboston-developers/Website#1848]
**Bug Description**
Clicking on any of the FAQ questions for the second time doesn't toggle off the answer dropdown.
This happens in both the FAQ page as well as those that are in the Home page.

**Steps to Reproduce**
1. Go to FAQ Section
2. Click on any of the questions and see that the answer drop-down is toggled.
3. Click the question again.
4. The answer drop-down is not toggled off.

**Expected behavior**
When we click the question for the second time, the user expects to toggle off the answer dropdown.

**Actual behavior**
When we click the question for the second time, the answer drop-down is not toggled off - rather, the answer is still displayed.

**OS and Browser**
 - OS: Arch Linux
 - Browser: Brave

**Comment by hemanth-kotagiri** [comment]
I would like to work on this.

**Comment by hussu010** [comment]
@hemanth-kotagiri feel free to make a PR and link this issue.

**Comment by hemanth-kotagiri** [comment]
@hussu010 Awesome. I am fixing some dependency issues at my end. I will link the PR ASAP.

**Comment by jamessspanggg** [comment]
hi @hemanth-kotagiri please only work on the PR when the `Not Ready` tag is removed and the bug is confirmed. @kashikushi would this UX addition be fine with you?

**Comment by hemanth-kotagiri** [comment]
@jamessspanggg, the same PR also fixes another issue that I saw in the morning today. Here are the steps to reproduce it:
1. Go to FAQ Page and click on any of the questions.
2. See that the answer drop-down is toggled. 
3. After that, click on the drop-down icon to the right to toggle off the answer.
4. Now, click on the question again - now it doesn't toggle the answer because the `toggleExpanded` is set to false and when you click on the link, it doesn't change its state. And that's exactly what I have added in the PR.

I hope you've got what I am talking about here. If not, lemme know, I will do my best to be more concise.

**Comment by angle943** [comment]
@hemanth-kotagiri what is your account number?

**Comment by hemanth-kotagiri** [comment]
@angle943 here you go: 5468b09948f1be8034e043fffcc7a9ac915957b0877eed0eda7e88c3c3631351

**Comment by angle943** [comment]
Paid for both bug found & completed
