### ISSUE TITLE
Tablet issues

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Website#1859]
On tablet (screenshot from iPad) the top nav dropdown menus do not open when they are tapped. Also, the right hamburger menu icon is not visible on the screen.

![B8AD5621-3C4F-46A4-AE92-157EBD5B806F](https://user-images.githubusercontent.com/8547538/121791169-d6db5580-cb9b-11eb-9ab8-d14a31692cb2.png)

**Comment by angle943** [comment]
fixed by this: #1872
