### ISSUE TITLE
TNB Forum github link is broken

### ISSUE THREAD

**Issue by arjunraghurama** [thenewboston-developers/Website#1861]
**Bug Description**
When clicked on github link, getting 404 error 

Here is the project page URL
https://thenewboston.com/projects/d7df9c1c-50c9-4d4c-8ba7-27eff38559ee

**Steps to Reproduce**
1. Go to 'https://thenewboston.com/projects/d7df9c1c-50c9-4d4c-8ba7-27eff38559ee'
2. Click on 'TNB Forum' github link
3. Redirects to Github

**Expected behavior**
Link should be pointing to a valid github repo

**Actual behavior**
Link is pointing to unknown github repo

**Screenshots/Recordings**

**OS and Browser**
 - OS: [Windows 10]
 - Browser [Chrome]

**Additional context**

**Account Number**
Your account number where the reward coins for this bug bounty will be sent (pending review and approval).

[How to Create an Account](https://thenewboston.com/wallet/create-an-account)

**Comment by jamessspanggg** [comment]
@avinashupadhya99 can you provide the correct link to your repo?

**Comment by avinashupadhya99** [comment]
I have used Discourse to set it up. Technically there's no code changes to the original Discourse source code yet. Here's the forked version - https://github.com/avinashupadhya99/discourse

**Comment by angle943** [comment]
I don't think we should provide a link to a forked version of an app on the website :/
