### ISSUE TITLE
Navbar overflow for whole mobile view

### ISSUE THREAD

**Issue by hussu010** [thenewboston-developers/Website#1862]
**Bug Description**
There's the overflow of the navbar in mobile view of the whole site.

**Steps to Reproduce**
1. Go to thenewboston.com on mobile view.
2. Scroll horizontally.

**Expected behavior**
There should be no x-scroll on the mobile view.

**Actual behavior**
x-scroll on the whole site.

**Screenshots/Recordings**

**OS and Browser**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari]

**Additional context**

**Account Number**
Your account number where the reward coins for this bug bounty will be sent (pending review and approval).

[How to Create an Account](https://thenewboston.com/wallet/create-an-account)

**Comment by jamessspanggg** [comment]
Overlap with #1859
