### ISSUE TITLE
Loading spinner for download page is not in center

### ISSUE THREAD

**Issue by avinashupadhya99** [thenewboston-developers/Website#1863]
**Bug Description**

The page loading spinner for the download page is not in the center, it is the top left instead.

**Steps to Reproduce**
1. Go to https://www.thenewboston.com/download
2. The spinner will appear in the top left

**Expected behavior**
The spinner should be in the center from top and left.

**Actual behavior**
The spinner is in the top left corner.

**Screenshots/Recordings**
![image](https://user-images.githubusercontent.com/52544819/121907103-5fe3bf80-cd49-11eb-8759-a344b9d942b5.png)

**OS and Browser**
 - Windows 10
 - Chrome

**Additional context**
N/A

**Account Number**
`94cf53921e9c5ddf48dc5589b7cdf111f7acdc93dc3073b94880416d4676b9ae`

[How to Create an Account](https://thenewboston.com/wallet/create-an-account)

**Comment by avinashupadhya99** [comment]
Hi, I will be working on this

**Comment by avinashupadhya99** [comment]
Should the Loader be in the center for all containers or just the download container?

**Comment by angle943** [comment]
PAID for both bug bounty and the work done
