### ISSUE TITLE
Uneven spacing from left and right in Hero section of homepage

### ISSUE THREAD

**Issue by Niekon01** [thenewboston-developers/Website#1866]
**Bug Description**
Uneven spacing from left and right in Hero section of the homepage

**Steps to Reproduce**
1. Go to Homepage and check the spacing from left and right in the hero section

**Expected behavior**
Spacing from both edges should be the same

**Actual behavior**
The SVG illustration is having more space from right

**Screenshots/Recordings**
![Group 1](https://user-images.githubusercontent.com/55133485/122045001-ca086d00-cdfa-11eb-92e3-fa679351b90b.png)

**OS and Browser**
 - OS: All
 - Browser: All

**Account Number**
18c07b4227cb0993fa7a1db834834e42461a0d9f61b2b157dfbfee625bbf3de6

[How to Create an Account](https://thenewboston.com/wallet/create-an-account)

**Comment by angle943** [comment]
I don't see it in my browser :/ Feel free to reopen if you still see it
