### ISSUE TITLE
Small update to the projects page

### ISSUE THREAD

**Issue by ma2b0043** [thenewboston-developers/Website#1867]
Hi you need to make a small update to the projects page, as if you head over to https://thenewboston.com/projects and if you open any approved project(for example: https://thenewboston.com/projects/2058c70b-c5f2-404b-a377-ab767937b651 ), you will see that under each section `overview`, `problem`, `target audience`...etc, you'll that each section has a guiding text, like if you see the `overview` section down below: 

![Screenshot from 2021-06-15 19-06-24](https://user-images.githubusercontent.com/60430226/122068374-caf6ca00-ce0d-11eb-834b-c6198e087889.png)

In this section we have `A brief summary, situation, plan, and outline about the project, bigger picture, functionality and the possible outcome from this project`<- guiding text, which is a little confusing for the new user as it causes a slight confusion of whether this text belongs to the actual project overview or is this a standard guideline that every projects needs to include in their overview? 

We need to remove this for the overview section as well as for all other sections we have on the project page. 

If you need more clarification in this task, let me know in the comments below or on discord.

**Comment by hemanth-kotagiri** [comment]
Here's what I understood and correct me if I am wrong: You need the guiding text for all the sections(such as overview, problem...) to be removed.
And can I take this?

**Comment by ma2b0043** [comment]
> Here's what I understood and correct me if I am wrong: You need the guiding text for all the sections(such as overview, problem...) to be removed.
> And can I take this?

Actually this a core team task, not a bounty based task. You can do these task if you want: https://thenewboston.com/tasks/All
