### ISSUE TITLE
Mobile Issues

### ISSUE THREAD

**Issue by hemanth-kotagiri** [thenewboston-developers/Website#1868]
**Bug Description**
On mobile screens, the top navigation dropdown menus do not respond to when they are tapped and the layout of the page is off.

**Expected behavior**
When the navigation links are tapped, they should redirect to that specific page and the layout of the page should be mobile-specific.

**Actual behavior**
The links when they are tapped, are not redirecting to their respective pages and layout of the page is off screen.

**Screenshots**
![1b4c0c2c-9b51-4103-a0eb-793f7c88d79f](https://user-images.githubusercontent.com/24365579/122090522-765f4900-ce25-11eb-8950-6e9ccf5767ef.jpg)
![71cde1d6-8ce0-414a-a1ec-d6a4f09423b0](https://user-images.githubusercontent.com/24365579/122090550-7eb78400-ce25-11eb-90e3-a9bf55ab6524.jpg)
![6d462717-278c-4048-9d0d-1531ea0cd5ab](https://user-images.githubusercontent.com/24365579/122090561-81b27480-ce25-11eb-913a-e8bf7ce0120e.jpg)
![f6225738-4e4d-4b16-b731-0d8eb1ff5ae9](https://user-images.githubusercontent.com/24365579/122090568-8414ce80-ce25-11eb-8ff9-b435abcf4418.jpg)

Mobile : Samsumg Galaxy M31

**Account Number**
5468b09948f1be8034e043fffcc7a9ac915957b0877eed0eda7e88c3c3631351

**Comment by angle943** [comment]
fixed by this: https://github.com/thenewboston-developers/Website/pull/1872
