### ISSUE TITLE
Add Analytics Page onto the Website

### ISSUE THREAD

**Issue by ma2b0043** [thenewboston-developers/Website#1869]
Hi, you need to add the analytics page onto the website as per the following design.

Design Link:
- https://www.figma.com/file/wWisZsaUf9xzkCCqlzvG3G/Analytics?node-id=1%3A4
- https://www.figma.com/file/wWisZsaUf9xzkCCqlzvG3G/Analytics?node-id=243%3A0

GitHub Issue: https://github.com/thenewboston-developers/Design/issues/209

If you need help or clarification in this task, let me know in the comments below or on discord. Thank you!

**Comment by wakawakathedev** [comment]
asking @angle943 for clarification - the code looks merged, seeking more info

**Comment by wakawakathedev** [comment]
closing as this was removed from website
