### ISSUE TITLE
Prevent content shifting in tutorials page

### ISSUE THREAD

**Issue by jamessspanggg** [thenewboston-developers/Website#1877]
There is content shifting in the tutorials page, we will need to explicitly set the width and height of the cards to prevent content shifting

https://user-images.githubusercontent.com/32864116/122566839-976ca780-d07a-11eb-8429-ab883c8f9065.mp4

**Comment by avinashupadhya99** [comment]
Hi, I can work on this. Do you mean the content shifting on the cards?

**Comment by jamessspanggg** [comment]
> Hi, I can work on this. Do you mean the content shifting on the cards?

yes correct

**Comment by angle943** [comment]
PAID
