### ISSUE TITLE
Search queries should be case insensitive

### ISSUE THREAD

**Issue by Niekon01** [thenewboston-developers/Website#1884]
**Bug Description**
When doing a search, an exact match should not be required, and a search should work regardless of the search query case.

**Steps to Reproduce**
Steps to reproduce the behaviour:
1. Go to FAQ page (https://thenewboston.com/faq/all)
2. Type "coins" (for example) and hit search. You will see some results. Now change the case of any letter (Coins or coinS or CoinS).
3. No results will be shown

**Expected behaviour**
The search should display results regardless of the case of the query

**Actual behaviour**
Results are shown only when a query is entirely in lower case

**OS and Browser**
 - OS: Windows
 - Browser: All

**Additional context**

**Account Number**
18c07b4227cb0993fa7a1db834834e42461a0d9f61b2b157dfbfee625bbf3de6

**Comment by avinashupadhya99** [comment]
Hi, I will be working on this if it's alright

**Comment by angle943** [comment]
@avinashupadhya99 as a note, in the future, if there is a `PR Reward` label on an issue, feel free to begin working on it right away without getting permission from us!
