### ISSUE TITLE
Add "Head of Human Resources" job to website

### ISSUE THREAD

**Issue by Chrisha1212** [thenewboston-developers/Website#1906]
Add the following job opening to the website.

***

#### Job Description
Our company is looking for a Head of Human Resources to join our team. to oversee all personnel-related matters and ensure we use our resources beneficially.

#### Responsibilities
- a. Working with team leads to write job descriptions
- b. Overseeing the application process
- c. Overseeing the interview process
- d. Overseeing payments and accounting 
- e. Documenting standard memo conventions for payments
- f. Assisting team leads with the onboarding process
- g. Oversee creation of the new recruiting team

#### Technology Requirements
- a. Leadership abilities
- b. Familiar with Github
- c. Knowledgable with Gsuite

#### Reports To
- First Name: [Chrisha]
- Discord Username: [MsChrishaph#0709]

**Comment by SazidAhmed** [comment]
How to apply for this job?
Would I DM MsChrishaph#709 ?

**Comment by avinashupadhya99** [comment]
I will work on this :)
