### ISSUE TITLE
Add "Recruiting Lead" job to website

### ISSUE THREAD

**Issue by Chrisha1212** [thenewboston-developers/Website#1907]
Add the following job opening to the website.

***

#### Job Title
 Recruiting Lead

#### Job Description
HR Team is looking for Recruiting Lead that will assists organizations in recruiting new staff by finding talent, sifting applicants, and managing the selection process.

#### Responsibilities
- a. Documenting all recruiting related processes
- b. Creating a recruiting strategy
- c. Organizing contact lists and all other recruiting related documents
- d. Working with HR to optimize the hiring process
- e. Building out an effective and productive recruiting team

#### Technology Requirements
- a. Leadership abilities 
- b. Familiar with Github
- c. Knowledgable with Gsuite

#### Reports To
- First Name: [Chrisha]
- Discord Username: [MsChrishaph#0709]

**Comment by avinashupadhya99** [comment]
I will be working on this :)
