### ISSUE TITLE
Blur issue of Top Navigation Bar in FAQ page

### ISSUE THREAD

**Issue by hemanth-kotagiri** [thenewboston-developers/Website#1924]
**Bug Description**
The background of the top navbar is not blurred properly in the FAQ page.

**Steps to Reproduce**
1. Go to FAQ page.
2. Scroll down slowly to see the error.

**Expected behavior**
The background should be blurred.

**Actual behavior**
The background is not blurred properly.

**Screenshots/Recordings**
![image](https://user-images.githubusercontent.com/24365579/124485568-55f23100-ddca-11eb-8e1f-0d15bb8350b6.png)

**OS and Browser**
 - OS: Arch Linux
 - Browser Brave

**Comment by hemanth-kotagiri** [comment]
I'll be working on it. I'll update the progress and if I couldn't fix - I'll let you guys know.

**Comment by Radu033** [comment]
I will be working on this issue.

**Comment by hemanth-kotagiri** [comment]
@Radu033 any update on this?

**Comment by roovy54** [comment]
@Radu033 I'm working on this.

**Comment by hemanth-kotagiri** [comment]
Hi, @roovy54. I have briefly looked into the codebase and I feel this issue probably requires _alot_ of refactoring to be made specific to the NavBar component. There's some div/element which is messing around with the CSS and what you have done above is actually not the same behavior (blur effect) that we see in other links, such as the homepage.

**Comment by Radu033** [comment]
@hemanth-kotagiri  yes, I could fix the blur issue, there needs to be some refactoring, not much though.  But I saw that the ticket is in "Not Ready" label so for now I stopped working on it until it will be added to "ready for development" as the readme says that we should not work on issues with the "Not Ready" label.
![image](https://user-images.githubusercontent.com/6954983/125174887-a6053500-e1c8-11eb-883e-2ab082307295.png)

**Comment by EmmanuelORivera** [comment]
Hi guys I'm new in the community. So i just looking for a simple task to practice, and i found this issue that i think is just a CSS problem. 
But at the same time i can't understand what is the expected behavior, it is that the navbar doesn't need blur?
Also is there a prototype on Figma to see the expected behavior?

**Comment by Lalisfeed** [comment]
<img src="https://user-images.githubusercontent.com/59479762/126608203-2b7986fa-b6cc-4ea4-87cd-fa8e28a73275.png" width="500px" align="center">

**Bug Discription**
Blur effect impacts other pages.

fix this by either removing the blur effect globally or by adding blur effect to the `div.TopLinks` and `div.DeveloperPortalLayout__breadcrumb`

**Comment by angle943** [comment]
hello @hemanth-kotagiri , sorry for the delay, but I saw your PR and it looks good. What is your account # so that you may get the bounty?

**Comment by hemanth-kotagiri** [comment]
Hello, @angle943. I have raised the issue regarding this but I haven't fixed it(I tried to, but things became a little complicated for me here). If you are referring to PR #2014, then that's not my work. I will soon share my account details here. Thanks!

**Comment by masakachristopher** [comment]
Hello @angle943 It was my work with PR #2014 and not @hemanth-kotagiri

**Comment by masakachristopher** [comment]
Correct

**Comment by angle943** [comment]
made a bounty request. @masakachristopher you should be paid soon!
