### ISSUE TITLE
Top navigation render performance

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Website#1927]
Improve the rendering performance of the top navigation. It may be difficult to see in the video but there is a bit of lag/rendering bottlenecks when using the top navigation, particularly when switching between menus. Any way we can optimize the performance would be great.

https://user-images.githubusercontent.com/8547538/124522460-30ecc680-dda8-11eb-9083-ce068691769c.mp4

**Comment by angle943** [comment]
i think we have a fade-in/fade-out. do you want me to tget rid of those?

**Comment by jamessspanggg** [comment]
I believe the `hello text animation` plays a big part in the lag, i tried removing em and its much smoother
