### ISSUE TITLE
Add Developer Portal's Living Whitepaper's Landing Page onto the website

### ISSUE THREAD

**Issue by ma2b0043** [thenewboston-developers/Website#1931]
Hi, you need to add Developer Portal's Living Whitepaper's Landing Page onto the website. The things you may need to complete this task are as follows:
- Content:
https://docs.google.com/document/d/1_6OCmqL0OK5UiWJROe-EbRYAQa9s-iuIIQOdv_Vd5Bs/edit
- UI & Handoff
https://www.figma.com/file/x6gQN0dfrzCq1iDfbLQTXZ/Living-Whitepaper?node-id=1%3A3
- Other materials
https://drive.google.com/drive/folders/1WZYNsT2bJ16_zbteY34gd2HHfIPeyZUr?usp=sharing
White Paper Diagrams-20210705T032731Z-001.zip

Link to design issue: https://github.com/thenewboston-developers/Design/issues/223

All of the design guidelines and materials are provided in the links listed above^, and if you need assistance, kindly let us know asap, so that we can help you.

Breakdown of tasks (to be confirmed):
- [x] Add basic routes for pages (James)
- [x] Create dev portal layout, contains top links, breadcrumbs container, side bar etc (James)
- [x] Responsive main structure of the living whitepaper landing page (James)
- [x] Principal Entities on the network documentation (Sanjeev)
- [x] Principal Events and Processes on the network documentation (Sanjeev)
- [x] Architecture - deep dive documentation (James)
- [x] Breadcrumb component + sidebar component (James)

**Comment by jamessspanggg** [comment]
Hi, can provide permissions for the content as well as the UI & handoff to the FE team?

**Comment by manishram** [comment]
@jamessspanggg please DM me your Figma email on Discord. I'll send you the invite.

**Comment by jamessspanggg** [comment]
hi @angle943 @thesanjeevsharma 

Since Justin is occupied with the beta wallet, Sanjeev should we work on this together? This page seems to be quite huge.

We can break the task down, make small changes and merge to development regularly, since the page is not able to be accessed by the public.

**Comment by thesanjeevsharma** [comment]
Sure @jamessspanggg, let me have a thorough look at the Figma design then I'll get back to you on discord. 👍
