### ISSUE TITLE
Text overflow thenewboston_node.business_logic.blockchain.base.BlockchainBase

### ISSUE THREAD

**Issue by Lalisfeed** [thenewboston-developers/Website#1941]
**Bug Description**
Mobile: Text overflow broke UI

**Steps to Reproduce**
1. Go to 'https://thenewboston.com/progress'
2. Click on 'blockchain'
3. Scroll down to 'last second issue'

**Expected behavior**
No overflow like this

<img src="https://user-images.githubusercontent.com/59479762/125373288-7dd12e00-e3a2-11eb-8052-ac39346d60a7.jpg" width="500px" />

**Actual behavior**
Text overflow

**Screenshots/Recordings**

<img src="https://user-images.githubusercontent.com/59479762/125372660-47df7a00-e3a1-11eb-9415-f8fba0f6bb4b.jpg" width="500px" />

**OS and Browser**
 - OS: Android
 - Browser: Chrome

**Additional context**
[this page](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Text/Wrapping_Text) can be used as a reference for css

 **Account Number**
> 6663b43af069d9d4d303cd1a13d63e9d206ab786eba694b3e23f4dfdb3670d34

**Comment by Lalisfeed** [comment]
I'll update account details few hours later

**Comment by Hamza091** [comment]
I am working on this issue.

**Comment by Lalisfeed** [comment]
👌check readme.md

**Comment by Lalisfeed** [comment]
I updated the account details
