### ISSUE TITLE
Add `Senior SEO Specialist` job to the website

### ISSUE THREAD

**Issue by manishram** [thenewboston-developers/Website#1946]
Add the following job opening to the website.

***

#### Job Title
Sample Job Title

#### Job Description
We are looking for a talented Senior SEO Specialist to join our team.

#### Responsibilities
- Develop optimization strategies that improve the search engine results rankings
- Research SEO keywords to use throughout the website and marketing materials
- Collect data and report on traffic, rankings, and other SEO aspects
- Review technical SEO issues and recommend fixes
- Collaborate with others within the marketing team to manage SEO strategy
- Write compelling and high-quality website content, including blog posts and page descriptions
- Update content and website links for maximum optimization and search engine rankings

#### Technology Requirements
- 3+ years of experience in successfully developing and executing SEO campaigns
- Understanding of search engine algorithms and ranking methods
- Experience with SEO industry programs, such as Google Analytics
- Knowledge of keyword research and data mining tools
- Able to complete competitive analysis of other organizations within the industry
- Excellent written and verbal communication skills
- Comfortable analyzing high volumes of data daily
- Expertise in WordPress.

#### Reports To
- First Name: Manish
- Discord Username: Manish#4379

**Comment by Lalisfeed** [comment]
Where is the application form?

**Comment by manishram** [comment]
**Application form:** https://docs.google.com/forms/d/e/1FAIpQLSf4Mk-vxO3Nl193LkCSGPOrrT5uDvA27peH8du7hSnfUsxb0A/viewform

@Lalisfeed @Hamza091

**Comment by Lalisfeed** [comment]
The #1948 PR for this issue is merged and this can be closed
