### ISSUE TITLE
Broken Responsiveness

### ISSUE THREAD

**Issue by Lalisfeed** [thenewboston-developers/Website#1974]
**Bug Description**
Mobile: Div breaks websites responsiveness because of more width

**Steps to Reproduce**
1. Go to 'https://thenewboston.com/projects'
2. Scroll down to `<div class="ProjectsHero_wrapper">`
3. See error

**Expected behavior**
Fits into the screen

**Actual behavior**
Breaks Responsiveness

**Screenshot**

> the min-width of this div is more than screen width which causes x-overflow

**Account Number**

> 6663b43af069d9d4d303cd1a13d63e9d206ab786eba694b3e23f4dfdb3670d34

**Comment by jamessspanggg** [comment]
Please attach a screenshot of the bug and provide the specific width of the bug mentioned

**Comment by jamessspanggg** [comment]
@Lalisfeed sorry I can't seem to understand the issue at hand? Your screenshot looks fine to me?

**Comment by Lalisfeed** [comment]
open the page in browser and reduce the tab width to miminum and check if there is an x-overflow

**Comment by jamessspanggg** [comment]
@Lalisfeed ah got it, thanks for the clarification
