### ISSUE TITLE
Doubled Text entry

### ISSUE THREAD

**Issue by stweyel** [thenewboston-developers/Website#1978]
**Bug Description**
Doubled Text in 'Principal Entities on the Network' description box on Developer Portal Page.

**Steps to Reproduce**
1. Go to: https://thenewboston.com/developer/whitepaper

2. Scroll down

**Account Number**
94161c7f2d143eb387aab95b1ee4d334df57a233a63bd466c8b2368148c4917d

**Comment by stweyel** [comment]
@jamessspanggg just curious... who will be rewarded what in these cases?

**Comment by jamessspanggg** [comment]
hi @stweyel, in this case, the bug bounty will be paid to you and the PR reward will be paid to the person who fixes it
