### ISSUE TITLE
When we open a question on the FAQ page it scrolls to that question

### ISSUE THREAD

**Issue by YashovardhanSingh** [thenewboston-developers/Website#1989]
**Bug Description**
When I open a question to see its answer on the FAQ page, the page scrolls and makes that question the top of the screen disturbing the view.

**Steps to Reproduce**
1. Go to [FAQ Page](https://thenewboston.com/faq/all)
2. Click on any question to open it up
4. See the error

**Expected behavior**
The page should not scroll and stay where it was

**Actual behavior**
The page scrolls to the question

**Screenshots/Recordings**
Before opening
![image](https://user-images.githubusercontent.com/63940326/126874683-07993726-3b1a-4d55-82a5-95f0ca0b7fa1.png)
After opening
![image](https://user-images.githubusercontent.com/63940326/126874694-88a91a77-b2f1-454b-bb2e-d5a8bb189572.png)

**OS and Browser**
 - Browser = Chrome

**Account Number**
38a99b8f1916eab0471ca1df26e7fe5e71d845e6ea5b233cd3d93a75097ea2d6

**Comment by hemanth-kotagiri** [comment]
I'd like to work on this.

**Comment by hemanth-kotagiri** [comment]
Hey, @jamessspanggg. I'd like to work on this.

**Comment by jamessspanggg** [comment]
@kashikushi can u advise on the UI/UX for this?

**Comment by kashikushi** [comment]
if you would like to stop the scrolling, you can go ahead but this is how we have designed it as it is looking now. let's see how it would look with a fixed view on the opened question.

**Comment by hemanth-kotagiri** [comment]
Hi, @kashikushi . Wouldn't that be better if the scrolling happened in a smooth transition, instead of a hard direct transition like it is now?

**Comment by kashikushi** [comment]
Yes. Please go ahead.

**Comment by hemanth-kotagiri** [comment]
I am waiting on your response on this, @jamessspanggg.

**Comment by jamessspanggg** [comment]
yep go ahead @hemanth-kotagiri  sorry for the late reply

**Comment by Lalisfeed** [comment]
It would be better if this is implemented
- remove link from text and add share icon to share faq
- remove pound symbol completely or hide it in responsive mode
- change opacity for active cards

what do you say?

**Comment by hemanth-kotagiri** [comment]
I am super busy with college and stuff here until next month, I will soon implement the changes. Thanks, @Lalisfeed for your suggestions. @jamessspanggg and @kashikushi please give it a review.

**Comment by jamessspanggg** [comment]
@kashikushi please advice

**Comment by kashikushi** [comment]
@jamessspanggg ok. I will update you soon about UX

**Comment by kashikushi** [comment]
<img width="1128" alt="Screenshot 2021-08-22 at 19 36 19" src="https://user-images.githubusercontent.com/35629401/130355424-61076b2d-04f3-4ebc-8214-bf3b4cc4e426.png">
1. you can remove the link from question text since the user can drop down by click on the dropdown icon
2. Pound sign is not a part of the design, it can be hidden.
3. Share icon can be added
4. no need to change opacity for the active card to keep the design consistent with the design system. We can elevate drow shadow instead.

**Comment by manishram** [comment]
Bug bounty has been paid for this one.
