### ISSUE TITLE
Tasks to Bounties

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Website#2045]
Rename Tasks to Bounties including all relevant variables, files, and anywhere throughout the source code.

**Comment by YashovardhanSingh** [comment]
can i do it?

**Comment by jamessspanggg** [comment]
go ahead @YashovardhanSingh

**Comment by YashovardhanSingh** [comment]
working on it

**Comment by YashovardhanSingh** [comment]
@buckyroberts and @jamessspanggg https://github.com/YashovardhanSingh/Website
The task is done.

**Comment by hussu010** [comment]
@YashovardhanSingh you'll need to create Pull Request linking this issue.

**Comment by YashovardhanSingh** [comment]
@hussu010 https://github.com/thenewboston-developers/Website/pull/2052

**Comment by YashovardhanSingh** [comment]
38a99b8f1916eab0471ca1df26e7fe5e71d845e6ea5b233cd3d93a75097ea2d6
