### ISSUE TITLE
[All desktop devices] Highlighted section should be less in height 

### ISSUE THREAD

**Issue by webdeveloperswj** [thenewboston-developers/Website#205]
Url : https://thenewboston.com/
![image](https://user-images.githubusercontent.com/59204822/93762585-7e3ee380-fc2d-11ea-879f-df58b0b05296.png)

**Comment by GermaVinsmoke** [comment]
@angle943 This one's completed, right?

**Comment by webdeveloperswj** [comment]
Solved
