### ISSUE TITLE
Developer Portal Related Updates

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Website#2055]
Update all the `Developer` links to point to https://developer.thenewboston.com/ rather than https://thenewboston.com/developer.

Once that is done, remove any existing "Developer Portal" related code (API's, Living Whitepaper, Projects, etc...) from this repository since it has already been moved over to https://github.com/thenewboston-developers/Developer-Portal and we will be using that repo for all developer related example, documentation, and guides from now on.

**Comment by thesanjeevsharma** [comment]
I think we forgot to move `SDKs and Libraries` page. I'll create a PR for it. 👍
