### ISSUE TITLE
Page x-overflow

### ISSUE THREAD

**Issue by ghost** [thenewboston-developers/Website#2073]
**Bug Description**
Image is not flexible. 

**Steps to Reproduce**
1. Go to 'https://developer.thenewboston.com/whitepaper/principal-entities#principal-entities-governance'
2. Scroll down to 'Image'
3. See error

**Expected behavior**
Image fits to screen.

**Actual behavior**
Image doesnot fit into the screen

**OS and Browser**
 - OS: Android

**Account Number**
> 6663b43af069d9d4d303cd1a13d63e9d206ab786eba694b3e23f4dfdb3670d34

**Comment by wakawakathedev** [comment]
I'll close this issue since the OP hasn't clarified the issue
