### ISSUE TITLE
Rendering new urls on scroll

### ISSUE THREAD

**Issue by ghost** [thenewboston-developers/Website#2074]
**Bug Description**
when I scroll on developer pages the page keeps rendering new urls for every new id

**Steps to Reproduce**
1. Go to 'https://developer.thenewboston.com/whitepaper/principal-entities'
2. keep scrolling
3. See error

**Expected behavior**
pages have to render url only when url on the headings with ids are clicked

**Actual behavior**
Site renders new urls for each div scrolled.

**OS and Browser**
 - OS:  Android :(

**Account Number**
> 6663b43af069d9d4d303cd1a13d63e9d206ab786eba694b3e23f4dfdb3670d34

**Comment by jamessspanggg** [comment]
hi, this is actually intended as we are using `react-scroll` which updates the url id while scrolling.
