### ISSUE TITLE
Download wallet page has x-scroll in mobile view

### ISSUE THREAD

**Issue by jamessspanggg** [thenewboston-developers/Website#2075]
## Task Description

While in mobile view, the download wallet page seems to have x-scroll. Please visit `https://thenewboston.com/download` to view.

<img width="420" alt="Screen Shot 2021-10-09 at 12 38 43 PM" src="https://user-images.githubusercontent.com/32864116/136644263-897de742-430c-4efa-87c5-2f043b59e19c.png">

## To Note

Please only work on the issues that you are assigned to, PRs will be ignored if you are not assigned to the task. If the assigned issues have not been worked on for more than 3 days, we will remove the assignment.

**Comment by kala2** [comment]
Hello, i can take this one!

**Comment by jamessspanggg** [comment]
assigned to @kala2 check this folder for the page `src/containers/Download`

**Comment by kala2** [comment]
Submitted PR #2086
