### ISSUE TITLE
Rename all references of "account manager" to "wallet"

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Website#2090]
We recently changed our marketing terminology of the "account manager" application to "wallet", however there are various places around the website (especially the docs) where it still refers to the app as "account manager". Please rename all of these to "wallet".

## Example
<img width="1048" alt="Screen Shot 2021-10-11 at 11 11 14 PM" src="https://user-images.githubusercontent.com/8547538/136884919-a7646aad-ff3b-4771-bfe6-eba52def7fb2.png">

**Comment by hussu010** [comment]
working on the issue.

**Comment by hussu010** [comment]
Found no instance of "Account Manager" on the website repo. Creating a PR on the Developer Portal repo.
