### ISSUE TITLE
[All laptop devices] Highlighted table should be aligned inline with other tables

### ISSUE THREAD

**Issue by webdeveloperswj** [thenewboston-developers/Website#210]
Url : https://thenewboston.com/leaderboard
![image](https://user-images.githubusercontent.com/59204822/93761692-d543b900-fc2b-11ea-9dc2-56128d5fa669.png)
![image](https://user-images.githubusercontent.com/59204822/93762059-81859f80-fc2c-11ea-8108-64d719deda74.png)

**Comment by buckyroberts** [comment]
Outdated designs
