### ISSUE TITLE
[Internet Explorer] Site not working 

### ISSUE THREAD

**Issue by webdeveloperswj** [thenewboston-developers/Website#211]
Version 11
https://thenewboston.com/
![image](https://user-images.githubusercontent.com/59204822/93766544-32dc0380-fc34-11ea-8916-d50377ac57f5.png)

**Comment by guptstagram** [comment]
Can I take it?

**Comment by angle943** [comment]
@webdeveloperswj @guptstagram is this still an issue?

**Comment by webdeveloperswj** [comment]
Yes @angle943

**Comment by zinoadidi** [comment]
can i attempt it?

**Comment by Hristijan95** [comment]
For now (and I think forever) let's just add a message that IE is not supported.
I highly doubt that someone will need to open this website from IE, ever.

**Comment by nparoski** [comment]
I've created potential fix for this issue #1044
