### ISSUE TITLE
[All mobile devices] Highlighted section should have space from left

### ISSUE THREAD

**Issue by webdeveloperswj** [thenewboston-developers/Website#213]
Url : https://thenewboston.com/
![image](https://user-images.githubusercontent.com/59204822/93768032-6c157300-fc36-11ea-8d6c-6b38a00812f2.png)

**Comment by ankitsridhar16** [comment]
I will do it can you assign it to me ?

**Comment by Niekon01** [comment]
Sorry @ankitsridhar16, but this issue has already been fixed in Pull #246.
