### ISSUE TITLE
[FAQ] Link pointing to governance overview does not exist

### ISSUE THREAD

**Issue by Creatinas** [thenewboston-developers/Website#2155]
**Bug Description**
Clicking on "docs" hyperlink from https://thenewboston.com/faq/all#how-does-governance-work redirects to https://thenewboston.com/ as https://thenewboston.com/governance/overview does not exist

**Steps to Reproduce**
1. Go to 'https://thenewboston.com/faq/all#how-does-governance-work'
2. Click on 'docs'
3. Observe opened page

**Expected behavior**
User is redirected to governance overview page

**Actual behavior**
User is redirected to https://thenewboston.com/

**OS and Browser**
 - OS: macOS Monterey 12.0.1
 - Browser Chrome

**Account Number**
679aff9a630beb883cc10368a2dedb7722e63b682143ae9fd2e051c13b710752

**Comment by thesanjeevsharma** [comment]
This link should be updated to this - https://developer.thenewboston.com/whitepaper/principal-entities#principal-entities-governance

cc: @manishram

**Comment by manishram** [comment]
Paid 250 TNBC as a bug bounty.

**Comment by Creatinas** [comment]
@thesanjeevsharma  can i take this one?

**Comment by thesanjeevsharma** [comment]
@manishram PR bounty for @Creatinas
