### ISSUE TITLE
Update hero text in `apps` page

### ISSUE THREAD

**Issue by manishram** [thenewboston-developers/Website#2160]
**Page:** https://thenewboston.com/apps
![image](https://user-images.githubusercontent.com/22790904/143884113-5bfa411b-7276-4b5e-b584-e1a1ce5dd8e3.png)

**Replace** 
`Join thousands of other players and explore games and a variety of applications built by our community to earn or spend your TNBC.` 

**with** 

`Explore games and a variety of apps built by our community to earn or spend TNBC, the official cryptocurrency of thenewboston.`

**Comment by Creatinas** [comment]
Can i do this one?
