### ISSUE TITLE
Security: Npm Audit

### ISSUE THREAD

**Issue by wakawakathedev** [thenewboston-developers/Website#2162]
As of eeff37f22f4c090d29e4314aadbf36932de79c8c
running npm audit

```
52 vulnerabilities (31 moderate, 18 high, 3 critical)
```

---
**User Story** 

As a **developer**. 
**I would like** to automate/warn of high/critical security issues within CI. 
**such that** I can be notified about security vulnerabilities.

**Acceptance criteria:**
- The app should continue to work as expected
- Deployed to production
- Code is peer-reviewed

**Comment by jamessspanggg** [comment]
yep sounds good to me @wakawakathedev
