### ISSUE TITLE
[All mobile devices] Unable to see content easily

### ISSUE THREAD

**Issue by webdeveloperswj** [thenewboston-developers/Website#217]
Url : https://thenewboston.com/leaderboard
https://recordit.co/TWJ3z2H1T0
![image](https://user-images.githubusercontent.com/59204822/93774454-e944e600-fc3e-11ea-8dfd-df2058462026.png)

https://thenewboston.com/tasks
http://recordit.co/dTK80GRDGJ
![Uploading image.png…]()

**Comment by buckyroberts** [comment]
Fixed

**Comment by webdeveloperswj** [comment]
Issue solved 
![Uploading image.png…]()
