### ISSUE TITLE
Add app showcase placeholder in home page to prevent content shifting

### ISSUE THREAD

**Issue by jamessspanggg** [thenewboston-developers/Website#2185]
## Current

The current home page will have content shifting during the api calls to the apps api:

https://user-images.githubusercontent.com/32864116/152628207-6072e36f-b9e7-4fa0-bcd0-34b97e415a58.mp4

## Expected

Have some sort of a default placeholder for the app show cases to prevent content shifting

**Comment by hydra91** [comment]
Closed, will be redesigned.
