### ISSUE TITLE
[All mobile devices] Table should be aligned horizontally center

### ISSUE THREAD

**Issue by webdeveloperswj** [thenewboston-developers/Website#219]
URL : https://thenewboston.com/guide/introduction

![image](https://user-images.githubusercontent.com/59204822/93782315-0e8a2200-fc48-11ea-9169-7ba3cf63c086.png)

**Comment by BozidarSiljanoski** [comment]
I would like to take this

**Comment by buckyroberts** [comment]
Done.

**Comment by webdeveloperswj** [comment]
Issue solved
