### ISSUE TITLE
What's New Section

### ISSUE THREAD

**Issue by hydra91** [thenewboston-developers/Website#2192]
Whats New section
https://www.figma.com/file/uw6yrOCNOMwf1AFpJ3AmSF/What%27s-New?node-id=139%3A1572
Featured Content
Title, Image, Link for 3 different items

**Comment by hydra91** [comment]
@led76marx please add a description

**Comment by led76marx** [comment]
## Description
We need a section in the main page of our website that will be updated whenever we have something new and major to share with the community, including, but not limited to:

- New video tutorial series kick-off
- New library / SDK / API
- Updates on the whitepaper
- News about the core team
- Important project kick off
- Even (but NOT limited to) a LINK to a blog post

### Example
Here is how the nano community does it:

![image](https://user-images.githubusercontent.com/20023713/158499492-bc483646-5e2d-45f5-91f4-5629ba851d39.png)

![image](https://user-images.githubusercontent.com/20023713/158499654-d7165c0b-c618-4cf7-bc1c-433f8bae9a50.png)

From this screenshot we don't need the Latest Updates. Also, we are not going to create a feed for blog posts that will pull content automatically, or any other form of feed. It is not only about new blog posts.

## Elements
We need a section that holds a a. thumbnail image, b. date, c. a title, d. 1-2 sentences that will contain the link to a video/dev portal page/blog post page, e. a way to navigate to next/previous update. For the previous example, I highlight these elements (and only these).

![image](https://user-images.githubusercontent.com/20023713/158500367-de4781da-1a8a-4b40-9b91-311cad7e07c2.png)

All content will be manually entered by the author.

We only care about the functionality, not how similar it will look to the above image.

**Comment by osaroadade** [comment]
I have made the appropriate changes to the design. Please @led76marx and @kristykjlee let me know if this is along the lines of what we want. 

https://www.figma.com/file/1B5Z34oOx5jl4eoXUXoRyj/What's-New-(Copy)?node-id=604%3A2103
