### ISSUE TITLE
[iPhone SE] Page moved horizontally

### ISSUE THREAD

**Issue by webdeveloperswj** [thenewboston-developers/Website#220]
**Bug Description**
Page is horizontally scrollable where it should not be.

Url : https://thenewboston.com/guide/introduction
Video : https://recordit.co/lX2ssTout2

**Comment by csmtcy** [comment]
#257 submitted a pull request for resolving the horizontal scroll issue

**Comment by lapstjup** [comment]
#266 submitted a pull request for resolving the horizontal movement of page in Docs.

**Comment by webdeveloperswj** [comment]
Issue solved
