### ISSUE TITLE
[Desktop] Title should be aligned vertically center

### ISSUE THREAD

**Issue by webdeveloperswj** [thenewboston-developers/Website#247]
Url : https://thenewboston.com/leaderboard/All
![image](https://user-images.githubusercontent.com/59204822/94420758-3e827980-01a2-11eb-97cb-1d5d25a6531b.png)

**Comment by BozidarSiljanoski** [comment]
I would like to take this

**Comment by GermaVinsmoke** [comment]
@webdeveloperswj completed, right?
