### ISSUE TITLE
[iPhone 320Px] Text goes out of section

### ISSUE THREAD

**Issue by webdeveloperswj** [thenewboston-developers/Website#248]
Url : https://thenewboston.com/leaderboard/All
![image](https://user-images.githubusercontent.com/59204822/94421153-c5375680-01a2-11eb-9484-04fd0f8789ab.png)

**Comment by itsnikhil** [comment]
### Which one of the fix mentioned below should I push?

|  |  |
| - | - |
| **Fix A** - Stacked horizontally | **Fix B** - Text-overflow: Ellipsis |
| ![localhost_3000_leaderboard_All(iPhone 5_SE)](https://user-images.githubusercontent.com/20350674/95026759-4a45d280-06b1-11eb-8753-93c72850cc58.png) | ![thenewboston com_leaderboard_All(iPhone 5_SE)](https://user-images.githubusercontent.com/20350674/95026888-099a8900-06b2-11eb-99f9-8e96d4968d61.png) |

**Comment by webdeveloperswj** [comment]
@itsnikhil 2 nd looks better
