### ISSUE TITLE
[iPad 4] Site not working

### ISSUE THREAD

**Issue by webdeveloperswj** [thenewboston-developers/Website#249]
**OS iOS, v7
Browser  Safari**

![image](https://user-images.githubusercontent.com/59204822/94422163-46431d80-01a4-11eb-8c01-20a72cb3df3e.png)

**Comment by angle943** [comment]
@webdeveloperswj does this issue still exist?

**Comment by webdeveloperswj** [comment]
Yes @angle943

**Comment by zinoadidi** [comment]
#542
