### ISSUE TITLE
[Desktop]Font size for text looks too small

### ISSUE THREAD

**Issue by webdeveloperswj** [thenewboston-developers/Website#250]
Url: https://thenewboston.com/leaderboard/All
![image](https://user-images.githubusercontent.com/59204822/94422658-0fb9d280-01a5-11eb-85ea-79f7746b6407.png)

**Comment by nazmulshuvo03** [comment]
PR created #256

**Comment by kristykjlee** [comment]
This has been moved to the Design Repository
