### ISSUE TITLE
Title should be changed

### ISSUE THREAD

**Issue by webdeveloperswj** [thenewboston-developers/Website#251]
**Bug Description**
Title for date is completed it should be changed as issue is not solved yet

**Steps to Reproduce**
1. Go to https://thenewboston.com/leaderboard/All
2. Check title for Dates

**Expected behavior**
Title should  "Issued Date or Only Date" 

**Actual behavior**
Title is "completed"

**Screenshots/Recordings**
![image](https://user-images.githubusercontent.com/59204822/94424460-dfbffe80-01a7-11eb-9056-3fb729ba3728.png)

**OS and Browser**
 - OS: [Windows 10]
 - Browser [Chrome]

**Account Number**
15e164325715c9552911caf7e3ea1759f4c2ccba5fd82864a4d811d67935c4f9

**Comment by nazmulshuvo03** [comment]
Created a PR #252

**Comment by buckyroberts** [comment]
Note to self - differentiate bug tickets from bug solutions (PR's)

**Comment by LunarDeveloper** [comment]
Should this issue be closed? @buckyroberts mentioned the title was correct as "completed" in PR #252 and closed the PR.

**Comment by kristykjlee** [comment]
This has been moved to the Design Repository
