### ISSUE TITLE
Points displayed on Leaderboard page and actual points given on github are different

### ISSUE THREAD

**Issue by webdeveloperswj** [thenewboston-developers/Website#263]
![image](https://user-images.githubusercontent.com/59204822/94682686-ee8ee880-0342-11eb-9324-90dc9cabcb68.png)
![image](https://user-images.githubusercontent.com/59204822/94682808-2007b400-0343-11eb-91d0-f9660631334b.png)
![image](https://user-images.githubusercontent.com/59204822/94682874-3d3c8280-0343-11eb-89ef-7db5db69c06d.png)
![image](https://user-images.githubusercontent.com/59204822/94682948-5c3b1480-0343-11eb-9206-2e1e318fd195.png)

**Comment by johnjacobkenny** [comment]
Perhaps you could introduce some kind of github action or bot to ensure that the closed PRs are correctly transferred? I could try to help with that if there is more direction from the team!

**Comment by Hristijan95** [comment]
Looks like this issue was a misunderstanding back when there were no different labels for issues & PRs, so I am closing it. Everything looks fine as far as I can see.
