### ISSUE TITLE
Team Page

### ISSUE THREAD

**Issue by kristykjlee** [thenewboston-developers/Website#271]
We are including a Team page to the marketing site so it is easier to understand who is working on what and to understand who people can reach out to if they have any questions.

Team Pages:
- [ ] 'All' page will be organized by the most recent contributors that have been added. 
- [ ] 'All' page will display 1. Name of Contributor, 2. Title, 3. Team Name (Link to the team (Side menu)), 4. Slack Name, 5. Github Name (Link to their GitHub), 6. Pay per day. 
- [ ] For all the other team pages (For ex, Analytics, BE Devs, etc..) we will display 1. Name of Contributor, 2. Title, 3. Slack Name, 4. Github Name (Link to their GitHub), 5. Pay per day
- [ ] For all other team pages, Team Lead will always be the 1st card, so people know who to ask questions to. 

Style:
- [ ] Please use the same card component we use for the Leaderboard
- [ ] Use existing side menu component
- [ ] Use status component for Team Lead
- [ ] Names that are too long with truncated with ellipses

**Note**
The API is not complete for this task yet, however here are the Website API requirements. For now we can design the UI with dummy data and hook it up to the API later:
https://docs.google.com/document/d/1a17x4_2SS1LZgMJTkFYIIk9SvOYmrceijGmxHkg0KCI/edit?usp=sharing

**Figma**
https://www.figma.com/file/ChyT88EmP2Rmzx35I9erCL/Marketing-Site?node-id=587%3A1262

<img width="1329" alt="Screen Shot 2020-10-04 at 11 22 55 AM" src="https://user-images.githubusercontent.com/8547538/95023823-ffd24080-0633-11eb-99d7-a7e6c5296ed5.png">

**Comment by brmendez** [comment]
I'd like to work on this.

**Comment by mankarsandesh** [comment]
This page done or pending. let me know otherwise I will finish this.

**Comment by brmendez** [comment]
Hi @mankarsandesh, I would like to be assigned to this — just waiting on becoming a collaborator. Cc: @kristykjlee

**Comment by buckyroberts** [comment]
@brmendez all yours
