### ISSUE TITLE
Openings Page Update

### ISSUE THREAD

**Issue by kristykjlee** [thenewboston-developers/Website#273]
We are updating the Openings page so whenever someone clicks on a job opening, we are no longer expanding the card to see the full details, but we will now take them to a new page that has the details of the openings. We are doing this because it is easier for people to send links of the specific job opening to a variety of people. 

- [ ] When user selects on a card, we will take them to that specific job opening.
- [ ] Selected job opening page will house the job description. 
- [ ] Each selected job opening page will have its own unique link so people can share the specific job easily with many people.
- [ ] Selected job opening page will have a Back button, to go back to the list of openings. 
- [ ] Add Openings title
- [ ] Add hover state to these specific cards
- [ ] Use existing side menu component

https://www.figma.com/file/ChyT88EmP2Rmzx35I9erCL/Marketing-Site?node-id=577%3A1182

**Comment by thesanjeevsharma** [comment]
@kristykjlee I would like to work on this one.
