### ISSUE TITLE
Email Capture for Landing Page

### ISSUE THREAD

**Issue by audous** [thenewboston-developers/Website#274]
Idea: Create an email Capture form for users who are not joining the development community, but have made it to the TNB landing page to check on the ICO progress.

Objective: Capture users emails so we can notify them when they can invest.

There are two main segments of users to capture on the landing page. 

The segment we are capturing now for the github and slack team building. 

And the segment that is here for investment and other ICO reasons.

(#design) Needs discussion and Design tags.

**Comment by Francaolisa** [comment]
This is good.

**Comment by ph4ni** [comment]
I know this is just a mockup but the text in the image doesn't really reflect TNB accurately. Makes it sound like it's just another crypto project. Gotta be more authentic than "invest", "faster", "gains", "only-600". We are not generating hype for a shitcoin here.
I hope either @buckyroberts, @kristykjlee, or someone else who has a better idea about what we are really doing, writes something better.

**Comment by Francaolisa** [comment]
@ph4ni you are right. Just now I saw that text. Isn’t right to mention gains or hype thing. Is best to simply say “subscribe to get u  update on when we will launch “ or something more simple.

**Comment by audous** [comment]
@ph4ni and @Francaolisa Good points. I removed the image to avoid confusion.

**Comment by buckyroberts** [comment]
Closing, outdated since entire marketing page including messaging has been updated
