### ISSUE TITLE
Update Account Manager Guide Pages

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Website#280]
Update Account Manager guide screenshots that are out of date. For example:

## Old Account page

<img width="1409" alt="AccountOverview 9a07b5f3" src="https://user-images.githubusercontent.com/8547538/95025251-3791b600-063d-11eb-9c0b-5030c57b3171.png">

## New Account page

<img width="612" alt="Screen Shot 2020-10-04 at 12 27 44 PM" src="https://user-images.githubusercontent.com/8547538/95025242-29dc3080-063d-11eb-98a1-d93b9b5b7ad6.png">

**Comment by colfax23** [comment]
I'll knock this out tomorrow!
