### ISSUE TITLE
Landing Page Style Update

### ISSUE THREAD

**Issue by kristykjlee** [thenewboston-developers/Website#283]
### **Please review all updates below:**

**Remove**
- [ ] Remove grey background on the 'Build software. Earn digital currency' section.
- [ ] Remove grey background on the 'Say goodbye to 10 minute block times' section.

**Style Update:** 
- [ ] On 'Build software. Earn digital currency' text, make the 'Build' & 'Earn' **bold**.
- [ ] Update Earn color to Sail Green 400
- [ ] Update the mocks of the Send Points modal & the desktop app. (Attachments on the ticket)
- [ ] Update the Send Points modal size to 326x414
- [ ] Update the desktop app image to 875x491
- [ ] Include color block strip for the 3 steps. The color is Sail Gray 50.
- [ ] Change INSTANT TRANSACTIONS text color to Sail Green 500 & to 16px font size
- [ ] For the 'Say goodbye...' section, put the 2nd paragraph on the bottom of the first one.
- [ ] Bold 'Say goodbye...' title
- [ ] Put the bitcoin & thenewboston comparison on the right of the 'Say goodbye' text blocks.
- [ ] Update the width of the bitcoin & thenewboston cards to 300x396
- [ ] For the bitcoin & thenewboston comparison, remove the arrow inbetween the cards and put the text 'vs' instead.
- [ ] Please make sure all the 'Build software...', the 3-step points, & the 'Say goodbye...' text blocks are all left aligned. 
- [ ] Update the footer to be straight not diagonal. 
- [ ] Include social media icons on the footer, (Slack, Linkedin, Facebook, Twitter, & Github) (Icons are attached to the ticket.
- [ ] Make all primary buttons use 16px font size
- [ ] Update unselected top nav and unselected side menu button color from Sail Gray 400 to Sail Gray 500
- [ ] Lastly, this mock is on a 1366px screen, the width of the sticky header from the logo to the Download button is 1294px. Please make sure if you stretch the width of the screen, the logo & all the buttons will not stretch with it. We want the content to stay in a narrow view.

https://www.figma.com/file/ChyT88EmP2Rmzx35I9erCL/Marketing-Site?node-id=491%3A349

[Marketing Site Images.zip](https://github.com/thenewboston-developers/Website/files/5326017/Marketing.Site.Images.zip)

[Social Media Icons.zip](https://github.com/thenewboston-developers/Website/files/5326030/Social.Media.Icons.zip)

**Comment by mankarsandesh** [comment]
I will work on this. and Update Soon. thanks

**Comment by moki298** [comment]
@kristykjlee @angle943 Regarding the last item in the above check list, I infer 1366px should be the max width of the nav bar which should never expand even if the browser window expands on wide monitors/devices. Is my understanding right? If yes please check the below snapshot(this is how it looks on wide monitors @ >1366px width) and let me know what you think. Thanks.

![Screen Shot 2020-10-23 at 4 55 31 PM](https://user-images.githubusercontent.com/21165330/97053547-23144f80-1551-11eb-9907-8e4513aeef00.png)

**Comment by moki298** [comment]
I went ahead and created a pull request for these changes, all the changes have been added. Regarding my question in above comments, I went ahead and made changes so that the nav bar looks like as shown in first snapshot above for wide screens(>1366px) and normal(as seen in second snapshot above) for <=1366px screens.

**Comment by kristykjlee** [comment]
@moki298 Hey moki, on bigger screens such as 1920px, the nav buttons itself will continue to remain 1294px width, but the navigation background with the dropshadow on it needs to stretch out so it doesn't create a weird dropshadow cut off. 
![Screen Shot 2020-10-24 at 6 18 47 PM](https://user-images.githubusercontent.com/68207101/97096754-6c35d380-1625-11eb-9a4e-bb423b80d924.png)

**Comment by kristykjlee** [comment]
@moki298 Also not sure if you already did this, but just wanted to make sure, please make sure all the content is left aligned. 
![Screen Shot 2020-10-24 at 6 09 11 PM](https://user-images.githubusercontent.com/68207101/97096810-37764c00-1626-11eb-812d-da4e9c9fccdc.png)

**Comment by moki298** [comment]
@angle943 @kristykjlee  everything is added and complete, do check and merge. Thanks!
