### ISSUE TITLE
[All mobile devices] On Leaderboard page Popup for Contributors info should be aligned vertically center

### ISSUE THREAD

**Issue by webdeveloperswj** [thenewboston-developers/Website#287]
![image](https://user-images.githubusercontent.com/59204822/95204606-f3034780-0801-11eb-965e-f327f37616ec.png)

**Comment by VishakhaAwasthi01** [comment]
Can I take this?

**Comment by buckyroberts** [comment]
@VishakhaAwasthi01 We have to send this through design first. They may want to keep it this way.

**Comment by mofodox** [comment]
@buckyroberts Based on my understanding from the design itself, the modal wanted to be like a mobile 'native'-esque modal which it will come up from the bottom. Is

**Comment by mofodox** [comment]
@buckyroberts Based on my understanding from the design, the modal should come out from the bottom of the screen like a mobile native-esque experience. Is that right @kristykjlee ?

**Comment by mersimoski** [comment]
@buckyroberts @kristykjlee @thesanjeevsharma 
![image](https://user-images.githubusercontent.com/62712311/98708495-8855a680-2381-11eb-8bc1-3b6faed03f7e.png)
will this work? If yes please assign it to me

**Comment by manishram** [comment]
I like it the way it is currently. It gives a more native-app-like experience. Also good for one-hand use I guess. What do you say @mofodox ?

**Comment by mofodox** [comment]
> I like it the way it is currently. Its design is also similar to the current design of Navigation Link Modal when the user clicks the Hamburger button in the right top corner plus gives a more native-app-like experience. Also good for one-hand use I guess. What do you say @mofodox ? 
> 
> 
> 
> ![navigation](https://user-images.githubusercontent.com/22790904/98800358-463a6c80-2436-11eb-8e8f-cb90d05c4625.JPG)
> 
> 

Yes I guess that's how the design is designed for. It makes the design more "native-esque".

**Comment by manishram** [comment]
Yeah please close this issue then.
