### ISSUE TITLE
Add the functionality to use font-weight with our Inter Font

### ISSUE THREAD

**Issue by angle943** [thenewboston-developers/Website#293]
Currently, we can't set the font-weight with our Inter fonts. We have to change the font-family to make it bold. For example: `font-family: var(--font-family-inter-bold)`.

Research into how to update this. We don't want to update the font weight by changing the font-family.

**Comment by colfax23** [comment]
I'll take this one!

**Comment by colfax23** [comment]
Ok, so I did some digging and it seems the approach outlined in this post is best:
https://www.456bereastreet.com/archive/201012/font-face_tip_define_font-weight_and_font-style_to_keep_your_css_simple/

This SO post shows a snippet of the implementation at a glance:
https://stackoverflow.com/a/10046346

I'll work on a PR the fonts file (https://github.com/thenewboston-developers/Website/blob/development/src/styles/_font.scss), leaving the existing font-family options in tact for to not break anything, and once that gets merged I can work on migrating the css to utilize the new font weight specification if you want!

**Comment by angle943** [comment]
@colfax23 here's the AccountManager's same issue: https://github.com/thenewboston-developers/Account-Manager/issues/416

Open for you to take this one if you want ;). These two tickets alone will put you as #3 contributor on our leaderboard ;)

**Comment by colfax23** [comment]
Consider it done!
