### ISSUE TITLE
[All mobile Devices] Page is not responsive 

### ISSUE THREAD

**Issue by webdeveloperswj** [thenewboston-developers/Website#298]
Page is not responsive it moves horizontally
URL : https://thenewboston.com/guide/root-account-file

 Screenshots :
 http://recordit.co/d9MskJ2t2S

**Comment by angle943** [comment]
![Screen Shot 2020-10-19 at 8 28 48 PM](https://user-images.githubusercontent.com/5943963/96536832-bf84dc00-1249-11eb-8bf7-ba2486c8d45c.png)

Its due to this table. Make this table responsive by giving the table itself a horizontal scroll

**Comment by GermaVinsmoke** [comment]
This page also https://thenewboston.com/guide/resync-triggers
