### ISSUE TITLE
[Mozilla Firefox] Remove dotted border coming around navigation menu when clicked on it

### ISSUE THREAD

**Issue by webdeveloperswj** [thenewboston-developers/Website#303]
Version  80.0.1
![image](https://user-images.githubusercontent.com/59204822/96138931-e8406500-0f1b-11eb-81cb-d6c7956059fa.png)

**Comment by angle943** [comment]
we need `active` states for all of our buttons

**Comment by mersimoski** [comment]
I would like to take this and resolve it.

**Comment by mersimoski** [comment]
PR made about fixing this

**Comment by mersimoski** [comment]
There's "outline: 0" to it but doesn't apply, and if we add !important it will remove the dots, if this is they way to fix it please assign it to me.

**Comment by mersimoski** [comment]
`focus` state has outline, so the issue will be fixed when added `outline: none` to the `focus` state. Please assign it to me.
