### ISSUE TITLE
Homepage design

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Website#31]
Homepage needs general design improvements

![screencapture-localhost-3000-2020-07-13-15_42_05](https://user-images.githubusercontent.com/8547538/87360735-99032680-c51f-11ea-946c-5c2a76073702.png)

**Comment by kristykjlee** [comment]
**Update Marketing Site Landing Page elements/layout**

Update newboston logo 
Contributors, Developers, Roadmap will now be top nav
Clicking on thenewboston logo will return user back to Landing Page
Copy text directly from mocks
Make slack & github buttons both 114px width
Include slack & github logos inside buttons
Send Points image has a dropshadow of X: 15, Y: 15, Blur: 40, Hex #: 042235, Opacity: 25%
In-App 'Banks' image has a dropshadow of X: 0, Y: 15, Blur: 40, Hex #: 042235, Opacity: 25%
Kill Roboto, please use **Helvetica Neue** for all text on marketing site
Please make sure to use thenewboston logo inside the 'View Guide' button


**Update Colors:**
Background color 1: #F6F9FC
Background color 2: #131F41
ALL text color: #042235
Secondary button color: #C1C9D2
Primary button color: #042235


**Figma**
https://www.figma.com/file/ChyT88EmP2Rmzx35I9erCL/Marketing-Site?node-id=6%3A0
