### ISSUE TITLE
Updated Top Navigation 

### ISSUE THREAD

**Issue by kristykjlee** [thenewboston-developers/Website#317]
Now that we have more pages in our marketing site, we need to update our top navigation to be grouped in a more intuitive way to help guide people on how to get started or involved in the community. The way the navigation structure will be grouped will now be: 

**1. Get Started**
- Documentation 
- Tutorials 
- Tasks 

**2. Community**
- Join the Community!
- Openings
- Team
- Leaderboard 

**Additional Criterias**
- [ ] Ignore FAQ page for now, will be added in the new future
- [ ] Join the Community page can link to our current 'Help' page for now.
- [ ] Include icons per each page in the dropdown
- [ ] Include the little descriptions under each page title in the dropdown
- [ ] Include hover state for each dropdown nav
- [ ] Keep dropdown centered to the nav title
- [ ] For tablet & mobile, when the user selects on the hamburger menu, we will display to them all the page options.

https://www.figma.com/file/ChyT88EmP2Rmzx35I9erCL/Marketing-Site?node-id=934%3A1386

[Social Media.zip](https://github.com/thenewboston-developers/Website/files/5434176/Social.Media.zip)

**Comment by angle943** [comment]
We need to create a popover component to do this one. I'll handle this one
