### ISSUE TITLE
Updated Footer 

### ISSUE THREAD

**Issue by kristykjlee** [thenewboston-developers/Website#318]
**On the footer of the marketing site, please include...:**
- [ ] thenewboston logo
- [ ] Social media icons
- [ ] All page navs listed 
- [ ] Ignore FAQ section for now, will be added in the new future

https://www.figma.com/file/ChyT88EmP2Rmzx35I9erCL/Marketing-Site?node-id=934%3A1387

[Social Media.zip](https://github.com/thenewboston-developers/Website/files/5434175/Social.Media.zip)

**Comment by thesanjeevsharma** [comment]
I would like to work on this!
