### ISSUE TITLE
Social Media page

### ISSUE THREAD

**Issue by kristykjlee** [thenewboston-developers/Website#319]
We are completely revamping our 'Help' page to being our Social Media page. 

- [ ] Basically remove everything from that Help page and we can start from scratch if thats easier.
- [ ] Change nav title from 'Help' to 'Social' 
- [ ] Include header text 'Join the Community' 
- [ ] Include subtext 'Explore ways to get involved, and stay up-to-date with the latest announcements and events.'
- [ ] Include social media blocks that include the full social logo & wordmark (view attachments) 
- [ ] Clicking on social media blocks will link to the appropriate thenewboston social media account. 

https://www.figma.com/file/ChyT88EmP2Rmzx35I9erCL/Marketing-Site?node-id=0%3A1

[Social Media Wordmark.zip](https://github.com/thenewboston-developers/Website/files/5434232/Social.Media.Wordmark.zip)

**Comment by angle943** [comment]
Engineering Notes:

url should be `/social`

**Comment by colfax23** [comment]
I'll take this!  Should have a PR by Tuesday.
