### ISSUE TITLE
FAQ page

### ISSUE THREAD

**Issue by kristykjlee** [thenewboston-developers/Website#320]
We need to build out an FAQ page on our marketing site to help answer additional questions the community has been asking. This page will be updating often based off the questions we get from the community. 

**Criteria:**
Please copy all the text that is on the mocks itself. 
https://www.figma.com/file/ChyT88EmP2Rmzx35I9erCL/Marketing-Site?node-id=606%3A2300

**Comment by angle943** [comment]
Engineering Notes. Please make each Question linkable with a hashtag & id

**Comment by aayushi14** [comment]
@angle943 @kristykjlee  Can you assign this to me?

**Comment by brmendez** [comment]
@aayushi14 Sorry! I am almost done with this.
