### ISSUE TITLE
Update social media buttons on the main marketing page

### ISSUE THREAD

**Issue by kristykjlee** [thenewboston-developers/Website#321]
On the marketing page, please update these social media buttons ![Screen Shot 2020-10-24 at 9 48 42 PM](https://user-images.githubusercontent.com/68207101/97099144-b8434100-1642-11eb-92b1-248fda144966.png)  to the new design on the mocks. 

- [ ] We are updating the social media icons to Sail Gray 900 and only including the social media icon but not the workmark.
- [ ] We are also going to include a YouTube icon on the right of the GitHub icon. 

https://www.figma.com/file/ChyT88EmP2Rmzx35I9erCL/Marketing-Site?node-id=934%3A1387

[Social Media.zip](https://github.com/thenewboston-developers/Website/files/5434182/Social.Media.zip)

**Comment by aayushi14** [comment]
@kristykjlee @angle943 Can you assign this to me? I am pushing my branch.

**Comment by aayushi14** [comment]
#323 Please let me know if it needs any changes.

**Comment by kristykjlee** [comment]
@aayushi14 @angle943 Sorry to bring this one up again. The logos itself needs to the white, while the button is the current color. The current logos look like they have an inner dropshadow.

**Current:**
![Screen Shot 2020-10-29 at 10 20 19 PM](https://user-images.githubusercontent.com/68207101/97663131-fae78d80-1a35-11eb-8822-f0c13d17724e.png)

**Design:**
![Screen Shot 2020-10-29 at 10 31 24 PM](https://user-images.githubusercontent.com/68207101/97663324-7e08e380-1a36-11eb-824d-cc7dff3843ef.png)
