### ISSUE TITLE
Update Initial Funds Page

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Website#334]
Updated with information about contributors, tasks, etc... https://thenewboston.com/guide/initial-funds

**Comment by taneishamitchell** [comment]
I'd like to take a crack at this, but see where overall documentation needs refactoring at some point. There are sections that are repetitive, e.g. "Blocks" is mentioned in Guides, Bank API, Validator API. Validator has multiple sections, etc.

@buckyroberts or @angle943 is there anything else I need to know before adding information about "Contributors and Tasks"? What else would you like to see here?
