### ISSUE TITLE
Replace Hompage Social Media Hero icons to use SVG Icons

### ISSUE THREAD

**Issue by angle943** [thenewboston-developers/Website#336]
prereq for this ticket: https://github.com/thenewboston-developers/Website/issues/335 - must be completed before this ticket

update these three icons to use the mdi-icons

![Screen Shot 2020-10-29 at 11 44 34 PM](https://user-images.githubusercontent.com/5943963/97669145-b57c8d80-1a40-11eb-8ece-56cf9aebc76d.png)

**Comment by aayushi14** [comment]
Will do it.

**Comment by angle943** [comment]
#335 has been merged. So this one is ready!
