### ISSUE TITLE
Top navigation popover clickable when closed

### ISSUE THREAD

**Issue by aayushi14** [thenewboston-developers/Website#347]
**Bug Description**
After clicking on the top navigation bar and selecting one of the options from the dropdown, the page navigates to the selected option and the popup closes, but the the popup area is still clickable.

**Steps to Reproduce**
1. Go to 'topNavBar'-> Click on 'Community'
2. Click on 'Leaderboard'
3. Keep mouse pointer on the first contributor's top-left side of Total earnings.
4. Mouse has hand pointer and when you click on the empty area you are directed to Openings page.

**Expected behavior**
Mouse should not be clickable. Popover should close completely.

**Actual behavior**
The popover area is hidden but clickable.

**Screenshots/Recordings**
[thenewboston - Google Chrome 2020-11-01 11-49-43.zip](https://github.com/thenewboston-developers/Website/files/5471468/thenewboston.-.Google.Chrome.2020-11-01.11-49-43.zip)

**Account Number**
100c627095785ab8a7ed04d548b53f4b0638c44b49c46aea6c003d7b06294881

**Comment by angle943** [comment]
ah yeah, i saw this bug in the morning :(. Hotfix has been deployed, it should be fixed now
