### ISSUE TITLE
Put "Hello World" in your OWN language!

### ISSUE THREAD

**Issue by angle943** [thenewboston-developers/Website#351]
![helloworld](https://user-images.githubusercontent.com/5943963/97818023-d0275000-1c54-11eb-9c27-69099f35fd8d.png)

We currently have a text in the homepage where the "Hello World" loops through in different languages. We want you to add your own language!

in the file `/src/containers/Home/HomeHero/hello-world.ts`, you will find the `HelloWorld` object. The key must be in the two-letter ISO code of your language (ex: en. see https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes), and the value must be `Hello World` in your own language.

**Please open up a Pull request!**

You will get 500 coins for this. But limit one per person, and please only add a language if you are a native speaker!

And please write your account # on the PR, so that I can send you coins!

**Comment by woosal1337** [comment]
Salam, Dünya!

**Comment by angle943** [comment]
gotta open up a Pull request @woosal1337 !

**Comment by woosal1337** [comment]
Which, branch?

**Comment by Yamen2** [comment]
مرحبًا يا عالم 
Marhabaan ya-alealam

**Comment by negoziator** [comment]
Hej verden 🇩🇰

**Comment by DWK55** [comment]
hi im new to programming but have some experience i just dont know where src/containers/Home/HomeHero/hello-world.ts is to edit to "de"

**Comment by Unlkoc** [comment]
> Which, branch?

Hello World in Turkish #480

**Comment by Ramin-RX7** [comment]
Add Persian Hello World #477

**Comment by Unlkoc** [comment]
> Hej verden 🇩🇰

Hello World in Turkish #500

**Comment by gunars-b** [comment]
Added Hello World in Latvian

**Comment by VJKLFT** [comment]
Added Hello World in Dutch #490

**Comment by murattimurtas** [comment]
> ![helloworld](https://user-images.githubusercontent.com/5943963/97818023-d0275000-1c54-11eb-9c27-69099f35fd8d.png)
> 
> We currently have a text in the homepage where the "Hello World" loops through in different languages. We want you to add your own language!
> 
> in the file `/src/containers/Home/HomeHero/hello-world.ts`, you will find the `HelloWorld` object. The key must be in the two-letter ISO code of your language (ex: en. see https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes), and the value must be `Hello World` in your own language.
> 
> **Please open up a Pull request!**
> 
> You will get 500 coins for this. But limit one per person, and please only add a language if you are a native speaker!
> 
> And please write your account # on the PR, so that I can send you coins!



> > Hej verden 🇩🇰
> 
> Hello World in Turkish #500

Merhaba Dünya

**Comment by murattimurtas** [comment]
"Merhaba Dünya" in turkish

**Comment by kaneki666** [comment]
i can write the full documentation in my language in Bengali! if you need

**Comment by aEmreAydemir** [comment]
Merhaba, Dünya !

**Comment by Rexkozy** [comment]
Kedu Ndeewo🤝

**Comment by suhailpappu** [comment]
When i try to merger it says " The base branch restricts merging to authorized users " what do i do?

**Comment by Hristijan95** [comment]
@suhailpappu Just create a Pull Request and reference this issue in it and we'll take care of the merge.

**Comment by suhailpappu** [comment]
@Hristijan95 Yes I already created one thank you.

**Comment by Mithileshxx765** [comment]
नमस्ते दुनिया

**Comment by Mithileshxx765** [comment]
नमस्ते दुनिया {Hindi}

**Comment by lost-folder** [comment]
Hello world in  Arabic #639

**Comment by Solo509HT** [comment]
Bonjou lemond (Haitian Creole)

**Comment by abhiprksh** [comment]
नमस्कार विश्व (Hindi)

**Comment by AayushKarna** [comment]
नमस्कार संसार (Nepali)

**Comment by satyamgupta1495** [comment]
namaste duniya(Hinglish)

**Comment by VincentHch** [comment]
Luxembourgish language #736

**Comment by VincentHch** [comment]
#736

**Comment by VincentHch** [comment]
#736

**Comment by kagisojamesthomba** [comment]
> ![helloworld](https://user-images.githubusercontent.com/5943963/97818023-d0275000-1c54-11eb-9c27-69099f35fd8d.png)
> 
> We currently have a text in the homepage where the "Hello World" loops through in different languages. We want you to add your own language!
> 
> in the file `/src/containers/Home/HomeHero/hello-world.ts`, you will find the `HelloWorld` object. The key must be in the two-letter ISO code of your language (ex: en. see https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes), and the value must be `Hello World` in your own language.
> 
> **Please open up a Pull request!**
> 
> You will get 500 coins for this. But limit one per person, and please only add a language if you are a native speaker!
> 
> And please write your account # on the PR, so that I can send you coins!

I have two questions, 1. If I am a native speaker of two languages ,can I add them both and 2. Are there any considerations for languages that do not have the 639-1 code but have another code like the 639-3 code , which consists of two characters?

**Comment by IronManCool001** [comment]
hello in bengali language: ওহে বিশ্ব

**Comment by lapstjup** [comment]
> hello in bengali language: ওহে বিশ্ব

@IronManCool001  - You have to open a PR in the appropriate file as mentioned in issue. Also hello world for bengali is already included. You are welcome to solve other issues.

**Comment by at-in** [comment]
Klingon doesn't have a 2 letter ISO code, will it cause any problem? @angle943

**Comment by suhailpappu** [comment]
@Hristijan95 I haven't received my 500?

**Comment by Hristijan95** [comment]
@suhailpappu, the coins are sent.
Can you please check again? Here's the transaction:
<img width="1137" alt="Screen Shot 2020-11-14 at 18 19 49" src="https://user-images.githubusercontent.com/5727677/99153139-f1515d00-26a6-11eb-8477-60c29f58705d.png">

**Comment by suhailpappu** [comment]
@Hristijan95 Yes bro the coins appeared just now after you replied. Thank you.

**Comment by frankiefab100** [comment]
Please how do I get this account #?

**Comment by at-in** [comment]
@Hristijan95 @angle943 can you check my PR #825 ?

**Comment by Raeab** [comment]
Selam Alem in Amharic

**Comment by Toledit** [comment]
Hello World in Afaan Oromoo #949

**Comment by Toledit** [comment]
Added hello World in Afaan Oromoo #949

**Comment by gsonly** [comment]
@angle943  I haven't received my 500?

**Comment by angle943** [comment]
@gsonly moved your PR to the 'done' section, you should be getting paid within the week. LMK if a week passes and you still haven't received coins

**Comment by Rexkozy** [comment]
I haven't received even a single coin..

**Comment by angle943** [comment]
@Rexkozy can you link me the PR that you have made for this
