### ISSUE TITLE
iPad homepage scrolling issue

### ISSUE THREAD

**Issue by angle943** [thenewboston-developers/Website#355]
when on the homepage on an iPad, there's two issues:

1) scrolling is not fluid
2) It appears that whenever the "Hello world" gets updated, the screen flicks back to the top.

Try to find a fix for these issues

**Comment by angle943** [comment]
@lapstjup i will test this one once your changes are live. It was only happening on an actual iPad. If it's fixed, you'll be paid for this one as well

**Comment by lapstjup** [comment]
@angle943 Were you able to test this?

**Comment by angle943** [comment]
@lapstjup yup i just did! and it fixed it wonderfully. sending points your way
