### ISSUE TITLE
Integrate GitHub OAuth into Front-end

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Website#364]
Integrate GitHub OAuth into front-end. After users login to their GitHub accounts, they should be redirected back to our app, and our app should be able to access their GitHub information using the user's access token.

We can just `console.log` their user information for now. No UI needed (aside from any buttons/links needed for testing the flow).

**Comment by thesanjeevsharma** [comment]
Hey @buckyroberts, If you have enough time bandwidth for this feature I would love to work on this one. 

If it's requried urgently, you can assign it to someone else.

**Comment by buckyroberts** [comment]
@thesanjeevsharma all yours 👍
