### ISSUE TITLE
Make the Footer's background color go all the way to the bottom

### ISSUE THREAD

**Issue by angle943** [thenewboston-developers/Website#369]
On pages with less content, such as '/downloads', the footer's dark background color doesn't extend all the way to the bottom:

![Screen Shot 2020-11-01 at 9 56 20 PM](https://user-images.githubusercontent.com/5943963/97834821-97f03380-1c8d-11eb-9dae-4c3148cde439.png)

Make it such that this color stretches all the way to the bottom of the page, without arbitrarily giving the footer more height.

Like this:

![Screen Shot 2020-11-01 at 9 56 20 PM](https://user-images.githubusercontent.com/5943963/97835013-08975000-1c8e-11eb-9b2a-143c56f512b0.png)

**Comment by lapstjup** [comment]
Hi @angle943 , When I go to the downloads page, there is no white space at bottom of footer. I am running it on macOS.

**Comment by aayushi14** [comment]
@lapstjup To reproduce, check in iPad pro (1024x1366).
