### ISSUE TITLE
[Download] Make spacing equal on Download page

### ISSUE THREAD

**Issue by webdeveloperswj** [thenewboston-developers/Website#374]
Url : https://thenewboston.com/download
![image](https://user-images.githubusercontent.com/59204822/97837611-8c8c1f00-1d04-11eb-9b37-49e59b6446ca.png)

**Comment by thesanjeevsharma** [comment]
@Hristijan95 @lapstjup I don't think this is an issue. Can we close this?

**Comment by Hristijan95** [comment]
@thesanjeevsharma yes, and actually the spacing is equal now after some changes in the past few days.
