### ISSUE TITLE
The footer icons for small screen devices are not centered

### ISSUE THREAD

**Issue by Niekon01** [thenewboston-developers/Website#385]
**Bug Description**
The footer icons for small screen devices are not centered.

**Screenshots/Recordings**
![Capture](https://user-images.githubusercontent.com/55133485/97899598-84150200-1d5f-11eb-867a-5aa0a2ae9f1b.JPG)

**Account Number**
18c07b4227cb0993fa7a1db834834e42461a0d9f61b2b157dfbfee625bbf3de6

**Comment by angle943** [comment]
https://github.com/thenewboston-developers/Website/pull/384 solves this
