### ISSUE TITLE
Opening Updates

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Website#387]
Remove the following openings from the website (since they are already filled or no longer needed)
- Hiring Manager
- Accounting Manager (Python)
- Slack Community Manager

Update the following UI/UX Design Lead opening to:
- Position: `UI/UX Design Lead` > `UX/UI Designer`
- Technology Requirements: `Figma ` > `Figma or Sketch`

**Comment by itsnikhil** [comment]
Taking this 👋
