### ISSUE TITLE
Opening Left Menu Logic

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Website#388]
When you are viewing a specific opening details and you click on an opening category, you should be taken to that opening category page. 

## When you click this...
<img width="1258" alt="menunav" src="https://user-images.githubusercontent.com/8547538/97947273-9b44f700-1d41-11eb-8a00-f0b2c5b940c1.png">

## You should be taken here
<img width="1261" alt="Screen Shot 2020-11-02 at 7 29 35 PM" src="https://user-images.githubusercontent.com/8547538/97947324-ca5b6880-1d41-11eb-82ac-83b782f00775.png">

**Comment by thesanjeevsharma** [comment]
Hey, I am working on this!

**Comment by angle943** [comment]
@thesanjeevsharma you're right, we should update our routings. Here are the new acceptance criteria.

1. make our routes `/openings/:category` for the openings overview page, and `/openings/:category/:openingId` for the detail page.
2. please take a look at how we handle things at `/tasks`, and try to imitate the logic in there as much as possible (as much as it is reasonable to).
3. going to `/openings` should redirect to `/openings/all`

I've upped the points on this issue, @thesanjeevsharma . I'm going to assign it to you, let me know if you don't want it

**Comment by thesanjeevsharma** [comment]
Got it! Working on it.
