### ISSUE TITLE
Download page needs design update for iPhone 5

### ISSUE THREAD

**Issue by angle943** [thenewboston-developers/Website#389]
![Screen Shot 2020-11-02 at 8 41 07 PM](https://user-images.githubusercontent.com/5943963/97950469-cdf3ed00-1d4b-11eb-92ec-8d3af6144e79.png)

**Comment by lapstjup** [comment]
@kristykjlee 
Cause of the issue:-
The individual tabs have a margin right of 42px and so this doesn't scale down on mobile devices with width <= 400px. 
Should this margin right be made auto after 400px or is there a certain amount we still want to maintain ?

**Comment by nrednav** [comment]
Hi @kristykjlee, have you already finished work on this? I tried my hand at fixing this but since I'm still kinda new to open source work I only realised after that you were already assigned to this.

This is what I've got so far: https://recordit.co/KLinLnhY1L

**Comment by kristykjlee** [comment]
> Hi @kristykjlee, have you already finished work on this? I tried my hand at fixing this but since I'm still kinda new to open source work I only realised after that you were already assigned to this.
> 
> This is what I've got so far: https://recordit.co/KLinLnhY1L

Hey! The updates look perfect! I will assign this ticket to you so you can get compensated for it.
@angle943 This ticket is assigned to @nrednav

**Comment by nrednav** [comment]
Thanks! I will submit a PR soon.

**Comment by kristykjlee** [comment]
> Thanks! I will submit a PR soon.

@nrednav Copy and paste your account# so we can send you coins for completing the task :)

**Comment by nrednav** [comment]
@kristykjlee Thanks, it's: 4619c9fbc925437d7c81a0bdce60064d03d4697be86bc7621ad9cc894b637af6
