### ISSUE TITLE
Responsive left menu

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Website#39]
Early analytics are showing that the majority of the users are coming in from mobile.

<img width="346" alt="Screen Shot 2020-07-13 at 4 40 04 PM" src="https://user-images.githubusercontent.com/8547538/87364111-973d6100-c527-11ea-9063-b105f003c047.png">

<img width="585" alt="Screen Shot 2020-07-13 at 4 37 54 PM" src="https://user-images.githubusercontent.com/8547538/87364004-51809880-c527-11ea-9247-0deb29c48734.png">

**Comment by jacobclevenger** [comment]
The menu currently does not respond to the browser being resized. Consider adding a denounced window resize watcher to close the menu if the screen is small enough or open it if the screen is large enough.
