### ISSUE TITLE
Senior DevOps Engineer

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Website#394]
Add the following job opening to the website.

***

#### Job Title
Senior DevOps Engineer

#### Job Description
As Senior DevOps Engineer you will be a key contributor to designing, building, testing, managing, and maintaining some of the key technology that powers our digital currency network.

#### Responsibilities
- Analyze, troubleshoot and resolve system, software, network, and storage failures
- Configure, test, deploy, and upgrade software for production services in AWS
- Author and recommend settings for applications, operating systems, networks, and cloud services to improve performance, security, and reliability
- Design and develop monitoring and 100% uptime solutions for our digital currency network

#### Technology Requirements
- 3+ years experience with both software engineering and sysops or 6+ years experience as a DevOps engineer or similar
- Extensive experience with cloud computing and virtualization
- Expert knowledge of Linux
- Proven understanding of networking (TCP/IP, DNS, etc)

#### Reports To
- First Name: Bucky
- Slack Name: Bucky

#### Pay
- [x] 2,800 points/day

#### Application channels
- [x] Slack - Message Bucky
- [x] LinkedIn
- [x] Twitter
- [x] Reddit

**Comment by lapstjup** [comment]
I will take this.

**Comment by lapstjup** [comment]
Quick question - reportsTo has support for github right now. Do we maintain that or add slack username to it ? Since you mentioned Slack here.
