### ISSUE TITLE
Remove a line in all of our job openings

### ISSUE THREAD

**Issue by angle943** [thenewboston-developers/Website#395]
https://thenewboston.com/openings if you go to our job openings, a lot of the engineering jobs has this line:

"Ineligible for task points (you will be creating tasks for your team)"

Please remove this sentence in all the places that has it
![Screen Shot 2020-11-02 at 9 17 17 PM](https://user-images.githubusercontent.com/5943963/97952065-0cd87180-1d51-11eb-98d5-5852b5cf8382.png)

**Comment by itsnikhil** [comment]
Taking this 👋
