### ISSUE TITLE
Junior Python (Django) Developer

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Website#398]
Add the following job opening to the website.

***

#### Job Title
Junior Python (Django) Developer

#### Job Description
We are seeking a Junior Python (Django) Developer to work collaboratively with team members to develop and contribute to our digital currency network.

#### Responsibilities
- Expand your Python skills by working on packages, services, scripts, and deployments in a collaborative work environment
- Find, document and track bugs
- Create test plans/test cases, write test scripts, and execute all tests

#### Technology Requirements
- Able to manage source code using GitHub
- Fast learner who is eager to face new technological challenges and come up with innovative solutions
- Curious to learn how things really work
- Excellent teamwork and interpersonal communication skills

#### Reports To
- First Name: Bucky
- Slack Name: Bucky

#### Pay
- 2,800 points/day

#### Application channels
- Slack - Message Bucky
- LinkedIn
- Twitter
- Reddit

**Comment by itsnikhil** [comment]
On it!
