### ISSUE TITLE
add the floating button that takes us to the top of the page

### ISSUE THREAD

**Issue by kristykjlee** [thenewboston-developers/Website#399]

**Comment by manishram** [comment]
@kristykjlee On which page we have to add that button on any particular or all pages?

**Comment by manishram** [comment]
@kristykjlee I am working on it. Do you think the up facing thenewboston logo will be good?
![frefef](https://user-images.githubusercontent.com/22790904/98436242-d9566800-20ff-11eb-8104-7fe1d712873c.JPG)

**Comment by mofodox** [comment]
@manishram I guess we can provide the icon yeah? 

cc: @kristykjlee

**Comment by manishram** [comment]
Currently, I am using the upside logo of thenewboston as the "Go to Up" button. Let me know if you want change :)

![go-to-top](https://user-images.githubusercontent.com/22790904/98439827-7f16d080-211a-11eb-8ee7-caa2b5f58111.gif)

**Comment by manishram** [comment]
@kristykjlee Please let me know about the design of **floating button**.

**Comment by kristykjlee** [comment]
> @kristykjlee Please let me know about the design of **floating button**.

@manishram Heres the design for the floating button.
