### ISSUE TITLE
Head of Python Client Library Development

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Website#401]
Add the following job opening to the website.

***

#### Job Title
Head of Python Client Library Development

#### Job Description
As Head of Python Client Library Development you will be responsible for leading the development efforts for our Python client library. 

#### Responsibilities
- Writing technical documentation
- Recruiting Python developers
- Help assist other developers while managing work between team members
- Respond to GitHub issues and review PR's

#### Technology Requirements
- 2+ years of experience in Python
- Experience with Python web frameworks, ideally Django

#### Reports To
- First Name: Bucky
- Slack Name: Bucky

#### Pay
- 2,800 points/day

#### Application channels
- Slack - Message Bucky
- LinkedIn
- Twitter
- Reddit

**Comment by itsnikhil** [comment]
:)
