### ISSUE TITLE
YouTube Educator

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Website#403]
Add the following job opening to the website.

***

#### Job Title
YouTube Educator

#### Job Description
We are looking for YouTube Educators with technology, programming, or cryptocurrency related channels to collaborate with [thenewboston](https://www.youtube.com/user/thenewboston).

#### Responsibilities
- Create high quality educational tutorials
- Listen to feedback from community on which topics they would like to see most
- Optimize titles, descriptions, and tags for optimal SEO

#### Technology Requirements
- YouTube channel with 1,000+ subscribers
- YouTube channel related to technology, programming, or cryptocurrency

#### Reports To
- First Name: Bucky
- Slack Name: Bucky

#### Pay
- 2,800 points/day

#### Application channels
- Slack - Message Bucky
- LinkedIn
- Twitter
- Reddit

**Comment by itsnikhil** [comment]
What category would this role come under?
(Accounting/Community/Design/Engineering/Marketing)

**Comment by buckyroberts** [comment]
@itsnikhil Community
