### ISSUE TITLE
HashTag links doesn't go to desired location

### ISSUE THREAD

**Issue by angle943** [thenewboston-developers/Website#407]
when clicking on a hashtag link, it goes underneath the Topnav.

**Comment by Mutale85** [comment]
Can you please elaborate?  <a href="#register">Register</a>
When you click, its not taking you to the desired results?

**Comment by angle943** [comment]
ah sorry guys, this one's mine

**Comment by kryptonian41** [comment]
@angle943 I can take up this issue
