### ISSUE TITLE
Recruiter for Cryptocurrency Partnerships

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Website#408]
Add the following job opening to the website.

***

#### Job Title
Recruiter for Cryptocurrency Partnerships

#### Job Description
Seeking a Recruiter for Cryptocurrency Partnerships as we continue to strategically grow our digital currency network.

#### Responsibilities
- Reaching out to other cryptocurrency related websites, businesses, and communities regarding strategic partnerships
- Joining cryptocurrency related communities and discussions
- Researching trends and offering suggestions on any areas that you feel would be beneficial to our community
- Designing and implementing the overall recruiting strategy

#### Technology Requirements
- Strong understanding of cryptocurrency and blockchain technology

#### Reports To
- First Name: Bucky
- Slack Name: Bucky

#### Pay
- 2,800 points/day

#### Application channels
- Slack - Message Bucky
- LinkedIn
- Twitter
- Reddit

**Comment by aayushi14** [comment]
Category?

**Comment by buckyroberts** [comment]
@aayushi14 Community
