### ISSUE TITLE
Python / Django Developer

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Website#411]
Add the following job opening to the website.

***

#### Job Title
Python / Django Developer

#### Job Description
We are looking for a Python / Django Developer to help us build out both our digital currency network and Website API.

#### Responsibilities
- Designing and creating RESTful APIs
- Participating in architectural, design and product discussions
- Working in an environment with an excellent team of engineers

#### Technology Requirements
- Experience with Celery, DRF, and pytest
- 2+ years of experience in Django
- 4+ years of experience in Python

#### Reports To
- First Name: Bucky
- Slack Name: Bucky

#### Pay
- 2,800 points/day

#### Application channels
- Slack - Message Bucky
- LinkedIn
- Twitter
- Reddit

**Comment by itsnikhil** [comment]
Taking this
