### ISSUE TITLE
Task page margin

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Website#413]
<img width="1368" alt="margin" src="https://user-images.githubusercontent.com/8547538/97956830-8b87db80-1d5e-11eb-9c1b-3221741e951c.png">

**Comment by itsnikhil** [comment]
This looks similar to #369 which I have already fixed. You can close this issue :)

**Comment by angle943** [comment]
this issue still exists. @kristykjlee

**Comment by itsnikhil** [comment]
> this issue still exists. @kristykjlee 

Are your sure about this because for me in "development" branch. This doesn't exists

**Comment by angle943** [comment]
@itsnikhil try making the height of your browser smaller
