### ISSUE TITLE
Opening's starting content not in focus

### ISSUE THREAD

**Issue by lapstjup** [thenewboston-developers/Website#417]
**Bug Description**
Currently when you click on an opening card, the scroll position remains intact and the opening has to be scrolled up manually to view the details.

**Steps to Reproduce**
1. Go to [thenewboston/openings](https://www.thenewboston.com/openings)
2. Scroll down and click on Mobile Team Lead opening

**Expected behavior**
The beginning of a particular Opening should be in focus when the respective Opening card is clicked.

**Actual behavior**
The beginning of a particular Opening is not in focus when the respective Opening card is clicked.

**Screenshots/Recordings**
[Recording](https://drive.google.com/file/d/1lRU3cJt4KL1ddS1LW6UkqchaqS91IE-1/view?usp=sharing)

**OS and Browser**
 - OS: [e.g. macOS]
 - Browser [e.g. Chrome, Safari,Firefox]

**Account Number**
015447330144b709d1036eed79bdb93fb957b86502734584255edf2fb1029439

**Comment by angle943** [comment]
nice find @lapstjup

**Comment by angle943** [comment]
Please use the hook `useScrollToTopContainer` when working on this issue

**Comment by lapstjup** [comment]
Cool I will work on this then.
