### ISSUE TITLE
Update our README.md

### ISSUE THREAD

**Issue by angle943** [thenewboston-developers/Website#420]
A lot of open source repos have beautiful & meaningful READMEs, unfortunately this does not apply to our repo (yet!).

This will be more of an open-ended project for anyone willing to take it. Let's try to make our README as nice as possible, while at the same time having the relevant info it needs.

Suggestions that I have:

1) perhaps a link to our Q&A section on how to create a PR.
2) Explain that you have to go to the `issues` page and find issues to work on.
3) only one issue per pr.

Etc etc. Nothing corny or cheesy please

**Comment by thesanjeevsharma** [comment]
Hey, I am working on this.
