### ISSUE TITLE
Vertical scrollbar appearing in left menu

### ISSUE THREAD

**Issue by itsnikhil** [thenewboston-developers/Website#423]
**Bug Description**
[Desktop] Vertical scrollbar appearing in left menu of leaderboard at certain categories where there are no items

**Steps to Reproduce**
1. Go to 'https://www.thenewboston.com/leaderboard/All'
2. Click on 'Any category that does not have any item to display (for ex: thenewboston-python)'
3. Scrollbar will appear

**Expected behavior**
Layout should have more height so that scrollbar does not appear unnecessarily

**Screenshots**
![image](https://user-images.githubusercontent.com/20350674/98017285-06b3c500-1e25-11eb-993d-016ab2a0fddb.png)

**OS and Browser**
 - OS: Windows 10
 - Browser: Chromium edge

**Account Number**
e9c5acac0806aca6ba2c0ade74d93ec4f9a89d8743fa477c52ce9b7817dcad95

**Comment by angle943** [comment]
fantastic find @itsnikhil !
