### ISSUE TITLE
Auto Scroll to Top on Page Change

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Website#432]
When reading through the documentation pages and you click the next page using the bottom links, it no longer pops the user to the top of the page. Please add this logic back in.

Example URL: https://thenewboston.com/guide/root-account-file

<img width="787" alt="Screen Shot 2020-11-03 at 2 30 33 PM" src="https://user-images.githubusercontent.com/8547538/98047731-4953ae00-1de1-11eb-9e92-e68637407827.png">

**Comment by aayushi14** [comment]
This will be resolved with PR #422
