### ISSUE TITLE
Overlapping of text on top of expanded navbar

### ISSUE THREAD

**Issue by itsnikhil** [thenewboston-developers/Website#437]
**Bug Description**
[Mobile] Overlapping of "Top Contributors" on top of expanded navbar in the leaderboard page

**Steps to Reproduce**
1. Go to 'http://localhost:3000/leaderboard/All'
2. Click on 'Hamburger icon'
3. See text overlapping

**Expected behavior**
Ordering of expanded navbar elements should be on top of everything else

**Screenshots/Recordings**
![localhost_3000_(iPhone 5_SE)](https://user-images.githubusercontent.com/20350674/98080752-ee32c180-1e9b-11eb-9334-76ed4e9f2f6a.png)

**OS and Browser**
 - OS: iOS
 - Browser: Safari

**Account Number**
e9c5acac0806aca6ba2c0ade74d93ec4f9a89d8743fa477c52ce9b7817dcad95

**Comment by angle943** [comment]
nice find. i'll work on this
