### ISSUE TITLE
Rename "Points" to "Coins"

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Website#438]
Rename "points" to "coins" across the codebase.

- documentation
- file names
- function names
- variables
- etc...

**Comment by amarjeet987** [comment]
I'll take this.

**Comment by amarjeet987** [comment]
Updated and made a PR, https://github.com/thenewboston-developers/Website/pull/442

**Comment by angle943** [comment]
this is good work @amarjeet987 , you even changed the `AccountManagerSendPoint` component. nice nice

**Comment by angle943** [comment]
opened up an Account Manager counterpart: https://github.com/thenewboston-developers/Account-Manager/issues/422

Once that is done, we can update the image too: https://github.com/thenewboston-developers/Website/issues/445
