### ISSUE TITLE
Donations page

### ISSUE THREAD

**Issue by kristykjlee** [thenewboston-developers/Website#440]
**Top Nav & Footer Update**
- [ ] For top nav, FAQ & Donate buttons are going to go under a 'More' dropdown on the left of the Download button. 
- [ ] For footer, FAQ & Donate buttons under 'More' 

**Donate Page**
- [ ] TNB Account: b6e21072b6ba2eae6f78bc3ade17f6a561fa4582d5494a5120617f2027d38797
- [ ] Bitcoin Address: 3GZYi3w3BXQfyb868K2phHjrS4i8LooaHh
- [ ] Ethereum Address: 0x0E38e2a838F0B20872E5Ff55c82c2EE7509e6d4A

[donation logos.zip](https://github.com/thenewboston-developers/Website/files/5490347/donation.logos.zip)

[QR Codes.zip](https://github.com/thenewboston-developers/Website/files/5490230/QR.Codes.zip)

https://www.figma.com/file/ChyT88EmP2Rmzx35I9erCL/Marketing-Site?node-id=1447%3A2244

**Comment by angle943** [comment]
this ones mine. sorry contributors 8)
