### ISSUE TITLE
Update "Send Coin" image

### ISSUE THREAD

**Issue by angle943** [thenewboston-developers/Website#445]
Currently, our doc page https://thenewboston.com/account-manager/send-coins has an image that uses the word "point" rather than "coin".

![Screen Shot 2020-11-04 at 7 37 51 AM](https://user-images.githubusercontent.com/5943963/98131992-bf532600-1e70-11eb-825e-33dbc880b6fe.png)

Once the Account Manager's renaming issue is done: https://github.com/thenewboston-developers/Account-Manager/issues/422 , let's update this picture to show the new term

EDIT: The second image on this page as well: https://thenewboston.com/account-manager/create-an-account

Thanks @Niekon01 for that find

**Comment by Niekon01** [comment]
The second image on this page as well: https://thenewboston.com/account-manager/create-an-account

**Comment by Niekon01** [comment]
I would like to take this issue.

**Comment by angle943** [comment]
sure @Niekon01 , the AccountManager will be done tonight I believe, so you cacn screen shot away soon

**Comment by angle943** [comment]
its ready for ya. Account Manager's repo has been updated
