### ISSUE TITLE
Get Started / Community chevron icon disappears on toggle in Safari

### ISSUE THREAD

**Issue by lapstjup** [thenewboston-developers/Website#446]
**Bug Description**
When the **Get Started** or **Community** dropdown is clicked, the _up chevron icon_ disappears in Safari browser.

**Steps to Reproduce**
1. Go to [thenewboston](https://thenewboston.com) in Safari browser.
2. Click on **Get Started** dropdown.

**Expected behavior**
The up and down chevron toggle should work properly.

**Actual behavior**
The up chevron icon disappears.

**Screenshots/Recordings**
[Recording](https://drive.google.com/file/d/1Y9VVU1YE8a57Ttiy8CnxH-bDQT3aThIC/view?usp=sharing)

**OS and Browser**
 - OS: [macOS, iOS (iPad)]
 - Browser [Safari]

**Comment by angle943** [comment]
has to do with how safari handles the backface-visibility i believe

**Comment by kryptonian41** [comment]
> has to do with how safari handles the backface-visibility I believe

@angle943 yes I think if we set `backface-visibility: visible` explicitly when Icon **_TopNavPopoverButton__chevron-icon--open_** class is applied to the chevron icon, that will solve the issue.
