### ISSUE TITLE
Front-end Responsiveness/UX expert

### ISSUE THREAD

**Issue by angle943** [thenewboston-developers/Website#448]
Add the following job opening to the website.

***

#### Job Title
Front-end Responsiveness/UX expert

#### Job Description
We're looking for an experienced Front-end engineer who is able to test incoming PRs' design/responsive behavior. You will primarily be working on the Account Manager and Website repositories.

#### Responsibilities
- Perform code reviews on incoming PRs, testing specifically for the UI
- test in various viewports to make sure it looks fine
- Regularly test the applications to make sure there are no issues
- Create new issues if there are issues

#### Technology Requirements
- JavaScript (ES6+)
- React
- Redux
- Typescript
- HTML/CSS
- Experience with Figma (preferred)

#### Reports To
- First Name: Justin
- Slack Name: Justin

#### Pay
- 2,800 coins/day

#### Application channels
- Slack - Message Justin
- LinkedIn
- Twitter
- Reddit

**Comment by aayushi14** [comment]
On it
