### ISSUE TITLE
Popover content persists in the background

### ISSUE THREAD

**Issue by aayushi14** [thenewboston-developers/Website#451]
**Bug Description**
Popover content persists in the background.

**Screenshots/Recordings**
![Screenshot1](https://user-images.githubusercontent.com/33564949/98163822-5344e200-1eb1-11eb-9891-78144b983101.png)
![Screenshot2](https://user-images.githubusercontent.com/33564949/98163837-56d86900-1eb1-11eb-84fc-b6ec2065252e.png)
[thenewboston - Google Chrome 2020-11-04 14-09-13.zip](https://github.com/thenewboston-developers/Website/files/5490310/thenewboston.-.Google.Chrome.2020-11-04.14-09-13.zip)

**Comment by angle943** [comment]
yeah @aayushi14 i noticed this too :( . i'm trying to fix now. i'm beginning to hate this popover component i created
