### ISSUE TITLE
Make the command 'npm run lint' run for Windows/Linux users

### ISSUE THREAD

**Issue by angle943** [thenewboston-developers/Website#455]
currently, the command `npm run lint` doesn't work for Windows users (and possibly linux users). Lets update it such that it works for all platforms.

**Comment by moki298** [comment]
@angle943 I made a simple fix which should fix that issue, but we can add a more robust solution using this [cross-env](https://www.npmjs.com/package/cross-env). Let me know your thoughts.

**Comment by angle943** [comment]
@moki298 hey that sounds great! let's use `cross-env`

**Comment by moki298** [comment]
@angle943 hey sorry about my initial thoughts on cross-env, I was mislead by a comment in one of the  blogs where I researched this issue, but after reading the whole documentation of cross-env I don't think their module serves our purpose here. Their module is used in scenarios where we use env variables in npm scripts. I believe the simple fix I made should fix this and we just need to test this on a linux machine, but I am more than confident that it will work. So #458 can be merged.

Being said that please remove the 7500 tag for this issue, as its a simple fix and add something smaller/relevant. Thanks.

**Comment by angle943** [comment]
coins are given out irregardless of whether or not the solution is simple or not ;)
