### ISSUE TITLE
السلام عليكم - In Arabic

### ISSUE THREAD

**Issue by nabiloo19** [thenewboston-developers/Website#471]
**Bug Description**

**Steps to Reproduce**

**Expected behavior**

**Actual behavior**
A clear and concise description of what actually happened.

**Screenshots/Recordings**

**OS and Browser**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari]

**Additional context**

**Account Number**
Your account number where the reward coins for this bug bounty will be sent (pending review and approval).

[How to Create an Account](https://thenewboston.com/account-manager/create-an-account)

**Comment by angle943** [comment]
open up a pull request please (if you haven't done so already)
