### ISSUE TITLE
Create roadmap component

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Website#49]
Create roadmap component where we can:

- have teams (to group tasks)
- assign tasks to teams
- each task will be on it's own row (not multiple colors/tasks on the same row like in the diagram)
- in the colored rectangle area, there will be no text (since the task text will be on the left)
- ensure each teams tasks share a similar color
- set a range of 0-4 on the tasks to represent the Q1-Q4 range

Date values:

- 0 = beginning of Q1 (beginning of January)
- 1 = end of Q1 
- 4 = end of Q4 (end of December)

Notes:

- this component is simply the UI element only. the data will be static, there is no interaction needed (no adding tasks, deleting tasks interactions, etc...)

Roadmap component will be displayed here: [https://thenewboston.com/roadmap](https://thenewboston.com/roadmap)

<img width="398" alt="RoadmapUI 47f808b2" src="https://user-images.githubusercontent.com/8547538/87615792-5c266380-c6c8-11ea-9a63-2501063ce111.png">

```json
{
  "Account Manager": {
    "1": {
      "task_name": "Create roadmap page",
      "task_range": {
        "start": 1.3,
        "stop": 1.6
      }
    },
    "2": {
      "task_name": "Update deployment guide",
      "task_range": {
        "start": 2.1,
        "stop": 2.7
      }
    }
  },
  "Bank": {
    "1": {
      "task_name": "Create roadmap page",
      "task_range": {
        "start": 1.8,
        "stop": 2.9
      }
    },
    "2": {
      "task_name": "Write tests",
      "task_range": {
        "start": 3.1,
        "stop": 3.4
      }
    }
  }
}
```

**Comment by Senior-Hayato-Suzuki** [comment]
Awesome !!!

**Comment by Hristijan95** [comment]
Any ideas on how should we make it responsive? From a design point of view
