### ISSUE TITLE
Join Our Community! page revamp

### ISSUE THREAD

**Issue by kristykjlee** [thenewboston-developers/Website#495]
This ticket is assigned to @lukas-kasticky . 

**Potential considerations**
- number of growing community members 
- information on what each social media is used for
- anything else that you think would be helpful!

**Comment by ranka23** [comment]
**Suggestions for content:**

- Why join our community?
- What's in it for team members?
- What's next and exciting? - Perhaps, add the roadmap that is in discussion on Slack, when it's ready.

A simple suggestion/feedback form would be nice, to find out what other's are thinking. We can use a third party service to collect form data to avoid backend dev.

A new section on Homepage with a sweet sounding caption and a button(CTA) that redirects users to 'Join our Community' page.

Also, this page can benefit from SSR for SEO. What do you guys thing?

Finally, I would like to be a part of this revamp, if you find it alright. I'm a front-end React dev from India.

**Comment by lukas-kasticky** [comment]
https://www.figma.com/file/UAuzPXadk1D5Wem0c8nXwq/Marketing-Site-Copy

**Comment by lukas-kasticky** [comment]
https://www.figma.com/file/UAuzPXadk1D5Wem0c8nXwq/Marketing-Site-Copy

**Comment by lukas-kasticky** [comment]
@ranka23 

> * Why join our community?
> * What's in it for team members?

The homepage explains that devs get paid in coins for contributing. Maybe there should be a CTO to join the community.

> * What's next and exciting? - Perhaps, add the roadmap that is in discussion on Slack, when it's ready.

Great idea!

**Comment by ranka23** [comment]
Had a look at the Figma link. The designs look good.

Suggestions:
- You can have the cards (with links and descriptions) in 2 or 3 columns for desktop. So, users needn't scroll as much.
- I'm not a designer but I've scratched up something. People prefer numbers and so thought we can highlight those. Not sure what are the exact figures. The ones in the image are placeholders.

Also, in the caption Explore ways... you can mention about earning coins.
"Explore ways to get involved, **earn coins** and stay up-to-date with the latest announcements and events."


![stats](https://user-images.githubusercontent.com/35439798/99139714-3783cd80-2661-11eb-9ba2-f70fdaeb4e36.jpg)

**Comment by lukas-kasticky** [comment]
@ranka23 I shared your comment in Slack. The only problem we have with dynamic data like these stats is that we would have to update them frequently if we don't want more requests on the client side.

**Comment by ranka23** [comment]
@lukas-kasticky Alright. Thanks for the update.

**Comment by kristykjlee** [comment]
This has been moved to the Design Repository
