### ISSUE TITLE
Static Teams Page

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Website#503]
https://www.figma.com/file/ChyT88EmP2Rmzx35I9erCL/Marketing-Site?node-id=1278%3A979

Add a link to the Teams page in the top navigation. Include static data for now until we hook everything up to the API to help us organize into teams. 

<img width="669" alt="Screen Shot 2020-11-05 at 7 38 59 PM" src="https://user-images.githubusercontent.com/8547538/98323428-98930d80-1f9e-11eb-9d8d-80b1fbaff5b3.png">

**Comment by itsnikhil** [comment]
Taking this
