### ISSUE TITLE
Change leaderboard's default filter

### ISSUE THREAD

**Issue by angle943** [thenewboston-developers/Website#515]
![Screen Shot 2020-11-05 at 10 26 53 PM](https://user-images.githubusercontent.com/5943963/98333801-62618800-1fb6-11eb-85da-4d53dc5a3672.png)

Currently, when you go to the leaderboard page, it defaults to the `All` feature. Change this such that it defaults to `7d`

**Comment by dahelg** [comment]
@angle943 Could you assign this to me, please?

**Comment by johnjacobkenny** [comment]
@dahelg I don't mean to undercut you, but I think the line to change is [here](https://github.com/thenewboston-developers/Website/blob/223e5750fbcbcd7d5af0130541f526b5a3a117b0/src/containers/Leaderboard/index.tsx#L34)

**Comment by dahelg** [comment]
@johnjacobkenny And this is why I ask before doing any work in parallel to anyone else... We should respect that every work takes some time. ✌️

**Comment by johnjacobkenny** [comment]
@dahelg Yep :smiley:
