### ISSUE TITLE
[Desktop Browser] Download button/link clickable beyond the button

### ISSUE THREAD

**Issue by Utkarsh-Patel-13** [thenewboston-developers/Website#527]
The download link spans beyond the download button.

![recording](https://user-images.githubusercontent.com/30389481/98343270-9761ef00-2037-11eb-8c0e-11aff323b3c7.gif)

**Comment by whitelionx** [comment]
I will fix it quickly :)

**Comment by thesanjeevsharma** [comment]
@angle943 Verified! 👍

**Comment by whitelionx** [comment]
Fixed in #537
