### ISSUE TITLE
Following Devices And Browsers Website Not Loading 

### ISSUE THREAD

**Issue by webdeveloperswj** [thenewboston-developers/Website#534]
**Bug Description**
Website Not Open Following Devices And Browsers

**Steps to Reproduce**
1.Following Devices And Browsers Go through

2) Websites not open 
Source URL: https://thenewboston.com/
| Device | iPad 4 |
| Browser | Tablet_safari |
| Operating System | iOS 7.0 |
| Resolution | 1536 x 2048 px |
| Screen size | 9.7 in - 5.8 x 7.8 in |
| Viewport | 768 x 1024 dp |
| Aspect Ratio | 4 : 3 |

3)Websites not Open
Source URL: https://thenewboston.com/
| Device | iPhone 6S Plus |
| Browser | Mobile_safari |
| Operating System | iOS 9.0 |
| Resolution | 1080 x 1920 px |
| Screen size | 5.5 in - 2.7 x 4.8 in |
| Viewport | 414 x 736 dp |
| Aspect Ratio | 16 : 9 |

screen shot :- https://prnt.sc/vegvos

4)Website not open
Source URL: https://thenewboston.com/
| Device | iPhone 6S |
| Browser | Mobile_safari |
| Operating System | iOS 9.0 |
| Resolution | 750 x 1334 px |
| Screen size | 4.7 in - 2.3 x 4.1 in |
| Viewport | 375 x 667 dp |
| Aspect Ratio | 16 : 9 |

screen shot :- https://prnt.sc/vegy1z

5)Website not open
Source URL: https://thenewboston.com/
| Device | iPhone 6 Plus |
| Browser | Mobile_safari |
| Operating System | iOS 8.0 |
| Resolution | 1080 x 1920 px |
| Screen size | 5.5 in - 2.7 x 4.8 in |
| Viewport | 414 x 736 dp |
| Aspect Ratio | 16 : 9 |

screen shot:-https://prnt.sc/vegzlb

6)Website not open
Source URL: https://thenewboston.com/
| Device | iPhone 6 |
| Browser | Mobile_safari |
| Operating System | iOS 8.0 |
| Resolution | 750 x 1334 px |
| Screen size | 4.7 in - 2.3 x 4.1 in |
| Viewport | 375 x 667 dp |
| Aspect Ratio | 16 : 9 |

screen shot:-https://prnt.sc/veh1o5

7)Website not open
Source URL: https://thenewboston.com/
| Device | iPhone 5S |
| Browser | Mobile_safari |
| Operating System | iOS 7.0 |
| Resolution | 640 x 1136 px |
| Screen size | 4.0 in - 2.0 x 3.5 in |
| Viewport | 320 x 568 dp |
| Aspect Ratio | 16 : 9 |
screen shot:-https://prnt.sc/veh37o

8)Website not open
Source URL: https://thenewboston.com/
| Device | iPad Air 2 |
| Browser | Tablet_safari |
| Operating System | iOS 8.0 |
| Resolution | 1536 x 2048 px |
| Screen size | 9.7 in - 5.8 x 7.8 in |
| Viewport | 768 x 1024 dp |
| Aspect Ratio | 4 : 3 |

screen shot:-https://prnt.sc/veh6yc

9)Website content not showing only scrolling following device
Source URL: https://thenewboston.com/
| Device | iPad Air |
| Browser | Tablet_safari |
| Operating System | iOS 7.0 |
| Resolution | 1536 x 2048 px |
| Screen size | 9.7 in - 5.8 x 7.8 in |
| Viewport | 768 x 1024 dp |
| Aspect Ratio | 4 : 3 |

screen shot:-https://prnt.sc/veharr

10)Website not open
Source URL: https://thenewboston.com/
| Device | iPad Mini 3 |
| Browser | Tablet_safari |
| Operating System | iOS 8.0 |
| Resolution | 1536 x 2048 px |
| Screen size | 7.9 in - 4.7 x 6.3 in |
| Viewport | 768 x 1024 dp |
| Aspect Ratio | 4 : 3 |

screen shot:-https://prnt.sc/vehddt

11)Website not open
Source URL: https://thenewboston.com/
| Device | iPad Mini 2 |
| Browser | Tablet_safari |
| Operating System | iOS 7.0 |
| Resolution | 1536 x 2048 px |
| Screen size | 7.9 in - 4.7 x 6.3 in |
| Viewport | 768 x 1024 dp |
| Aspect Ratio | 4 : 3 |

screen shot:-https://prnt.sc/vehetf

12)Website not open
Source URL: https://thenewboston.com/
| Browser | Yandex 14.12 |
| Operating System | Windows 10 |
| Resolution | 1920x936 |

screen shot:-https://prnt.sc/vehhx4

13)Website not open
Source URL: https://thenewboston.com/
| Browser | Safari 5.1 |
| Operating System | Windows 10 |
| Resolution | 1920x936 |

14)Website not open
Source URL: https://thenewboston.com/
| Browser | Yandex 14.12 |
| Operating System | OS X Mojave |
| Resolution | 1920x936 |
screen shot :-https://prnt.sc/vehn4v

15)website not open
Source URL: https://thenewboston.com/
| Browser | Yandex 14.12 |
| Operating System | OS X High Sierra |
| Resolution | 1920x936 |
screen shot:- https://prnt.sc/vehow9

**Expected behavior**
Website supports mentioned  Devices And Browsers.

**Actual behavior**
Websites not supports mentioned Devices And Browsers.

**Comment by singh-sarabjeet** [comment]
I used free tiered BrowserStack to analyse a couple of these and all of them had the same error
![image](https://user-images.githubusercontent.com/11057104/98581641-cacaa500-22e7-11eb-8e78-06d096f80325.png)
I'm not familiar with the exact code behind it but will try to understand and fix it.

**Comment by amarjeet987** [comment]
@singh-sarabjeet any update on this issue?

**Comment by accessdeniedIT** [comment]
https://reactjs.org/docs/javascript-environment-requirements.html

**Comment by singh-sarabjeet** [comment]
@amarjeet987 I used free tiered BrowserStack which doesn't allow me to debug and I don't have the physical devices to work with.
