### ISSUE TITLE
[Internet Explorer] Website Not Loading

### ISSUE THREAD

**Issue by webdeveloperswj** [thenewboston-developers/Website#536]
**Bug Description**
Website not open In internet Explorer

**Steps to Reproduce**
1. Go to 'IE' (internet Explorer)
2.Enter Following Url "https://thenewboston.com/" 

**Expected behavior**
Website supports Every Browser 

**Actual behavior**
Website not supports internet explorer

**Screenshots/Recordings**
https://prnt.sc/vejidh

Source URL: https://thenewboston.com/
| Browser | Ie 11.0 |
| Operating System | Windows 10 |
| Resolution | 1920x880 |

**Comment by zinoadidi** [comment]
I will fix this

**Comment by thesanjeevsharma** [comment]
@webdeveloperswj @angle943 I think this issue is a duplicate of #211

**Comment by zinoadidi** [comment]
#542 Pull request submitted

**Comment by thesanjeevsharma** [comment]
Closing because this is a duplicate issue.
