### ISSUE TITLE
Teams page is not mobile responsive

### ISSUE THREAD

**Issue by thesanjeevsharma** [thenewboston-developers/Website#547]
**Bug Description**
Teams page is not mobile responsive.

**Steps to Reproduce**
1. Go to [https://thenewboston.com/teams](https://thenewboston.com/teams) on any mobile device.

**Expected behavior**
Should be responsive on all screen sizes

**Actual behavior**
It is not responsive on mobile screens

**Screenshots/Recordings**

Checked in Browser
![image](https://user-images.githubusercontent.com/29539278/98371975-11f43400-2063-11eb-829a-053f116f8368.png)

Checked on Phone 
![Teams](https://user-images.githubusercontent.com/29539278/98372027-22a4aa00-2063-11eb-9c8b-45cd90f1d959.jpeg)

**OS and Browser**
 - OS: Android 10, Windows 10
 - Browser: Chrome, Firefox

**Account Number**
644cdaf382c1f711fb05fb4328409a62713ecc7a3e83fa07427cc3539a8a23ac

**Comment by mersimoski** [comment]
Hi, i would like to take this, thanks.

**Comment by mersimoski** [comment]
![image](https://user-images.githubusercontent.com/62712311/98413381-d1ec7b80-2079-11eb-93d8-7c20e10fea46.png)

**Comment by GameOverTM0289** [comment]
I want to participate fixing this :D

**Comment by jeremygblake** [comment]
I just used the Firefox mobile view option and it still is not responsive to the size of a mobile application.

**Comment by BakungaBronson** [comment]
Hey guys. I'm willing to help out on this issue if an extra hand is needed.

**Comment by Linzo99** [comment]
#566 : **Fixed responsiveness for teams page**

**Comment by thesanjeevsharma** [comment]
I'll fix this. 😄 Change in design, we need vertical cards.

**Comment by BakungaBronson** [comment]
I was thinking the same thing. On smaller devices, the text to the side just can't fit well without becoming too small, why not just put the text below the team member photo instead.

**Comment by ArinzeJeffrey-droid** [comment]
I'd like to take this.
