### ISSUE TITLE
Last updated date for Docs

### ISSUE THREAD

**Issue by Niekon01** [thenewboston-developers/Website#549]
The Docs need to have a last updated date so that people who read them can know if they are up-to-date with the latest information.

**Comment by mofodox** [comment]
@Niekon01 I can provide the design for this.

**Comment by mofodox** [comment]
Here's the updated design Figma link:
https://www.figma.com/file/PIFGlnOLkEyTIEX2IPH1tw/Marketing-Site-%E2%80%93-TNB?node-id=55%3A0

@Niekon01 

As per the discussed: @buckyroberts @kristykjlee

**Comment by mofodox** [comment]
Here's my account number: ddef8a7ea0d98f8605703102f5b25e587d612ba7917afc1c9eb0ee904ae181c0

**Comment by kristykjlee** [comment]
@buckyroberts Has this been paid for?

**Comment by Rajputusman** [comment]
@mofodox Paid for the design

**Comment by CNFloss** [comment]
I've digging through the code and I believe that I can implement this.  This will be my first contribution should I just make a pull request or ask to have it assigned?

**Comment by CNFloss** [comment]
@kristykjlee I forgot to tag someone in my message above, could you offer some guidance?

**Comment by CNFloss** [comment]
@thesanjeevsharma I sent you a DM on slack but I'll post this here in case you see it first.   

Is this feature strictly for the main Guide, or is this supposed to be extended out to the account manager guide, deployment guides, style guide and API sections too?  And lastly should I just use today's date or is their a date object somewhere that I should be using?

**Comment by thesanjeevsharma** [comment]
Hey! It should be on every section. Since different sections can be updated at different times.
Also, you can write today's date for now. Later on, when someone makes a change in docs they'll update that date.

**Comment by CNFloss** [comment]
Hey I just want to remind you guys that the "paid" label was left over from the design just in case the payment team sees that and gets confused, no rush. I am excited my first contribution got merged though! Woohoo!  @thesanjeevsharma
