### ISSUE TITLE
[BUG] Scrolling freezes on Safari

### ISSUE THREAD

**Issue by Hristijan95** [thenewboston-developers/Website#55]
I've been reading the documentation on thenewboston.com and I've noticed that the scrolling freezes from time to time.
I scroll, then I stop to read a paragraph for example and when I try to scroll some more, I can't, I try scrolling up/down multiple times and after a 3-4 seconds it unfreezes and it instantly scroll to the last scroll you've entered.

I tried hard to find a reproducing scenario, but I can't, it's super random.
I didn't test in details on other browsers, but I wasn't able to reproduce it on Chrome (at least in the time I've tried)
My Safari version is: `13.1.1 (15609.2.9.1.2)`

**Comment by whitehox** [comment]
Been trying to recreate this bug with same version of Safari and I haven't succeeded. has this been fixed?

**Comment by buckyroberts** [comment]
Updated the entire layout and scrolling logic so hopefully this is fixed
