### ISSUE TITLE
[Feature Request] Tasks should be sortable by time and coins

### ISSUE THREAD

**Issue by thesanjeevsharma** [thenewboston-developers/Website#550]
Right now the tasks page([https://thenewboston.com/tasks/All](https://thenewboston.com/tasks/All)) doesn't have sorting.

Users should be able to sort tasks by `time` and `coins`.

**Comment by angle943** [comment]
@kristykjlee

**Comment by kush-daga** [comment]
If it's okay, can I look into this? I might not be as experienced but I would love to give this a shot and try adding this feature.

**Comment by kristykjlee** [comment]
> If it's okay, can I look into this? I might not be as experienced but I would love to give this a shot and try adding this feature.

@kush-daga you can take this issue

**Comment by kush-daga** [comment]
Great! Is there any design resource I need to use for adding the "sort" menu option and label? @kristykjlee

**Comment by kush-daga** [comment]
I have added the logic part of things in the PR #616 , just waiting on some UI element to display the Sort By functionality on the page. @thesanjeevsharma @kristykjlee any suggestions on how should I display the sort by on the screen, should I just use a flat nav list or something similar to the tags?

**Comment by kush-daga** [comment]
Updated the PR #616 With the latest changes and code. @kristykjlee Do review the changes
![image](https://user-images.githubusercontent.com/40840079/98935005-e365d580-2508-11eb-8147-4c1f3496cb99.png)
Here is a screenshot for reference.
