### ISSUE TITLE
Typo in Root Account file description

### ISSUE THREAD

**Issue by piyusharorawork** [thenewboston-developers/Website#551]
**Bug Description**
In current documentation it is mentioned that the description of Root Account file as  A historic record (snapshot) of all account balances at a given **coin** in time instead of given **point** in time 

![image](https://user-images.githubusercontent.com/31386968/98389584-445d5b80-207a-11eb-9d8f-201950ae8738.png)

**Comment by JonasPik** [comment]
I will take a look at this, Thanks.

**Comment by theCow61** [comment]
Am I doing this correctly by doing the PR and referencing this issue? I haven't really done much contributions on github before.

**Comment by LunarDeveloper** [comment]
I've found a couple references to "a coin in time". Was this possibly the intentional phrasing?

**Comment by piyusharorawork** [comment]
@LunarDeveloper even I think the same . I guess since they renamed the term **points** to **coins**  during bulk replacement for documentation , this mistake might have happened .

**Comment by thesanjeevsharma** [comment]
Fixed with #556 

@LunarDeveloper @piyusharorawork Thanks for letting us know. I'll check and create a separate issue for this. 👍

**Comment by piyusharorawork** [comment]
@thesanjeevsharma I have found few more occurences and created PR for this as well incase .
