### ISSUE TITLE
[Design] No Margin between Task Left Menu

### ISSUE THREAD

**Issue by officialabdulrehman** [thenewboston-developers/Website#581]
There is no gap between 2 tabs of Task Left Menu. ( Chrome )
Makes them look smudged if the current tab and next tab are the 2 consecutive tabs.

![margin](https://user-images.githubusercontent.com/33157081/98438630-7c61ae80-210d-11eb-8f2c-b5ea4e16c77b.png)

Giving 2px margin-bottom to [ .FlatNavLinks__option ] makes it look better:

![margin1](https://user-images.githubusercontent.com/33157081/98438614-5cca8600-210d-11eb-8a0d-425de56bbc01.png)

Account Number: cd2400e0402fd081b2f71d08a9334e56d876eb589e096b6a0b8a6e4ac20a73c3

**Comment by whitelionx** [comment]
I will fix it quickly

**Comment by whitelionx** [comment]
Fixed the issue, please review and merge.
