### ISSUE TITLE
Mobile drop-down menu blocking logo & icon during animation

### ISSUE THREAD

**Issue by btk** [thenewboston-developers/Website#582]
**Bug Description**
Mobile drop-down menu blocking logo & icon during animation. In general this might be a design desicion, but seems like a bug. 

**Steps to Reproduce**
1. Go to any route with TabNav on a mobile device or smaller viewport
2. Toggle the menu by clicking the hamburger icon.
3. See the dropdown div is clipping the header.

**Expected behavior**
I would expect the menu to never clip and position itself right under the `TabNav`

**Actual behavior**
Dropdown div is clipping the header.

**Screenshots/Recordings**
Before: 
https://drive.google.com/file/d/1xogf0CqBCmeKV0DfsNW-_xJ-O4Qpr-YL/view
After:
https://drive.google.com/file/d/1hgv8cfYySEJrSsAuHs4pn9DTR5ML7rJZ/view

**OS and Browser**
 - OS: any
 - Browser: any, smaller viewports

**Additional context**

**Account Number**
Your account number where the reward coins for this bug bounty will be sent (pending review and approval).

[How to Create an Account](https://thenewboston.com/account-manager/create-an-account)

**Comment by btk** [comment]
If this was not a design desicion #584 resolves this.

**Comment by nparoski** [comment]
I will take this issue.

**Comment by Hristijan95** [comment]
I had to revert the code back from @btk because it was causing the menu break on the desktop, so I am reopening this issue.
