### ISSUE TITLE
[Design] Avatar Icon not Centered.

### ISSUE THREAD

**Issue by officialabdulrehman** [thenewboston-developers/Website#583]
Avatar circle has more gap on bottom than top.

![avatar](https://user-images.githubusercontent.com/33157081/98438944-b8960e80-210f-11eb-95dc-e2b282e5fdd9.png)

Adding margin-top: 7px to [ .LeaderboardContributor__user-avatar ] make it look better:

![avatar2](https://user-images.githubusercontent.com/33157081/98438971-014dc780-2110-11eb-83ff-135cf06dfedb.png)

**Comment by thesanjeevsharma** [comment]
@officialabdulrehman I don't think this is meant to be centered! If you look at the contributor on position 3, there are more tasks as compared to 1 and 2. This card will expand in height and hence avatar will be placed differently for each contributor. We wanna avoid that. 

Let's get @kristykjlee's view on this.
