### ISSUE TITLE
Dropdowns are not keyboard accessible

### ISSUE THREAD

**Issue by lapstjup** [thenewboston-developers/Website#587]
**Bug Description**
The Get Started, Community and More dropdowns are not keyboard accessible.

**Steps to Reproduce**
Scenario 1:-
1. Go to [thenewboston](https://www.thenewboston.com/)
2. Click on Get Started or any other dropdown text.
3. Press Tab Key

Scenario2:-
1. Go to [thenewboston](https://www.thenewboston.com/)
2. Press tab key until you are over any of the dropdown text, press enter/space and press tab key again.

**Expected behavior**
The list of items of dropdown should get focus

**Actual behavior**
The list items do not get focused

**Screenshots/Recordings**
[Recording](https://drive.google.com/file/d/14BC82nRqS6t_F9aH7C6Ke_SS8JpjiYAP/view?usp=sharing)

**OS and Browser**
 - OS: [e.g. macOS]
 - Browser [e.g. Chrome, Firefox, Safari]

**Additional context**
Also multiple dropdowns can be opened at the same time using enter/space. This can be also be corrected in this same issue.

**Comment by prajwalkulkarni** [comment]
I went through this issue and made some research and caught hold of a function that might be of use. I was unsure of the implementation, so here's the code so far. Please check if it works.
`
const useKeyPress = function (targetKey: any) {  //Not sure where to use this function.
    const [keyPressed, setKeyPressed] = useState(false);
    function downHandler(key: any) {
      if (key === targetKey) {
        setKeyPressed(true);
      }
    }
    const upHandler = (key: any) => {
      if (key === targetKey) {
        setKeyPressed(false);
      }
    };

    React.useEffect(() => {
      window.addEventListener('keydown', downHandler);
      window.addEventListener('keyup', upHandler);
      return () => {
        window.removeEventListener('keydown', downHandler);
        window.removeEventListener('keyup', upHandler);
      };
    });
    return keyPressed;
  };
 `

**Comment by nparoski** [comment]
Since this is still unsolved I'll give it a go.

**Comment by mbdteam9** [comment]
Hi @lapstjup, im sorry not sure about the complex code others have suggested. 

I just know how to use fake buttons(keyboard acessible) , by making use of tabindex=0. 

If it dont work sorry, im too new to web dev.

**Comment by lapstjup** [comment]
Hey @mbdteam9 No need to be sorry for anything. You can always raise a PR for a fix you think can work and post review if we find it to be fit for inclusion, we will merge it 😄.

**Comment by SNikhill** [comment]
Greetings,
The dropdowns are accessible via the tab key, it is just that their styling doesn't change and hence, they appear to be non-accessible. 
Trying opening the website and press tab two times followed by an enter press. The Get Started Dropdown will open up.

Regards
@SNikhill

**Comment by nparoski** [comment]
> Greetings,
> The dropdowns are accessible via the tab key, it is just that their styling doesn't change and hence, they appear to be non-accessible.
> Trying opening the website and press tab two times followed by an enter press. The Get Started Dropdown will open up.
> 
> Regards
> @SNikhill

Not really since you cant navigate inside of them once they are open, hopefully i will make pr tonight or tommorow night.

**Comment by SNikhill** [comment]
Oh, I just saw the same. Well please, go ahead with the fix. :)
