### ISSUE TITLE
Tasks page not reflecting new issues from GitHub

### ISSUE THREAD

**Issue by BakungaBronson** [thenewboston-developers/Website#598]
**Bug Description**
The Tasks page https://thenewboston.com/tasks/All is not showing new open issues coming in from GitHub https://github.com/thenewboston-developers/Website/issues. 

**Steps to Reproduce**
1. Go to 'https://thenewboston.com/tasks/All'
2. See error

**Expected behavior**
The https://thenewboston.com/tasks/All page gets the issues as they come in.

**Actual behavior**
Shows older tasks and leaves out newer ones yet the new issues are being received as seen in the network tab under the developer tools in the issue.
![issues_not_shown](https://user-images.githubusercontent.com/51344005/98449700-b8fdcc00-2146-11eb-994b-ff01f89893f8.PNG)

**OS and Browser**
 - OS: Windows 10
 - Browser: Chrome, Firefox

**Additional context**
It also applies to the https://thenewboston.com/tasks/Website, https://thenewboston.com/tasks/Account-Manager.

**Account Id:**
dfddf07ec15cbf363ecb52eedd7133b70b3ec896b488460bcecaba63e8e36be5

**Comment by thesanjeevsharma** [comment]
@BakungaBronson I checked this and found that what you're saying is partially true. It's fetching all the issues but only some are displayed. But under the hood, we are filtering issues that have an amount associated with them and no PR has been created to solve those issues.

This is not an issue. Closing.
