### ISSUE TITLE
Vertical line(blinking cursor) everywhere when clicked on the website on Chrome Browser

### ISSUE THREAD

**Issue by manishram** [thenewboston-developers/Website#614]
**Bug Description**
Most of the texts on the website when clicked gives a vertical line(blinking cursor).
This is a bug that is not only in the link I provided in the "Steps to Reproduce" but the other several pages are also affected by this.
This bug can be reproduced in "Chrome". The website is working well on Mircosoft Edge and Mozilla Firefox as intended.

**Steps to Reproduce**
1. Go to https://thenewboston.com/tasks
2. Click on any of the navigation link "All", "Account-Manager", "Bank" or any other place
3. You will see the blinking cursor like happens when you click on the input box where you to type something.

**Expected behavior**
There should be no blinking cursor when clicked.

**Actual behavior**
There is a blinking cursor when clicked.

**Screenshots/Recordings**
![bug-issue-x](https://user-images.githubusercontent.com/22790904/98459857-dbcec580-21c4-11eb-9a60-003e60312a61.gif)

**OS and Browser**
 - OS: Windows 10
 - Browser: Chrome

**Additional context**
Many pages are affected by this bug in Google Chrome Browser.

**Account Number**
0f92e975101eb96cea80dce430d74efd3172fa229377818d467ded85dcf2ab6c

**Comment by imcybergeek** [comment]
I think this is a client-side issue.
There's an option called "Navigate pages with a text cursor" in Accessibility settings, you'll need to disable this option.

Chrome Settings ​​--> Advanced --> Accessibility.
See if this fixes the issue and let me know.

**Comment by manishram** [comment]
Seems like there is some problem with my Chrome Browser because the same behavior can be observed in all other websites.

**Comment by manishram** [comment]
So I was using ScreenToGif Application to record my previous PRs working. This tool has a shortcut F7 to start recording and funny thing is that to turn on or off "Navigate pages with a text cursor" in chrome, there is shortcut F7 as well.
