### ISSUE TITLE
Blank page if chapter is not added in the documentation URL

### ISSUE THREAD

**Issue by manishram** [thenewboston-developers/Website#615]
**Bug Description**
When the user goes to https://thenewboston.com/guide/ link it shows a blank white page.

**Steps to Reproduce**
1. Go to https://thenewboston.com/guide/
2. There is a white blank page

**Expected behavior**
It should redirect to https://thenewboston.com/guide/introduction

**Actual behavior**
There is a white blank page

**Screenshots/Recordings**
![issue-2](https://user-images.githubusercontent.com/22790904/98460271-f30fb200-21c8-11eb-8a94-40a1e7a2d2b6.JPG)

**Account Number**
0f92e975101eb96cea80dce430d74efd3172fa229377818d467ded85dcf2ab6c

**Comment by thesanjeevsharma** [comment]
It's a quick fix! I'll do it. 👍 Thanks for letting us know.

**Comment by rahulkiller104** [comment]
@thesanjeevsharma I am new to contributing to the Open-source project. This small fix will be my good starting PR. :) Thank you
