### ISSUE TITLE
Docs need some language/grammatical fixes

### ISSUE THREAD

**Issue by lapstjup** [thenewboston-developers/Website#619]
**Bug Description**
There are not single but multiple instances of point renamed to coin where the meanings gets obscured. Also some grammatical nuances here and there.

**Places to fix as per my proof reading (Bold are incorrect and italics (if present) are correct) on the below routes**
1. **/guide/root-account-file :**
	 The root account file is a historic snapshot of all account balances at a given **coin** _point_ in time.
	 However, since Bucky had already verified the first transaction and also made a copy of the account file at that **coin** _point_ in time

2. **/guide/transaction-fees :**
	A very simple UI that Amy may see at that **coin** _point_ might look like this:

3. **/guide/banks :**
When users first download account manager applications and create their accounts, they will then select a bank **in** which they wish to use.

4. **/guide/confirmation-validators :**	•	
    1. This is the flattened representation of all account balances at a given **coin** _point_ in time
    2. Value representing the message hash of the primary **validators** _validator’s_ most recently verified block
    3. Beginning with the previous primary **validators** _validator’s_
	 
5. **/style-guide/css** - 
	1. if the naming **won't** won't be too confusing
	2. One of the pain-**coins** _points_ of BEM is the ambiguity
	3. This **coin** _point_ probably deserves a new section:
	4. Continuing on with the previous **coin** _point_

**Comment by taneishamitchell** [comment]
👋 @lapstjup I'd be willing to work on this. I'll wait for a moderater to acknowledge

**Comment by MuathAlhayani** [comment]
I am willing to work on this? If available.

**Comment by lapstjup** [comment]
@taneishamitchell and @MuathAlhayani - it seems that already 2 PRs are available for this. 
You can check out the other issues.
Thanks
