### ISSUE TITLE
Add title on some pages

### ISSUE THREAD

**Issue by bossajie** [thenewboston-developers/Website#626]
**Suggestion**
I am suggesting that it's much better if we add some [Title](https://www.w3schools.com/TAGs/tag_title.asp) on some/every page depends on what is the web page is about.

Currently, I don't see the title of most pages on the website is changing, it's just **thenewboston**.

For example,
If I am on https://thenewboston.com/download,
we can set the title to **thenewboston | Download**
If on https://thenewboston.com/guide/introduction, **thenewboston | Documentation***

**Account Number**
6954f2a530185bc6a0f100dbd8cf2b176fd2273b1697a613130d8f261f2d7590

**Comment by Paul-Taiwo** [comment]
I could work on this.
