### ISSUE TITLE
Team Page - Member Updates

### ISSUE THREAD

**Issue by kristykjlee** [thenewboston-developers/Website#627]
- [ ] Add Steve Heddens GitHub name on his team card. GitHub: SteveHedden
- [ ] Add **Team Lead** tag on David Yaps card. Update David Yaps title from UI/UX Designer to Design Lead. 
- [ ] Add Khairul Akmal as a team member. Role: UX/UI Designer,  GitHub: mofodox, Slack: Khairul Akmal
- [ ] Add Sush as a team member. Role: UX/UI Designer, GitHub: nsushman, Slack: Sush 
- [ ] Add Manish Ram as a team member. Role: UX/UI Designer, GitHub: manishram, Slack: Manish
- [ ] Add Pulkit Bajaj as team member. Role: Marketing Director, Slack: Pulkit Bajaj, add **Team Lead** to card

**Comment by jaelee0409** [comment]
I'll work on this!

**Comment by nsushman** [comment]
Hey!
Khairul and Sush's titles seem to have been set incorrectly. Could you please review this one?
@lapstjup @jaelee0409 

![image](https://user-images.githubusercontent.com/18399270/98536058-288dcb80-22ad-11eb-8c20-56c39dea6317.png)

**Comment by lapstjup** [comment]
@nsushman Thanks for bringing this to my notice. Identified the cause. Discussing the same with team.
