### ISSUE TITLE
Prevent Horizontal scrolling when on mobile view

### ISSUE THREAD

**Issue by angle943** [thenewboston-developers/Website#63]
![Image from iOS](https://user-images.githubusercontent.com/5943963/87833571-045d3900-c83d-11ea-89d1-768252d650f2.png)

when scrolling up and down, if you scroll a little bit to the sideways, it does this annoying thing.

**Comment by guptstagram** [comment]
Give **overflow-x: hidden;** to class **right**.

`.right{
    overflow-x:hidden;
  }`

**Comment by buckyroberts** [comment]
Closing, working on updating the entire UI
