### ISSUE TITLE
Team Lead tag's text is misaligned

### ISSUE THREAD

**Issue by thesanjeevsharma** [thenewboston-developers/Website#645]
**Bug Description**
Team Lead tag's text is misaligned.

**Steps to Reproduce**
1. Go to: [Teams](https://thenewboston.com/teams)

**Expected behavior**
It should be vertically and horizontally  center aligned.

**Screenshots/Recordings**
![image](https://user-images.githubusercontent.com/29539278/98538252-7c4de400-22b0-11eb-8644-ff86a20b879b.png)

**OS and Browser**
 - OS: Android, iOS
 - Browser: Firefox, Safari

**Additional context**
Solution: 
flex it, align and justify center

**Comment by whitelionx** [comment]
Should be resolved at #647
