### ISSUE TITLE
teams.json ordering is not correct

### ISSUE THREAD

**Issue by lapstjup** [thenewboston-developers/Website#648]
**Bug Description**
The ordering of team members in teams.json is not as per their contributor's id. Also there are some missing contributor ids. Need to order these entries as per the id's mentioned for consistency and prevent id overlapping issues during PRs. 

**Note**
 - If there's a miss (like 14), make sure that team member with id 15 changes to 14 , 16 changes to 15 and so on.
 - If there is a clash, chose any one to resolve it. 

We want to show the members in the same order on the [teams page](https://www.thenewboston.com/teams ) as we have been showing till now.

**Comment by manishram** [comment]
@lapstjup I am working on it. Thanks

**Comment by lapstjup** [comment]
Closing this since fix is done for the same directly in development branch.
