### ISSUE TITLE
[Feature Request] Additional task label filters

### ISSUE THREAD

**Issue by jamessspanggg** [thenewboston-developers/Website#658]
Currently, the task label filters only contain the following: `bug`, `design`, `discussion`, `documentation`, `engineering` and `suggestion`.
<img width="1395" alt="Screen Shot 2020-11-10 at 12 05 45 AM" src="https://user-images.githubusercontent.com/32864116/98565355-7c69d600-22e8-11eb-802b-e02e3dec1c50.png">

Would be good to have the `In Progress` filters so that external contributors can easily filter out and locate tasks that can be tackled.

If the feature request is okay, I'm happy to work on it :)

**Comment by jamessspanggg** [comment]
Additionally, would be good if the tasks with assignees are not included as well.

**Comment by lapstjup** [comment]
@jamessspanggg My take - The website ensures that you know the **types** of the tasks being worked on. But it's progress is a transient behaviour which I think is good if left to github labels. Same goes for assignee - it's a very dynamic entity.

**Comment by jamessspanggg** [comment]
@lapstjup thanks for the explanation. Agreed. Should I close this issue?

**Comment by lapstjup** [comment]
Yes for now let's close it. When an api is fully functional, this can be brought upon then.
