### ISSUE TITLE
Filter by Coins and Filter by Created Date for /tasks/all

### ISSUE THREAD

**Issue by ranka23** [thenewboston-developers/Website#664]
How about adding additional filters to the Tasks page?

Filter by reward (coins) and time (created_at). Can be a value adding feature.

In fact, I've already created both the filters and added them to my localhost. So, all that is really required now is a code review, tests and voila we have a new feature in less than a day.

Let me know if it's of interest. I'll push it.

Here's a [video preview](https://gofile.io/d/GY7SyH) of the filters in action.

**Comment by Hristijan95** [comment]
@kristykjlee please take a look at this when you have the time

**Comment by officialabdulrehman** [comment]
check issue #550

**Comment by ranka23** [comment]
@officialabdulrehman I did. That is for sorting the list. This is for filtering it. Also, this is ready.

**Comment by manishram** [comment]
#616
