### ISSUE TITLE
[Job Opening] Marketing Analyst

### ISSUE THREAD

**Issue by iamsid47** [thenewboston-developers/Website#673]
Add the following job opening to the website.

***

#### Job Title
Marketing Analyst

#### Job Description
Seeking a Marketing Analyst to research user behavior, gaining partners, and executing various marketing strategies.
#### Responsibilities
- Analyze sales funnels and customer intent
- Measure the ROI of online and offline marketing campaigns
- Reports on marketing KPIs like user base, web traffic, and social media engagement
- Conduct competitive research and analyze benchmarking data
- Recommend website and campaign optimizations
- Research and implement marketing tools to support our promotional projects (automation software, social media scheduling, etc)

#### Technology Requirements
- Strong understanding of Blockchain and our project architecture
- Strong analytical and research skills

#### Reports To
- First Name: Siddhesh
- Slack Name: Siddhesh Kulthe

#### Pay
- 2,800 coins/day

#### Application channels
- Slack - Message Siddhesh Kulthe
- LinkedIn - Connect & Message Siddhesh Kulthe (https://linkedin.com/in/siddheshkulthe)
- Twitter
- Reddit

**Comment by itsnikhil** [comment]
taking this
