### ISSUE TITLE
"Join the Community" heading in /social

### ISSUE THREAD

**Issue by ddyakov** [thenewboston-developers/Website#686]
**Bug Description**
It is not an actual bug, as it is more a styling problem.

**Steps to Reproduce**
1. Go to 'https://thenewboston.com/social'.
2. Toggle the screen to a mobile device resolution (e.g. from Chrome dev tools).
3. "Join the Community" is not aligned in the center.

**Expected behavior**
The heading should be centered the same way as on a tablet/desktop resolution.

**Actual behavior**
The heading is actually centered (because the parent div has 'justify-content: center;'), however, the font size is too much and it's making it look as if it is left aligned.

**Screenshots/Recordings**
![image](https://user-images.githubusercontent.com/11051204/98672776-9e9a3d00-2356-11eb-878f-e79315c364fd.png)

**OS and Browser**
 - Windows 10
 - Chrome

**Additional context**
The font-size might have to be less on mobile devices.

**Account Number**
f867dd69de4657143261b1f03f3e120e7cc4453ae8d77bce2a047d1989ef26ec

**Comment by Hristijan95** [comment]
I also noticed that the Slack, Github, Youtube... cards are not centered correctly, they are leaning a little bit more to the right.

**Comment by ddyakov** [comment]
@Hristijan95 Now that you said that, I double-checked and you are right.

**Comment by T-Whiz** [comment]
Hey guys I managed to fix this by adding text-align: center; to the Social_heading class in the css.

From
.Social__heading {
    font-size: 36px;
    font-weight: 800;
    line-height: 1.25;
    margin: 0 auto 30px;
}

To
.Social__heading {
    font-size: 36px;
    font-weight: 800;
    line-height: 1.25;
    margin: 0 auto 30px;
    text-align: center;
}

![headerfix](https://user-images.githubusercontent.com/71679719/98730514-64d33180-236a-11eb-9a57-185b2824d9bf.png)

**Comment by Hristijan95** [comment]
There are already 2 PRs opened about this issue, but both incomplete as of now.
@T-Whiz , that's great. If you fix the cards alignment as well, submit a PR and I'll close the issue.

**Comment by T-Whiz** [comment]
I opened a pr but I'm not entirely sure I did it correctly, still a noob to github 👍 

I fixed the icons too by adjusting their margins. Both the fixes are super quick
