### ISSUE TITLE
Left-Sidebar

### ISSUE THREAD

**Issue by guptstagram** [thenewboston-developers/Website#70]
If sidebar navigation overlaps the content instead of sliding it then it will look better I think because in mobile it totally slides the content. Or one option can be it should take up the whole width in the mobile device.

We can achieve the overlap thing by **position: absolute** and **some height**. And on the click of hamburger changing display or width property.

![image](https://user-images.githubusercontent.com/31503495/87844495-5bb1e680-c8db-11ea-8710-7f9bb52650f7.png)

To make the navbar **width:100%** and on the click of hamburger changing display or width property.

![image](https://user-images.githubusercontent.com/31503495/87844559-b21f2500-c8db-11ea-99d0-b312e42d453e.png)

In both the cases, I have given some **top margin** to the sidebar as **thenewboston** logo should be **visible**.

**Comment by buckyroberts** [comment]
Closed in place of https://github.com/thenewboston-developers/Website/issues/94
