### ISSUE TITLE
[Kotlin SDK] Build BankDataSource that calls Bank endpoints through HttpService

### ISSUE THREAD

**Issue by IanArb** [thenewboston-developers/Website#715]
As an SDK user,

I WANT
To be able to fetch all the available banks and also determine the level trust of the bank has.

SO THAT
I know which bank I can send transactions to.

Documentation for bank endpoints for GET and PATCH requests https://thenewboston.com/bank-api/banks

The data models and http layer are already implemented and just needs a data source class to call the endpoints.

**Comment by ztickm** [comment]
This issue should be transferred to the [relevant repository](https://github.com/thenewboston-developers/Kotlin-SDK)

**Comment by Hristijan95** [comment]
@IanArb , please reopen this issue in the relevant repository as I don't have access to move it there and Bucky is probably overloaded with messages & requests.
