### ISSUE TITLE
HTML warnings

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Website#75]
Go through each page and fix any HTML nesting warnings (usually with tables and lists)

<img width="883" alt="Screen Shot 2020-07-18 at 11 44 15 AM" src="https://user-images.githubusercontent.com/8547538/87859719-1d70f300-c8ec-11ea-86e4-4572f00cd4d4.png">

**Comment by Hristijan95** [comment]
I'm taking it if no one started it yet.
