### ISSUE TITLE
Typo in the documentation.

### ISSUE THREAD

**Issue by alexkimeu0** [thenewboston-developers/Website#756]
There's a small typo in the documentation.

![tnb](https://user-images.githubusercontent.com/61450115/98942334-e5c33200-24fe-11eb-9ec4-e9592f01a616.jpg)

**Comment by ddyakov** [comment]
I have opened a [PR](https://github.com/thenewboston-developers/Website/pull/759) for this.

**Comment by alexkimeu0** [comment]
I had already opened one.
