### ISSUE TITLE
Pkg update

### ISSUE THREAD

**Issue by awais3455** [thenewboston-developers/Website#760]
Team: [TEAM NAME]

{
  "title": [JOB TITLE],
  "isLead": [true OR false],
  "payPerDay": 2800,
  "createdDate": "2020-07-08T02:14:59.307535Z",
  "contributor": {
    "contributorId": [CONTRIBUTOR ID],
    "displayName": [DISPLAY NAME],
    "githubUsername": [GITHUB USERNAME],
    "profileImage": [PROFILE IMAGE URL (Slack or GitHub URL)],
    "slackUsername": [SLACK USERNAME]
  }
}

**Comment by Kirito129** [comment]
Can we get more details about this issue @awais3455 ?

**Comment by awais3455** [comment]
YES
