### ISSUE TITLE
extra right margin in donate-card  on mobile

### ISSUE THREAD

**Issue by rahulkiller104** [thenewboston-developers/Website#776]
**Bug Description**
extra right margin in donate-cards on mobile devices

**Steps to Reproduce**
1. Go to 'https://www.thenewboston.com/donate'
**Expected behavior**
on donate-cards margin should be equal in left-right on mobile
**Actual behavior**
on donate-cards right-margin is greater than left-right on mobile
**Screenshots/Recordings**
![Screenshot (77)](https://user-images.githubusercontent.com/56788144/99024970-bc051c00-258d-11eb-9e64-c6fb02f28747.png)

**OS and Browser**
 - OS: [e.g. Windows 10]
 - Browser [e.g. Chrome, Safari]
**Account Number**
dfddf07ec15cbf363ecb52eedd7133b70b3ec896b488460bcecaba63e8e36be5

**Comment by vectaaa** [comment]
i'll like to handle this

**Comment by rahulkiller104** [comment]
@vectaaa I have solved this issue.
