### ISSUE TITLE
Tasks & Leaderboard tabs don't show all GitHub repos

### ISSUE THREAD

**Issue by aayushi14** [thenewboston-developers/Website#780]
**Bug Description**
Tasks and Leaderboard tabs don't show all GitHub repos.

**Steps to Reproduce**
1. Go to thenewboston -> Community -> Leaderboard
2. Default on All and 7d
3. First person is DucFhamTV, click on their topmost task.
4. They have contributed to Repo: thenewboston-python-client, but this repo is not listed on the left menu.

**Expected behavior**
All 14 repos need be displayed whether they have tasks or not, have contributors or not.

**Screenshots/Recordings**
![image](https://user-images.githubusercontent.com/33564949/99025724-76b5ff80-2537-11eb-834a-fde630ac8ea2.png)
![image](https://user-images.githubusercontent.com/33564949/99026041-2db27b00-2538-11eb-83c4-9b1fa61f03f6.png)

**Comment by Hristijan95** [comment]
This will have the same problems that are being fixed at the moment in #620. Once we fix that, we can add all repos here & use the same solution for the repos with longer title.

**Comment by Hristijan95** [comment]
^same as my previous comment, but now it's in another PR - #803

**Comment by jamessspanggg** [comment]
May I know which additional repositories should be added to the tasks and leaderboard?

**Comment by jamessspanggg** [comment]
Is this issue still applicable?

**Comment by mrbusysky** [comment]
https://github.com/thenewboston-developers/Website/pull/1098

**Comment by thesanjeevsharma** [comment]
@Hristijan95 @lapstjup @aayushi14 @jamessspanggg 

I think we should close this. It doesn't make sense to show all the repos right now. If any team lead wants their repo on the website, they can create a separate issue for it like #1103.

The point is some repos are just for management and will never be added. Also, repos like Website-API are being handled internally.

**Comment by lapstjup** [comment]
@thesanjeevsharma 
![just_do_it](https://user-images.githubusercontent.com/29139815/101733245-8bf55e00-3ae4-11eb-90b3-cef6f2325872.gif)
