### ISSUE TITLE
[Feature Request] Add last updated date time to leaderboard

### ISSUE THREAD

**Issue by jamessspanggg** [thenewboston-developers/Website#786]
Since the leaderboard is based on commits to the `tasks.json`, the leaderboard may not contain the latest updated results. It would be good if the last updated date time is shown in the leaderboard.

**Comment by buckyroberts** [comment]
We are moving all the tasks/leaderboard data over to the API soon. It will fix this issue since everything will be updated close to real time (when the payments team logs the payment).
