### ISSUE TITLE
A little typo in the 'Openings' page

### ISSUE THREAD

**Issue by mahihossain** [thenewboston-developers/Website#787]
**Bug Description**
On the 'Openings' page, there is a typo.  

**Steps to Reproduce**
1. Go to 'https://www.thenewboston.com/openings/All'

**Expected behavior**
It should be 'till' or 'until'

**Actual behavior**
Now it is showing 'til'

**Account Number**
def3963e9afcdb0e7e9c00077bea51bd7233540b41eb78a384c2567986b4edf3

**Comment by ddyakov** [comment]
Btw it could be also 'til (with the single quote) :)

**Comment by mahihossain** [comment]
> Btw it could be also 'til (with the single quote) :)

Yes, that is also an option. It's really a very small issue.

**Comment by YashovardhanSingh** [comment]
Solution: [fixes #787](https://github.com/thenewboston-developers/Website/pull/794)
