### ISSUE TITLE
Incorrect Order in "Core Components Table" in Documentation Page

### ISSUE THREAD

**Issue by YashovardhanSingh** [thenewboston-developers/Website#795]
**Bug Description**
On the documentation page, https://thenewboston.com/guide/introduction , the core components table under the overview section must be in alphabetical order for ease.

**Expected behavior**
The table should be in alphabetical order.

**Actual behavior**
The table does not follow any order.

**Screenshots/Recordings**
![bandicam 2020-11-13 16-17-05-458](https://user-images.githubusercontent.com/63940326/99064291-c80fce80-25cb-11eb-87db-ae43f85bf136.jpg)

**Account Number**
38a99b8f1916eab0471ca1df26e7fe5e71d845e6ea5b233cd3d93a75097ea2d6

**Comment by thesanjeevsharma** [comment]
@YashovardhanSingh Not an issue. The way it's written right now is much more understandable.
