### ISSUE TITLE
Junior Python (Django) Developer

### ISSUE THREAD

**Issue by AmanJain27** [thenewboston-developers/Website#798]
Team: Junior Python (Django) Developer

{
  "title": Junior Python (Django) Developer,
  "isLead": false,
  "payPerDay": 2800,
  "createdDate": "2020-07-08T02:14:59.307535Z",
  "contributor": {
    "contributorId":
    "displayName": Aman Jain,
    "githubUsername": AmanJain27,
    "profileImage":
    "slackUsername": AmanJain
  }
}

**Comment by Hristijan95** [comment]
Only team leads are opening new contributor issues & only people who are hired are added as contributors.
