### ISSUE TITLE
Missing .NET Core SDK

### ISSUE THREAD

**Issue by ddyakov** [thenewboston-developers/Website#802]
**Bug Description**
Missing .NET Core SDK team name on the teams page.

**Steps to Reproduce**
1. Go to https://thenewboston.com/teams'
2.  See that the .NET Core SDK team name is missing

**Expected behavior**
The .NET Core SDK team name should be there since there are people working on it.

**Actual behavior**
Explained in the Bug Description.

**Screenshots/Recordings**
![image](https://user-images.githubusercontent.com/11051204/99070913-6e020f80-25b1-11eb-9fa5-4330d1266b2e.png)

**OS and Browser**
I am using Windows 10 and Chrome but this applies to all OS and browsers.

**Account Number**
f867dd69de4657143261b1f03f3e120e7cc4453ae8d77bce2a047d1989ef26ec

**Comment by hasham56** [comment]
@ddyakov Can you mention people who are working on it please? so i can add them in the ".NET Core SDK team" option

**Comment by ddyakov** [comment]
> @ddyakov Can you mention people who are working on ".NET Core SDK team" please? so i can add them in the ".NET Core SDK team" option

I don’t know 100% who are the contributors but there are a few people that open PRs often and are very active in the slack channel for the sdk. I have asked who is working daily on that and as soon as I have an answer I’ll post the people here or send you a PM. :)

**Comment by Mirch** [comment]
So far, it's been:
(me) Mircea Teodor Oprea / @Iammirch
- Joshua Santiago / @joshman1019
- Charalampos Makrylakis / @xmac11 
- Nish? I don't have any last name for him / @nishp77

**Comment by theCow61** [comment]
Added the .NET tab to the Teams like you wanted and added those 4 contributors to the section though the info I put wasn't correct because I do not know any of the 4's pay per day and slack so I set it as empty. I am new to this so sorry if I did it wrong.

**Comment by xmac11** [comment]
Hello everyone, 
Thank you for considering adding us on the teams page, however we haven't been hired by anyone from the team and aren't being paid daily, just contributing at our own pace. 
So I would suggest that the .NET Core SDK follow the Kotlin SDK and just display the Team Lead / @Mirch

**Comment by theCow61** [comment]
Does the "Not Ready" tag mean that this feature isn't to be added yet and the PR wont get approved until it is ready?

**Comment by lapstjup** [comment]
@theCow61 Yes

**Comment by v6-afk** [comment]
Why can't the Engineers just add another link to that page with the title ".NET Core SDK Team" and then edit the names of the members on the new linked webpage as they are being updated.  As for not showing on all OS and browsers, I've experienced this sort of stuff before in my country( it was widespread), I suggest that you use a popular programming language and a relatively old one at that (you get?) and see what happens. Nothing fancy.

**Comment by v6-afk** [comment]
Okay, There was an issue in my area not quite long ago.
When a page refuses to load on different os and browsers. It was discovered
that the programming language used were relatively "new" languages and the
browser didn't support such languages. I feel Java, JavaScript and html and
the likes might help with such issues. I do not know the current status of
things but I'm just suggesting

**Comment by lapstjup** [comment]
@v6-afk Actually there was no entry for ".NET Core SDK" team in our code for the website. So the issue just states to add them since there has been development going on the respective repo. 
There are no OS and browser inconsistency issues here.

**Comment by v6-afk** [comment]
Oh, okay, i got the impression because of this👇. Thanks for the
clarification.

**Comment by v6-afk** [comment]
I got the impression because of this. Thanks for the clarification.

**Comment by buckyroberts** [comment]
Closing. New teams will be added by the core team.
