### ISSUE TITLE
Update Marketing Site Landing Page

### ISSUE THREAD

**Issue by kristykjlee** [thenewboston-developers/Website#81]
**Update Marketing Site Landing Page elements/layout**

- Update newboston logo 
- Contributors, Developers, Roadmap will now be top nav
- Clicking on thenewboston logo will return user back to Landing Page
- Clicking Developers will link users to all the documentation, 'Guide, Bank API, Primary Validator API, etc...'
- Copy text directly from mocks
- Make slack & github buttons both 114px width
- Include slack & github logos inside buttons
- Send Points image has a dropshadow of X: 15, Y: 15, Blur: 40, Hex #: 042235, Opacity: 25%
- In-App 'Banks' image has a dropshadow of X: 0, Y: 15, Blur: 40, Hex #: 042235, Opacity: 25%
- Kill Roboto, please use **Helvetica Neue** for all text on marketing site
- Please make sure to use thenewboston logo inside the 'View Guide' button

**Update Colors:**

- Background color 1: #F6F9FC
- Background color 2: #131F41
- ALL text color: #042235
- Secondary button color: #C1C9D2
- Primary button color: #042235

**Figma**

https://www.figma.com/file/ChyT88EmP2Rmzx35I9erCL/Marketing-Site?node-id=6%3A0

<img width="778" alt="Screen Shot 2020-07-19 at 12 03 54 PM" src="https://user-images.githubusercontent.com/8547538/87882855-f3850280-c9b7-11ea-90ff-3603a150e516.png">

**Comment by kristykjlee** [comment]
<img width="384" alt="Send Points Modal" src="https://user-images.githubusercontent.com/68207101/87882957-ba00c700-c9b8-11ea-865b-8294e4748fc6.png">
<img width="1366" alt="Banks Full Data" src="https://user-images.githubusercontent.com/68207101/87882961-c08f3e80-c9b8-11ea-910f-4f691c1b9766.png">

**Comment by jacobclevenger** [comment]
Picking up.
