### ISSUE TITLE
Two Active banks at a same time?

### ISSUE THREAD

**Issue by AmanJain27** [thenewboston-developers/Website#822]
I think config.json file lets you have 2 active banks at a same time. 

**Steps to Reproduce**
1. Go to '/home/{linux user name folder}/.config/TNB Account Manager/' folder.
2. Edit the config.json on the line which says "is_default" : "false" to "true" under managed banks section.
3. Make sure that all the banks that you currently use have the value set to true.
3. then execute the TNB software.
4. You'll see that both the banks are marked active.

**Expected behavior**
I'm unsure as to what it may lead to. Its mostly client side and should not affect the server side functionality. I did not perform any transactions through the banks to check the issue as I currently don't own any coins. I'd still like you to at least check the functionality if this has some real effect on the working on banks. But I think this may cause some conflict between the banks or worse, the transaction may take place through both the banks if the issue affects the server side. 

I am attaching a screenshot of my TNB software indicating two active banks
![tnb](https://user-images.githubusercontent.com/42290198/99146382-97986500-269d-11eb-971d-0ce0c69544ab.png)

**Account Number**
eef9c0570d9d8eab23fed3f997cce01abec4e56922fbdff5d9caa4420e47a3e0

**Comment by lapstjup** [comment]
Hi @AmanJain27 you can create this issue in Account Manager repo. Closing it here.
