### ISSUE TITLE
[Bug]Website buttons in navigation have double focus.

### ISSUE THREAD

**Issue by nparoski** [thenewboston-developers/Website#830]
**Bug Description**
While navigation with `Tab` in top nav buttons like _Download_ button have double focus because `<Link>` has nested `<Button>` inside..

**Steps to Reproduce**
1. Go to Any page
2. Click on Top navbar
3. Start pressing tab, on 5th and/or 6th press `Enter`
4. You will be redirected to `/download` 

**Expected behavior**
Only one focus per interactive element

**Actual behavior**
One element has two focuses.

**Account Number**
`848a2743f581f4bb1dee0236474293690de7586aa235d32c427982e4a28fef77`

[How to Create an Account](https://thenewboston.com/account-manager/create-an-account)

**Comment by nparoski** [comment]
Created PR #831 for this issue.

**Comment by lapstjup** [comment]
@nparoski Thanks for raising this issue. I have pushed a commit to your PR to bring back button's outline for accessibility. There still might be other elements behaving the same way as you did. It would be good if you do the fix for all of those as well.

**Comment by nparoski** [comment]
@lapstjup Sure I will look into it right now and push fix as soon as possible.

**Comment by nparoski** [comment]
@lapstjup  I've found two more cases of double focus, I pushed fix to PR.
