### ISSUE TITLE
Design Redundancy in Navbar and Footer

### ISSUE THREAD

**Issue by mahihossain** [thenewboston-developers/Website#834]
**Bug Description**
The website has a fixed top navbar. It has a thenewboston logo which is a link to go to the homepage of the website. Scrolling down one comes across the same link and logo which does the exact same thing. This is a design redundancy. 

**Steps to Reproduce**
1. Go to 'https://thenewboston.com/'
2. Scroll down to the bottom where you can see the footer
3. See thenewboston logo which does the same thing in both the places

**Expected behavior**
Keeping the logo and link in the navbar produces a better design which is redundancy free. Which also requires repositioning the social media links logos. 

![SolutionSS](https://user-images.githubusercontent.com/23065512/99177892-00342000-2738-11eb-9898-f4a9f0fa52dd.png)

**Actual behavior**
In navbar and footer thenewboston logo is doing the same thing. They both take you to the homepage. 

![ProblemSS](https://user-images.githubusercontent.com/23065512/99177912-3bceea00-2738-11eb-8525-4d8d23ce067e.png)

**OS and Browser**
 - OS: Windows 10
 - Browser: Chrome

**Account Number**
def3963e9afcdb0e7e9c00077bea51bd7233540b41eb78a384c2567986b4edf3

**Comment by lapstjup** [comment]
@manishram Can you confirm the same with design team ?

**Comment by manishram** [comment]
Sure @lapstjup

**Comment by mahihossain** [comment]
I have made a pull request regarding this.

**Comment by manishram** [comment]
Hey @lapstjup , **kristykjlee** said that team is reworking on product development so this is not the priority at this moment.

Thankyou @mahihossain for your contribution. You are welcome to work on other issues.

**Comment by mahihossain** [comment]
> Hey @lapstjup , **kristykjlee** said that team is reworking on product development so this is not the priority at this moment.
> 
> Thankyou @mahihossain for your contribution. You are welcome to work on other issues.

Should I stop giving design suggestions? Rather focusing on other issues?

**Comment by kandarpgautam** [comment]
> Hey @lapstjup , **kristykjlee** said that team is reworking on product development so this is not the priority at this moment.
> 
> Thankyou @mahihossain for your contribution. You are welcome to work on other issues.

This might not be a priority but it's not just redundant "thenewboston" icon, but 3 of the icons are there on page which are also in footer. The 3 icons there don't make much sense. Keeping all the social networks icons in footer would be better. Adjustments might not be the priority right now, but we can fix this as long as people are willing to help and contribute. Any help would do. Before next release, UI must be polished.

**Comment by mahihossain** [comment]
@kandarpgautam I am perfectly willing to help in these issues! I have also made PRs.
