### ISSUE TITLE
Only three Social Media Icons in the Home page

### ISSUE THREAD

**Issue by mahihossain** [thenewboston-developers/Website#836]
**Bug Description**
There are only three Social Media icons available on the Home page though we have seven available.

**Steps to Reproduce**
1. Go to 'https://thenewboston.com/'
2. There are only three Social Media icons available on the page
3. Scroll down to the footer, there are seven of them

**Expected behavior**
All seven Social Media icons should be visible.

![SolutionSS](https://user-images.githubusercontent.com/23065512/99179226-c8cc7000-2745-11eb-8c4c-78002bac03fa.png)

**Actual behavior**
Only three Social Media Icons are visible.

![ProblemSS](https://user-images.githubusercontent.com/23065512/99179216-a9cdde00-2745-11eb-9726-45a606cb92a6.png)

**OS and Browser**
 - OS: Windows 10
 - Browser: Chrome

**Account Number**
def3963e9afcdb0e7e9c00077bea51bd7233540b41eb78a384c2567986b4edf3

**Comment by Hristijan95** [comment]
@kristykjlee , can you take a look at this? Is it intended, or we should add all icons there?

**Comment by nsushman** [comment]
@mahihossain, Introducing all the icons over there is going to cause a lot of clutter and draw the visitor's attention away from the text. This should be treated as an improvement since the current design specification did contain that part as it is.

**Comment by kandarpgautam** [comment]
> @mahihossain, Introducing all the icons over there is going to cause a lot of clutter and draw the visitor's attention away from the text. This should be treated as an improvement since the current design specification did contain that part as it is.

To avoid clutter, we can add a see more button there. Like hidden div section holding rest of the icons.

**Comment by mahihossain** [comment]
@kandarpgautam @nsushman I think if we put three there we have to put all there even making them hidden... Otherwise we can remove them altogether. It doesn't make sense only putting three there. Also it will not be as redundant as it seems because it is only on the homepage.

**Comment by kandarpgautam** [comment]
I think if rest of the icons are in footer, we can just keep them in footer. Also there's "thenewboston" icon in footer. Which is redundant as a user can easily go to index page by clicking on the one in the menu which is present at all times in both desktop and mobile interface.

**Comment by mahihossain** [comment]
> I think if rest of the icons are in footer, we can just keep them in footer. Also there's "thenewboston" icon in footer. Which is redundant as a user can easily go to index page by clicking on the one in the menu which is present at all times in both desktop and mobile interface.

@kandarpgautam I gave that suggestion here #834. But no result!

**Comment by ffpetrovic** [comment]
Add a toggle or something, so the user at least knows there's more possibilities without having to find that out once they get to the footer.
![image](https://user-images.githubusercontent.com/5026566/99276428-f3452880-282c-11eb-9ad2-784a1e373411.png)

**Comment by mahihossain** [comment]
@ffpetrovic that's a good idea. Will work on that.

**Comment by mahihossain** [comment]
> Add a toggle or something, so the user at least knows there's more possibilities without having to find that out once they get to the footer.
> ![image](https://user-images.githubusercontent.com/5026566/99276428-f3452880-282c-11eb-9ad2-784a1e373411.png)

@ffpetrovic that's a good idea. Will work on that.

**Comment by Hristijan95** [comment]
Guys, please avoid working on issues that have the "Not Ready" label, because your work can be for nothing. For this particular issue, we need approval from the design team, once we have that, we'll change the status of the issue.

**Comment by ffpetrovic** [comment]
@Hristijan95 so is the official procedure

1. Wait for an issue to lose it's "Not Ready" label
2. Be the first to say "I'll take this one"?

Whatever it is I think it needs to be very clearly defined, otherwise people will just race to make a PR. Sorry if missed this official procedure somewhere. If it exists, please let us know ❤️

**Comment by Hristijan95** [comment]
@ffpetrovic , yeah, that is the procedure. It's not clearly defined yet(and it's not written clearly as well), but it will be very soon, all teams are working very hard on organizing things as fast as possible, we just have to be patient for a few more days. For now we can manage it like this. :)
Thanks for contributing.

**Comment by mahihossain** [comment]
> Guys, please avoid working on issues that have the "Not Ready" label, because your work can be for nothing. For this particular issue, we need approval from the design team, once we have that, we'll change the status of the issue.

@Hristijan95 Ok! Thanks for telling me that! Better to work later when it's ready! But when it is ready, I want to take this.

**Comment by ffpetrovic** [comment]
@Hristijan95 Thank you for clearing it up! 🙂

**Comment by kristykjlee** [comment]
This has been moved to the Design Repository
