### ISSUE TITLE
Fix console warnings during development

### ISSUE THREAD

**Issue by lapstjup** [thenewboston-developers/Website#863]
**Bug Description**
I can see two console warnings coming during development.

**Steps to Reproduce**
1) Go to Assets Page for the general react key warning.
2) The second one is little tricky to reproduce but it happens when you move from Home to any other page.

**Screenshots/Recordings**
<img width="1022" alt="Screen Shot 2020-11-16 at 8 32 00 PM" src="https://user-images.githubusercontent.com/29139815/99268809-a6247f00-284b-11eb-87e0-c480f357438c.png">

**Comment by whitelionx** [comment]
I will have a look at this one 👍

**Comment by jamessspanggg** [comment]
I couldn't really reproduce the second issue...

**Comment by lapstjup** [comment]
@jamessspanggg Try switching your page when the next language rendition **hello world** it going to appear. That's probably where the memory leak would be happening.

**Comment by jamessspanggg** [comment]
Managed to replicate and solve both issues. @whitelionx if you don't mind, may I create a PR for this?

**Comment by whitelionx** [comment]
Yeah you can @jamessspanggg
