### ISSUE TITLE
New Contributor

### ISSUE THREAD

**Issue by Hristijan95** [thenewboston-developers/Website#866]
Team: Front-End Developers

{
  "title": Front-End Developer,
  "isLead": false,
  "payPerDay": 2800,
  "createdDate": "2020-11-14T02:14:59.307535Z",
  "contributor": {
    "contributorId": [CONTRIBUTOR ID],
    "displayName": Nine,
    "githubUsername": whitelionx,
    "profileImage": https://avatars1.githubusercontent.com/u/31674307?s=460&u=89b8153755b6765cbdc0b2579d8f545138b4760c&v=4,
    "slackUsername": Nine
  }
}

**Comment by DinShpati** [comment]
I can do this
