### ISSUE TITLE
Make an Image component with optimizations for image loading

### ISSUE THREAD

**Issue by jamessspanggg** [thenewboston-developers/Website#869]
**Current**
The leaderboard page loads github user avatars of size 460px, whereas the size of the div is 178px (desktop) and 54px (others). It is not needed to load such a big sized image for a small div.

May cause performance issues if there are more contributors, or the client does not have good device network.

Desktop:
<img width="1179" alt="Screen Shot 2020-11-17 at 12 40 02 AM" src="https://user-images.githubusercontent.com/32864116/99281554-9a49b480-286d-11eb-8954-b029bf5bcab4.png">

Mobile:
<img width="1430" alt="Screen Shot 2020-11-17 at 12 39 45 AM" src="https://user-images.githubusercontent.com/32864116/99281540-95850080-286d-11eb-9918-c69bad505acc.png">

**Suggestion**
Make an Image component and possibly optimise image loading using `srcset`, loading the appropriate size based on device widths.

Acc no: c54c04774efaae20746fd3f29cdd619fea512e119bc1082b863572b2e8844104

**Comment by lapstjup** [comment]
@thesanjeevsharma @Hristijan95 I like this suggestion. Maybe we can have an Image component that abstracts all this and is reusable ?

**Comment by Hristijan95** [comment]
I agree, would be nice to have that.

**Comment by lapstjup** [comment]
@jamessspanggg I have increased the scope of this issue. Nice suggestion btw.

**Comment by jamessspanggg** [comment]
> @jamessspanggg I have increased the scope of this issue. Nice suggestion btw.

May I clarify that the image component should be specific for the github avatar images? If so, then should the size of image at desktop and others be hardcoded or based on the passed in values?

**Comment by lapstjup** [comment]
@jamessspanggg A reusable component would be good. Not specific to github and passed in values.

**Comment by jamessspanggg** [comment]
Am busy with school exams atm, this issue is opened for anyone to solve!
