### ISSUE TITLE
Kotlin SDK new member (Peter Sommerhoff)

### ISSUE THREAD

**Issue by IanArb** [thenewboston-developers/Website#877]
Team: Kotlin SDK

{
  "title": Software Developer,
  "isLead": false,
  "payPerDay": 2800,
  "createdDate": "2020-07-08T02:14:59.307535Z",
  "contributor": {
    "contributorId": [CONTRIBUTOR ID],
    "displayName": Peter Sommerhoff,
    "githubUsername": https://github.com/petersommerhoff,
    "profileImage": https://avatars2.githubusercontent.com/u/2805791?s=460&u=5fcb7424015f63ae2194171c5649af332ab59f05&v=4,
    "slackUsername": Peter Sommerhoff,
  }
}

**Comment by nparoski** [comment]
I can take this one

**Comment by nparoski** [comment]
Since @sdhiaeddine made PR before me I will close my PR #880
