### ISSUE TITLE
Kotlin SDK New Contributor Martin Nowosad

### ISSUE THREAD

**Issue by IanArb** [thenewboston-developers/Website#878]
Team: Kotlin SDK

{
  "title": Team Lead,
  "isLead": true,
  "payPerDay": 2800,
  "createdDate": "2020-07-08T02:14:59.307535Z",
  "contributor": {
    "contributorId": [CONTRIBUTOR ID],
    "displayName": Martin Nowosad
    "githubUsername": https://github.com/MrIceman,
    "profileImage": https://ca.slack-edge.com/T07PJD1FZ-U016SCACHM4-1a824cfe8763-512
    "slackUsername": Martin Nowosad
  }
}

**Comment by sdhiaeddine** [comment]
I will take this issue
