### ISSUE TITLE
Decouple Hello World animation and word shuffle logic using custom hooks

### ISSUE THREAD

**Issue by lapstjup** [thenewboston-developers/Website#890]
**Bug Description**
The current implementation of Hello World animation and word shuffling that comes on Home page is tightly coupled but it can be divided into two hooks - useAnimationState and useShuffle.

**Additional context**
This is an open ended problem and the best solution would fetch the reward coins.

**Comment by savans2** [comment]
I would like to take the shot at this.

**Comment by harshilparmar** [comment]
I would also lilke to try this 😄

**Comment by ffpetrovic** [comment]
@lapstjup What you just said contradicts what @Hristijan95 says is the [official procedure](https://github.com/thenewboston-developers/Website/issues/836#issuecomment-728441196). Is it

>Wait for an issue to lose it's "Not Ready" label
>Be the first to say "I'll take this one"?

or

> the best solution would fetch the reward coins.

The first one means that people with the most free time will keep camping the Issues page and theoretically grab any chance they get, while the second one means that (this one is subjective to the maintainers of this repo), the *best* solution wins. Bear in mind this might dishearten less experienced people or put them off altogether.

**Comment by aayushi14** [comment]
@ffpetrovic For all such Developers who get disheartened if they don't win in a Hackathon, I believe whoever is inexperienced or whose PR is not selected to be merged, must come back to see the PR which is merged and learn from that code. Developers must always have the urge to learn and get better.

**Comment by lapstjup** [comment]
@ffpetrovic Hey thanks for raising the concern. So as I mentioned explicitly here - this is open ended problem. 
There can be different approaches by different people and everyone (including me) can learn which is the best one that works. The coins surely do motivate but we are trying to build a community of people who can learn from each other as well. 

Also this issue doesn't have "Not Ready" label from the start. And it is meant to be taken by different people.

We are still in process of having defined guidelines for such stuff. I know uncertainty about such stuff sucks but for this particular issue you're more than welcome to give it your own take.

**Comment by lapstjup** [comment]
@harshilparmar Think of it as this way.

The shuffling logic is dependent on when a particular condition becomes true.

In our case, it is a animation state. But what if you had to shuffle something based on a button click or any other event ?

There is an opportunity here for us to decouple both. 

Similarly animationState can be used by other components too. Doesn't have to be just fade_in and fade_out. You can map that animationState to anything you like.

**Comment by DrSparky-2007** [comment]
I updated the code in HomeHero/index.tsx and have added [pull request #945](https://github.com/thenewboston-developers/Website/pull/945). One thing that I could've imporoved was the `fadeInOut()` since it uses a stack variable.

**Comment by DrSparky-2007** [comment]
I updated the code in HomeHero/index.tsx and have added pull request #945 . One thing that I could've imporoved was the fadeInOut() since it uses a stack variable.
