### ISSUE TITLE
Slack link is invalid

### ISSUE THREAD

**Issue by Ramin-RX7** [thenewboston-developers/Website#903]
**Bug Description**
when I Click on slack link I see this page (link is no longer active), and when I'm logged in in slack, it will redirect me to last page of slack I were.
I saw this link in main page and footer (but I don't know where else is it)

**Screenshots/Recordings**
![Screenshot (18)](https://user-images.githubusercontent.com/52785580/99572020-52e83300-29e9-11eb-8e30-80e67b7c8e23.png)

**Comment by kandarpgautam** [comment]
Exactly. I checked it. It's not working.

**Comment by kandarpgautam** [comment]
Can someone provide slack link?

**Comment by Hristijan95** [comment]
Someone already changed the slack link, so I am closing this. Thanks for the report.
