### ISSUE TITLE
Clean and Crawl Docs

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Website#924]
We have new API endpoints and also WebSocket logic for our crawl and clean processes. These need to be documented on the website.

Please check with @charnysh-dev (**Dzianis** on Slack) for HTTP endpoints, WebSocket endpoints, and request/response/message shapes. He worked on this feature recently.

**Note:** These processes are available on Banks and Confirmation Validators (but not PVs)

<img width="372" alt="Screen Shot 2020-11-19 at 1 09 12 PM" src="https://user-images.githubusercontent.com/8547538/99724499-88803100-2a68-11eb-93ed-953d7f1d9670.png">

**Comment by VincentHch** [comment]
I can take this one. I should find all informations in the **Validator** and **Bank** repo. @charnysh-dev I'll reach you on Slack if I need further informations.

**Comment by VincentHch** [comment]
Hey @angle943, my account number is **aaf42054f84c66586bf29d446188347ab910112cb60b775a4d6feadd5b9ae73f**
