### ISSUE TITLE
Bank API - Update documentation on website to match the actual responses

### ISSUE THREAD

**Issue by velibor7** [thenewboston-developers/Website#926]
Documentation on Bank API page https://thenewboston.com/bank-api/accounts does not match actual responses from django rest framework.

To see actual responses go to:
143.110.137.54 - Bank IP or
54.183.17.224 - Validators IP

This needs to be updated for all endpoints

**Comment by buckyroberts** [comment]
Closing, creating standardized issues for all doc updates
