### ISSUE TITLE
Website email newsletter form

### ISSUE THREAD

**Issue by kristykjlee** [thenewboston-developers/Website#931]
- Add email newsletter form popup when the user comes onto thenewboston for the very first time
- Add email newsletter form to the footer of the website as well. Must be on every pages footer
- Please make sure to store the emails in the backend. We eventually want to be able to collect the emails so we can start doing email campaigns. 

https://www.figma.com/file/cOHTkvpRXzPIQGjCotrP4y/Email-Newsletter?node-id=0%3A1

**Comment by whitelionx** [comment]
@thesanjeevsharma is there an endpoint to which we can send the email?

**Comment by thesanjeevsharma** [comment]
@whitelionx I'll ask BE team about this. Meanwhile, contibutors can start with the FE part of it.  API can be added later, before merging!

**Comment by whitelionx** [comment]
Then I will grab this issue and prepare the frontend side of things and after you get the endpoint we can do an easy post request to store it 👍 @thesanjeevsharma

**Comment by whitelionx** [comment]
Is there any feedback from the BE, the FE is almost done, just optimizing stuff for other device widths as well @thesanjeevsharma

**Comment by whitelionx** [comment]
![image](https://user-images.githubusercontent.com/31674307/99815187-45968a00-2b4a-11eb-9a5d-a38117f68c21.png)

**Comment by thesanjeevsharma** [comment]
It's not available yet! You can submit a PR. We'll merge once the endpoint is ready.

**Comment by whitelionx** [comment]
Thanks for the feedback, will push it soon @thesanjeevsharma

**Comment by whitelionx** [comment]
I also prepared the mobile layout since it wasn't in the design, is this okay for mobile @kristykjlee 
![image](https://user-images.githubusercontent.com/31674307/99821194-066c3700-2b52-11eb-92f2-749a29c46691.png)

**Comment by buckyroberts** [comment]
Closing in place of the new sign up flow which will already require the users email.
