### ISSUE TITLE
[Windows]The Footer content In tab device alignment position in center

### ISSUE THREAD

**Issue by webdeveloperswj** [thenewboston-developers/Website#932]
**Bug Description**
Footer content too much left side making Center alignment position

**Steps to Reproduce**
1. Go to "https://thenewboston.com/"
2. click on mouse right click 
3. Select inspect
4. Select iPad device
5.scroll down to footer

**Expected behavior**
footer content in center alignment position

**Actual behavior**
Footer content left side

**Screenshots/Recordings**
https://prnt.sc/vmlgrn.

**OS and Browser**
 - OS: [ Windows 10]
 - Browser [Chrome]

**Comment by Hristijan95** [comment]
@mersimoski , isn't this the same thing you mentioned yesterday?
There's also a centering problem on the desktop version (although it shouldn't be centered on the desktop, I think it's better to align the links to the right side).

**Comment by mersimoski** [comment]
@Hristijan95 Yes, https://github.com/thenewboston-developers/Design/issues/26

**Comment by Hristijan95** [comment]
Yep, gonna close this one as a duplicate.
