### ISSUE TITLE
Projects Proposal page

### ISSUE THREAD

**Issue by kristykjlee** [thenewboston-developers/Website#934]
- We need to include Projects Proposal onto the marketing site to give people awareness of being able to create proposals as well as steps on how to do so. 
- Include all the text that is written in this doc onto the Project Proposals page. https://docs.google.com/document/d/1-FfsgfpBlCXhjlx_9-04cFsMw-mRoekjqXn7x2qxpbk/edit?usp=sharing
- Design: https://www.figma.com/file/F9sI5Lw376V7hy5RGXUXNb/Project-Proposals?node-id=0%3A1
- Side menu is autoscroll (like Documentations page)
- Project Proposals page will be under 'More' nav

**Comment by manishram** [comment]
Hey, @kristykjlee please update the design link. Either the link is private or broken.

**Comment by AbhayAysola** [comment]
I'm willing to try to do this, could I be assigned this issue?

**Comment by buckyroberts** [comment]
Here are the images for now. I don't have permission to share the Figma file though :-/

<img width="1920" alt="NewDropdownItem" src="https://user-images.githubusercontent.com/8547538/99892593-2885b800-2c2b-11eb-898a-905d44554cb2.png">

<img width="1366" alt="ProjectProposals" src="https://user-images.githubusercontent.com/8547538/99892595-2c193f00-2c2b-11eb-846a-8c19ba36389a.png">
