### ISSUE TITLE
Typos in the docs

### ISSUE THREAD

**Issue by alexkimeu0** [thenewboston-developers/Website#935]
![1](https://user-images.githubusercontent.com/61450115/99789112-293b2300-2b33-11eb-9d51-6655048d6179.jpg)
![2](https://user-images.githubusercontent.com/61450115/99789131-2f310400-2b33-11eb-84fc-7c184371bfed.jpg)
![3](https://user-images.githubusercontent.com/61450115/99789146-322bf480-2b33-11eb-9d6d-b1063237fb7e.jpg)
![4](https://user-images.githubusercontent.com/61450115/99789162-33f5b800-2b33-11eb-9567-6f28785ccad8.jpg)

**Comment by Hristijan95** [comment]
If possible, please take the time to take a look at the rest of the docs and fix any additional texts.
I will change the PR Reward to a higher amount if needed.

**Comment by alexkimeu0** [comment]
Sure. I'll go through the rest.

**Comment by osaroadade** [comment]
I would like to start working on this. Can I proceed?

**Comment by Hristijan95** [comment]
@osaroadade , this issue is already assigned to @alexkimeu0.

**Comment by osaroadade** [comment]
Oh okay. 😁
