### ISSUE TITLE
Proposal to add e2e tests with Cypress

### ISSUE THREAD

**Issue by Twaha-Rahman** [thenewboston-developers/Website#946]
Hello there, new contributor here. :wave: 

Looking at the project's source code, I don't see any e2e tests. I'd love to add e2e test with Cypress as I have a lot of experience doing so.

So, should I jump right in? Or is there anything that I'm missing? Please do let me know. :smiley:

**Comment by Twaha-Rahman** [comment]
Umm... what's the process to move this forward?

**Comment by Hristijan95** [comment]
@Twaha-Rahman, we planned to start integrating testing as soon as the API integration is done (which would be this next week). So until that happen, we'll have this issue waiting with the "Not Ready" label.

I can let you know & assign you this issue once it's ready if you want. Sorry for the super late response.

**Comment by Twaha-Rahman** [comment]
@Hristijan95 Sure, let me know when we're ready to go forward!

**Comment by Twaha-Rahman** [comment]
I'm closing this issue as it is stale. Feel free to re-open if it's not the case.
