### ISSUE TITLE
Update Docs for Bank - Accounts

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Website#951]
Update documentation and sample code for Bank - Accounts
- ensure all available endpoints (`GET`, `POST`, `PATCH`, and `DELETE`) are documented
- update request and response examples from real API data (2 items for `GET` list responses)
- JSON should be formatted with 2 space indents
- ensure any/all params are documented in tables
- https://thenewboston.com/bank-api/accounts

**Comment by velibor7** [comment]
I will take this and do it later today :)
