### ISSUE TITLE
Update Docs for Bank - Banks

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Website#953]
Update documentation and sample code for Bank - Banks
- ensure all available endpoints (`GET`, `POST`, `PATCH`, and `DELETE`) are documented
- update request and response examples from real API data (2 items for `GET` list responses)
- JSON should be formatted with 2 space indents
- ensure any/all params are documented in tables
- https://thenewboston.com/bank-api/banks

**Comment by DucPhamTV** [comment]
I will take it.
