### ISSUE TITLE
Update Docs for Bank - Config

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Website#955]
Update documentation and sample code for Bank - Config
- ensure all available endpoints (`GET`, `POST`, `PATCH`, and `DELETE`) are documented
- update request and response examples from real API data (2 items for `GET` list responses)
- JSON should be formatted with 2 space indents
- ensure any/all params are documented in tables
- https://thenewboston.com/bank-api/config

**Comment by velibor7** [comment]
I will take this

**Comment by VincentHch** [comment]
@buckyroberts you can close this issue, the documentation for all config endpoints are up-to-date

**Comment by velibor7** [comment]
@VincentHch Not exactly, for example type of default_transaction_fee is integer on API, but in docs its a string, I just fixed it I think there is 2 or 3 more lines, also small mistakes, but not up to date :)

**Comment by shahraizali** [comment]
@velibor7 Good catch bud 👍
