### ISSUE TITLE
Update Docs for Bank - Invalid Blocks

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Website#957]
Update documentation and sample code for Bank - Invalid Blocks
- ensure all available endpoints (`GET`, `POST`, `PATCH`, and `DELETE`) are documented
- update request and response examples from real API data (2 items for `GET` list responses)
- JSON should be formatted with 2 space indents
- ensure any/all params are documented in tables
- https://thenewboston.com/bank-api/invalid-blocks

**Comment by VincentHch** [comment]
I'm on this one
