### ISSUE TITLE
Update Docs for Bank - Validator Confirmation Services

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Website#959]
Update documentation and sample code for Bank - Validator Confirmation Services
- ensure all available endpoints (`GET`, `POST`, `PATCH`, and `DELETE`) are documented
- update request and response examples from real API data (2 items for `GET` list responses)
- JSON should be formatted with 2 space indents
- ensure any/all params are documented in tables
- https://thenewboston.com/bank-api/validator-confirmation-services

**Comment by DucPhamTV** [comment]
I take this.

**Comment by DucPhamTV** [comment]
Still working on it. I setup a local network. Bank try to pay confirmation service from CV. The bank send /bank_blocks to PV but celery service on PV doesn't propagate the block to CV. I added debug log in v1/tasks/block_queue.py and no log printed out. Still checking the PV setup.

**Comment by Hristijan95** [comment]
@DucPhamTV are you still working on this?

**Comment by DucPhamTV** [comment]
Almost forgot this one. Thanks for reminding me. I will finish it soon.
