### ISSUE TITLE
Update Docs for Bank - Upgrade Notice

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Website#960]
Update documentation and sample code for Bank - Upgrade Notice
- ensure all available endpoints (`GET`, `POST`, `PATCH`, and `DELETE`) are documented
- update request and response examples from real API data (2 items for `GET` list responses)
- JSON should be formatted with 2 space indents
- ensure any/all params are documented in tables
- https://thenewboston.com/bank-api/upgrade-notice

**Comment by tomijaga** [comment]
![Capture](https://user-images.githubusercontent.com/50385769/102176742-11c03300-3e70-11eb-8c56-ab50331d1b3a.PNG)

I'm trying to get the upgrade notice response but I keep getting a "Bad Signature" Error

I replaced the bank_node_identifier and the node_identifier from the example request with the ones on the TNB Account Manager desktop app. I don't know how to get the Signature

{
  "message": {
    "bank_node_identifier": "6873729b23663df345c9a03d8b9b0686f245f4cab6b869eb60d794b81bfd33bb"
  },
  "node_identifier": "9dd8825ae8bce326df4da8a02ab4345d3f5cb63f579e88018d8b480fdafe2a8d",
  "signature": "e9862cf176523449417b5f3426cb7bf0a3813ef04fae3330faa50b6468d9da9c55967a24c40040eaa6bc33843804bda9a0307bffe906ed8c7b2a55c15dabaa0d"
}

**Comment by gsonly** [comment]
I don't really know what going on here, but I would like to contribute... :smile:

**Comment by buckyroberts** [comment]
Closing in favor of newer sync model (still architecting)
