### ISSUE TITLE
Update Docs for Primary Validator - Bank Blocks

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Website#963]
Update documentation and sample code for Primary Validator - Bank Blocks
- ensure all available endpoints (`GET`, `POST`, `PATCH`, and `DELETE`) are documented
- update request and response examples from real API data (2 items for `GET` list responses)
- JSON should be formatted with 2 space indents
- ensure any/all params are documented in tables
- https://thenewboston.com/primary-validator-api/bank-blocks

**Comment by wajeehmisbahkhan** [comment]
I can work on this, currently setting up the bank locally to test out these endpoints.

**Comment by DucPhamTV** [comment]
I take this
