### ISSUE TITLE
Update Docs for Primary Validator - Confirmation Blocks

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Website#966]
Update documentation and sample code for Primary Validator - Confirmation Blocks
- ensure all available endpoints (`GET`, `POST`, `PATCH`, and `DELETE`) are documented
- update request and response examples from real API data (2 items for `GET` list responses)
- JSON should be formatted with 2 space indents
- ensure any/all params are documented in tables
- https://thenewboston.com/primary-validator-api/confirmation-blocks

**Comment by UweVanOpfern** [comment]
I will take this one

**Comment by UweVanOpfern** [comment]
I have a question on second point of requirements, this **(2 items for GET list responses)**
Its saying to return alteast 2 items but, this one returns only one block with help of block identifier, 
Endpoint formatted like this, **/confirmation_blocks/<block_identifier>/valid**
This one returns single item in this case return only one block passed as block_identifier

**Comment by UweVanOpfern** [comment]
This issue was solved with this PR [Documentation]: Updated Docs for Bank - Bank Transactions #952 #986

**Comment by Rajputusman** [comment]
@UweVanOpfern You have been Paid for this PR?

**Comment by UweVanOpfern** [comment]
@Rajputusman thank you for you asking, No i did not
