### ISSUE TITLE
Update Docs for Confirmation Validator - Bank Confirmation Services

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Website#970]
Update documentation and sample code for Confirmation Validator - Bank Confirmation Services
- ensure all available endpoints (`GET`, `POST`, `PATCH`, and `DELETE`) are documented
- update request and response examples from real API data (2 items for `GET` list responses)
- JSON should be formatted with 2 space indents
- ensure any/all params are documented in tables
- https://thenewboston.com/confirmation-validator-api/bank-confirmation-services

**Comment by UweVanOpfern** [comment]
I will take this one

**Comment by UweVanOpfern** [comment]
When i try to this endpoint
**| http://54.183.17.224/bank_confirmation_services**

I get an empty array results
Is any other way that I can get results to move on by working on this?
