### ISSUE TITLE
Update Docs for Confirmation Validator - Confirmation Blocks

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Website#973]
Update documentation and sample code for Confirmation Validator - Confirmation Blocks
- ensure all available endpoints (`GET`, `POST`, `PATCH`, and `DELETE`) are documented
- update request and response examples from real API data (2 items for `GET` list responses)
- JSON should be formatted with 2 space indents
- ensure any/all params are documented in tables
- https://thenewboston.com/confirmation-validator-api/confirmation-blocks

**Comment by CNFloss** [comment]
I can take this one!

**Comment by CNFloss** [comment]
@buckyroberts @thesanjeevsharma So I am using the JS lib on a test net I set up, and getting valid confirmation blocks is easy, but right now I am having trouble getting queued blocks.  the network is too fast I think, right now I use an API call to add a block to the bank and then I have to make another API to the bank call to grab the `block_identifier` for that newest block than I can make the API call to the confirmation validator for the queued or valid block.  So I think in the time that I am making the second API call to the bank the block is being moved from queued to valid.  So I guess my question for either of you is, do you have any ideas on how to get a `block_identifier` to be used in that short timeframe of being queued?

**Comment by bart-jay** [comment]
Is this project still available??

**Comment by buckyroberts** [comment]
Closing since alpha is being deprecated.
