### ISSUE TITLE
Update Docs for Confirmation Validator - Primary Validator Updated

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Website#975]
Update documentation and sample code for Confirmation Validator - Primary Validator Updated
- ensure all available endpoints (`GET`, `POST`, `PATCH`, and `DELETE`) are documented
- update request and response examples from real API data (2 items for `GET` list responses)
- JSON should be formatted with 2 space indents
- ensure any/all params are documented in tables
- https://thenewboston.com/confirmation-validator-api/primary-validator-updated

**Comment by wajeehmisbahkhan** [comment]
I can work on this, currently setting up the validator locally to test out this endpoint.
