### ISSUE TITLE
Update Docs for Confirmation Validator - Upgrade Request

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Website#976]
Update documentation and sample code for Confirmation Validator - Upgrade Request
- ensure all available endpoints (`GET`, `POST`, `PATCH`, and `DELETE`) are documented
- update request and response examples from real API data (2 items for `GET` list responses)
- JSON should be formatted with 2 space indents
- ensure any/all params are documented in tables
- https://thenewboston.com/confirmation-validator-api/upgrade-request

**Comment by wendtl** [comment]
I'd like to update the docs for this.
