### ISSUE TITLE
Add How to Set Up Payment Board Docs

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Website#990]
Add How to Set Up Payment Board documentation to the Internal documents section on the website.

- New User Operations - https://thenewboston.com/internal/new-user-operations
- Team Lead Onboarding - https://thenewboston.com/internal/team-lead-onboarding
- Product Development - https://thenewboston.com/internal/product-development
- **How to Set Up Payment Board - translate attached PDF to React**

[TNB Payments.pdf](https://github.com/thenewboston-developers/Website/files/5580660/TNB.Payments.pdf)

**Comment by AbhayAysola** [comment]
Can I work on this?

**Comment by lapstjup** [comment]
@AbhayAysola sure.
